using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using Microsoft.Win32;
namespace HdrPilot {
public static class Appearance {
 sealed class Value {public object Original,Last;}
 static ConditionalWeakTable<DependencyObject,Dictionary<DependencyProperty,Value>> saved=new ConditionalWeakTable<DependencyObject,Dictionary<DependencyProperty,Value>>();
 static bool light;
 static Dictionary<string,string[]> words=new Dictionary<string,string[]>();
 static readonly Dictionary<string,string> colors=new Dictionary<string,string>(StringComparer.OrdinalIgnoreCase){
 {"#A8141A22","#DCF7F8FA"},{"#C011161D","#E6E9EDF2"},{"#FF0C0F13","#F2F4F7"},{"#FF0D1118","#FFFFFF"},{"#FF11161D","#E9EDF2"},{"#FF141A22","#F7F8FA"},{"#FF171D26","#FFFFFF"},{"#FF1B222C","#E9EDF2"},{"#FF1C2631","#E7EDF3"},{"#FF202833","#FFFFFF"},{"#FF232A34","#FFFFFF"},{"#FF232D3B","#E4EAF1"},{"#FF242D39","#FFFFFF"},{"#FF242D3A","#D7DEE8"},{"#FF252F3C","#EDF1F6"},{"#FF26303B","#CCD4DF"},{"#FF27313C","#CCD4DF"},{"#FF293340","#CCD4DF"},{"#FF2A3541","#CCD4DF"},{"#FF303844","#C2CCD8"},{"#FF35404D","#B8C3D0"},{"#FF364150","#B8C3D0"},{"#FF465367","#B8C3D0"},{"#FF363018","#FAEACA"},{"#FF41331E","#FAEACA"},{"#FF514828","#FAEACA"},{"#FF2B281B","#FFF3D8"},{"#FF39414D","#A9B5C5"},{"#FF424C59","#A9B5C5"}
 };
 static Appearance(){
  Add("Controlla file e percorsi","Check files and paths","Revisar archivos y rutas","Vérifier les fichiers et chemins","Dateien und Pfade prüfen","Verificar arquivos e caminhos");
  Add("File installati","Installed files","Archivos instalados","Fichiers installés","Installierte Dateien","Arquivos instalados");
  Add("LA TUA LIBRERIA","YOUR LIBRARY","TU BIBLIOTECA","VOTRE BIBLIOTHÈQUE","DEINE BIBLIOTHEK","A TUA BIBLIOTECA");Add("▦   Libreria giochi","▦   Game library","▦   Biblioteca Steam","▦   Bibliothèque Steam","▦   Steam-Bibliothek","▦   Biblioteca Steam");Add("↻  Scansiona","↻  Scan","↻  Buscar","↻  Analyser","↻  Scannen","↻  Procurar");Add("Libreria…","Library…","Biblioteca…","Bibliothèque…","Bibliothek…","Biblioteca…");Add("Mostra anche Unreal da verificare","Show unverified Unreal games","Mostrar juegos Unreal por verificar","Afficher les jeux Unreal à vérifier","Unbestätigte Unreal-Spiele anzeigen","Mostrar jogos Unreal por verificar");Add("Più luce. Ogni dettaglio.","More light. Every detail.","Más luz. Cada detalle.","Plus de lumière. Chaque détail.","Mehr Licht. Jedes Detail.","Mais luz. Cada detalhe.");Add("HDR, DLSS 5 e mod grafiche. Senza complicazioni.","HDR, DLSS 5 & graphics mods. Simplified.","Activa HDR en juegos sin HDR nativo.","Activez le HDR dans les jeux sans HDR natif.","HDR in Spielen ohne natives HDR aktivieren.","Ativa HDR em jogos sem HDR nativo.");
  // Keep saved language choices; English is the default for new profiles.
  Add("Opzioni","Options","Opciones","Options","Optionen","Opções");Add("Lingua","Language","Idioma","Langue","Sprache","Idioma");Add("Aspetto","Appearance","Apariencia","Apparence","Darstellung","Aparência");Add("Chiaro","Light","Claro","Clair","Hell","Claro");Add("Scuro","Dark","Oscuro","Sombre","Dunkel","Escuro");Add("Come Windows","Follow Windows","Como Windows","Comme Windows","Wie Windows","Como Windows");Add("Chiudi","Close","Cerrar","Fermer","Schließen","Fechar");Add("Configura tasto overlay…","Overlay shortcut…","Tecla del overlay…","Raccourci de l’overlay…","Overlay-Taste…","Atalho do overlay…");Add("Tasto overlay…","Overlay shortcut…","Tecla del overlay…","Raccourci de l’overlay…","Overlay-Taste…","Atalho do overlay…");
  Add("Registro operazioni","Activity log","Registro de operaciones","Journal des opérations","Aktivitätsprotokoll","Registo de operações");Add("Apri log","Open log","Abrir registro","Ouvrir le journal","Protokoll öffnen","Abrir registo");Add("Avanzate","Advanced","Avanzadas","Avancées","Erweitert","Avançadas");Add("Avanzate e dettagli","Advanced and details","Avanzadas y detalles","Options avancées et détails","Erweitert und Details","Avançadas e detalhes");Add("Ripristina un componente","Restore a component","Restaurar un componente","Restaurer un composant","Komponente wiederherstellen","Restaurar um componente");
  Add("Guida per argomenti","Help topics","Temas de ayuda","Rubriques d’aide","Hilfethemen","Tópicos de ajuda");Add("Backup e dati","Backups and data","Copias y datos","Sauvegardes et données","Sicherungen und Daten","Cópias e dados");Add("Diagnostica overlay","Overlay diagnostics","Diagnóstico del overlay","Diagnostic de l’overlay","Overlay-Diagnose","Diagnóstico do overlay");Add("Gestione HDR","HDR method","Método HDR","Méthode HDR","HDR-Methode","Método HDR");Add("Configura ReShade / RenoDX…","Set up ReShade / RenoDX…","Configurar ReShade / RenoDX…","Configurer ReShade / RenoDX…","ReShade / RenoDX einrichten…","Configurar ReShade / RenoDX…");
  Add("Applica HDR","Apply HDR","Aplicar HDR","Appliquer HDR","HDR anwenden","Aplicar HDR");Add("▶  Avvia gioco","▶  Play game","▶  Iniciar juego","▶  Lancer le jeu","▶  Spiel starten","▶  Iniciar jogo");Add("Apri overlay live","Open live overlay","Abrir overlay en vivo","Ouvrir l’overlay","Live-Overlay öffnen","Abrir overlay ao vivo");Add("Chiudi overlay live","Close live overlay","Cerrar overlay","Fermer l’overlay","Overlay schließen","Fechar overlay");Add("Consigliati","Recommended","Recomendados","Recommandés","Empfohlen","Recomendados");Add("Ripristina","Restore","Restaurar","Restaurer","Wiederherstellen","Restaurar");Add("Verifica file","Verify files","Verificar archivos","Vérifier les fichiers","Dateien prüfen","Verificar ficheiros");
  Add("Picco luminoso","Peak brightness","Brillo máximo","Luminosité maximale","Spitzenhelligkeit","Brilho máximo");Add("Mezzitoni","Midtones","Tonos medios","Tons moyens","Mitteltöne","Tons médios");Add("Luminosità interfaccia","UI brightness","Brillo de la interfaz","Luminosité de l’interface","UI-Helligkeit","Brilho da interface");Add("Punto di nero","Black level","Nivel de negro","Niveau de noir","Schwarzwert","Nível de preto");Add("HDR avanzato","Advanced HDR","HDR avanzado","HDR avancé","Erweitertes HDR","HDR avançado");
  Add("Build","Build","Compilación","Version","Build","Versão");Add("Abilita Neural Rendering (DLSS 5)","Enable Neural Rendering (DLSS 5)","Activar Neural Rendering (DLSS 5)","Activer Neural Rendering (DLSS 5)","Neural Rendering aktivieren (DLSS 5)","Ativar Neural Rendering (DLSS 5)");Add("Risoluzione del modello","Model resolution","Resolución del modelo","Résolution du modèle","Modellauflösung","Resolução do modelo");Add("Stile","Style","Estilo","Style","Stil","Estilo");Add("Automatico","Automatic","Automático","Automatique","Automatisch","Automático");Add("Naturale","Natural","Natural","Naturel","Natürlich","Natural");Add("Cinematico","Cinematic","Cinemático","Cinématique","Filmisch","Cinematográfico");Add("Scheda video","Graphics card","Tarjeta gráfica","Carte graphique","Grafikkarte","Placa gráfica");
  Add("Installa / cambia build","Install / change build","Instalar / cambiar versión","Installer / changer de version","Build installieren / wechseln","Instalar / mudar versão");Add("Salva impostazioni","Save settings","Guardar ajustes","Enregistrer les réglages","Einstellungen speichern","Guardar definições");Add("Disinstalla / ripristina","Uninstall / restore","Desinstalar / restaurar","Désinstaller / restaurer","Deinstallieren / wiederherstellen","Desinstalar / restaurar");Add("Scegli modello DLSS 5…","Choose DLSS 5 model…","Elegir modelo DLSS 5…","Choisir le modèle DLSS 5…","DLSS-5-Modell wählen…","Escolher modelo DLSS 5…");
  Add("Posizione del passaggio · wilsjo2","Pass placement · wilsjo2","Posición del paso · wilsjo2","Position de la passe · wilsjo2","Position des Durchlaufs · wilsjo2","Posição da passagem · wilsjo2");Add("Passaggi · wilsjo2","Passes · wilsjo2","Pasadas · wilsjo2","Passes · wilsjo2","Durchläufe · wilsjo2","Passagens · wilsjo2");Add("Conserva / predefinita","Keep / default","Mantener / predeterminada","Conserver / défaut","Beibehalten / Standard","Manter / predefinida");Add("Dopo l’upscaling","After upscaling","Después del escalado","Après la mise à l’échelle","Nach Upscaling","Após o upscaling");Add("Prima dell’upscaling","Before upscaling","Antes del escalado","Avant la mise à l’échelle","Vor Upscaling","Antes do upscaling");Add("Conserva","Keep","Mantener","Conserver","Beibehalten","Manter");Add("1 · consigliato","1 · recommended","1 · recomendado","1 · recommandé","1 · empfohlen","1 · recomendado");Add("2 · sperimentale","2 · experimental","2 · experimental","2 · expérimental","2 · experimentell","2 · experimental");Add("3 · sperimentale","3 · experimental","3 · experimental","3 · expérimental","3 · experimentell","3 · experimental");Add("Intensità del risultato (%)","Effect strength (%)","Intensidad (%)","Intensité (%)","Effektstärke (%)","Intensidade (%)");Add("Tasto del menu OptiScaler","OptiScaler menu key","Tecla del menú OptiScaler","Touche du menu OptiScaler","OptiScaler-Menütaste","Tecla do menu OptiScaler");Add("Caricamento","Loading method","Método de carga","Méthode de chargement","Lademethode","Método de carregamento");
  Add("Installa ReShade selezionato","Install selected ReShade","Instalar ReShade seleccionado","Installer ReShade sélectionné","Ausgewähltes ReShade installieren","Instalar ReShade selecionado");Add("Catalogo mod RenoDX","RenoDX mod catalog","Catálogo de mods RenoDX","Catalogue des mods RenoDX","RenoDX-Modkatalog","Catálogo de mods RenoDX");Add("Installa mod RenoDX…","Install RenoDX mod…","Instalar mod RenoDX…","Installer le mod RenoDX…","RenoDX-Mod installieren…","Instalar mod RenoDX…");Add("Ripristina RenoDX","Restore RenoDX","Restaurar RenoDX","Restaurer RenoDX","RenoDX wiederherstellen","Restaurar RenoDX");Add("Ripristina ReShade","Restore ReShade","Restaurar ReShade","Restaurer ReShade","ReShade wiederherstellen","Restaurar ReShade");
  Add("Libreria","Library","Biblioteca","Bibliothèque","Bibliothek","Biblioteca");
  Add("Panoramica","Overview","Resumen","Vue d’ensemble","Übersicht","Visão geral");
  Add("Configura HDR","Set up HDR","Configurar HDR","Configurer HDR","HDR einrichten","Configurar HDR");
  Add("Configura DLSS 5","Set up DLSS 5","Configurar DLSS 5","Configurer DLSS 5","DLSS 5 einrichten","Configurar DLSS 5");
  Add("Cambia tasto","Change key","Cambiar tecla","Changer la touche","Taste ändern","Alterar tecla");
  Add("Tasto overlay HDR","HDR overlay key","Tecla del overlay HDR","Touche de l’overlay HDR","HDR-Overlay-Taste","Tecla do overlay HDR");
  Add("Seleziona un gioco","Select a game","Selecciona un juego","Sélectionnez un jeu","Spiel auswählen","Seleciona um jogo");
  Add("Non installato","Not installed","No instalado","Non installé","Nicht installiert","Não instalado");
  Add("Da verificare","Check required","Requiere revisión","Vérification requise","Prüfung erforderlich","Verificação necessária");
  Add("HDR del motore configurato","Engine HDR configured","HDR del motor configurado","HDR du moteur configuré","Engine-HDR konfiguriert","HDR do motor configurado");
  Add("OptiScaler installato","OptiScaler installed","OptiScaler instalado","OptiScaler installé","OptiScaler installiert","OptiScaler instalado");
  Add("ReShade installato","ReShade installed","ReShade instalado","ReShade installé","ReShade installiert","ReShade instalado");
  Add("RenoDX installato","RenoDX installed","RenoDX instalado","RenoDX installé","RenoDX installiert","RenoDX instalado");
  Add("Luci più definite. Ombre più leggibili.","Better highlights. Clearer dark scenes.","Luces más definidas. Sombras más claras.","Hautes lumières précises. Ombres lisibles.","Klarere Lichter und dunkle Szenen.","Luzes mais definidas. Sombras mais claras.");
  Add("Neural Rendering tramite OptiScaler.","Neural Rendering through OptiScaler.","Neural Rendering mediante OptiScaler.","Neural Rendering via OptiScaler.","Neural Rendering über OptiScaler.","Neural Rendering através do OptiScaler.");
  Add("HDR del motore o ReShade + RenoDX","Engine HDR or ReShade + RenoDX","HDR del motor o ReShade + RenoDX","HDR du moteur ou ReShade + RenoDX","Engine-HDR oder ReShade + RenoDX","HDR do motor ou ReShade + RenoDX");
  Add("ReShade + mod HDR compatibile","ReShade + compatible HDR mod","ReShade + mod HDR compatible","ReShade + mod HDR compatible","ReShade + kompatibler HDR-Mod","ReShade + mod HDR compatível");
  Add("Seleziona un gioco per vedere i metodi HDR disponibili.","Choose a game to see available HDR methods.","Selecciona un juego para ver los métodos HDR disponibles.","Choisissez un jeu pour voir les méthodes HDR disponibles.","Wähle ein Spiel, um verfügbare HDR-Methoden zu sehen.","Seleciona um jogo para ver os métodos HDR disponíveis.");
  Add("Seleziona un gioco per controllare i componenti.","Choose a game to check its components.","Selecciona un juego para comprobar sus componentes.","Choisissez un jeu pour vérifier ses composants.","Wähle ein Spiel, um seine Komponenten zu prüfen.","Seleciona um jogo para verificar os componentes.");
  Add("Configura OptiScaler per il gioco selezionato","OptiScaler setup for the selected game","Configura OptiScaler para el juego seleccionado","Configurer OptiScaler pour le jeu sélectionné","OptiScaler für das gewählte Spiel einrichten","Configura OptiScaler para o jogo selecionado");
  Add("Seleziona prima un eseguibile valido.","Select a valid game executable first.","Selecciona primero un ejecutable válido.","Sélectionnez d’abord un exécutable valide.","Wähle zuerst eine gültige Spiel-EXE.","Seleciona primeiro um executável válido.");
  Add("File rilevati · verifica in gioco","Detected files · verify activation in game","Archivos detectados · verifica en el juego","Fichiers détectés · vérifier dans le jeu","Dateien erkannt · im Spiel prüfen","Ficheiros detetados · verifica no jogo");
  Add("Scegli build e impostazioni immagine. La generazione fotogrammi esistente viene conservata.","Choose the build and picture settings. Existing frame generation is preserved by default.","Elige la versión y los ajustes de imagen. Se conserva la generación de fotogramas existente.","Choisissez la version et les réglages d’image. La génération d’images existante est conservée.","Wähle Build und Bildeinstellungen. Die bestehende Frame Generation bleibt erhalten.","Escolhe a versão e as definições de imagem. A geração de fotogramas existente é mantida.");
  Add("Come Windows","System","Como Windows","Comme Windows","Wie Windows","Como Windows");
Add("Guida","Help","Ayuda","Aide","Hilfe","Ajuda");
Add("Diagnostica","Diagnostics","Diagnóstico","Diagnostic","Diagnose","Diagnóstico");
Add("Backup","Backups","Copias","Sauvegardes","Sicherungen","Cópias");
Add("Indietro","Back","Atrás","Retour","Zurück","Voltar");
Add("Aggiungi gioco","Add game","Añadir juego","Ajouter un jeu","Spiel hinzufügen","Adicionar jogo");
Add("Copertina","Cover","Portada","Jaquette","Cover","Capa");
 }
 static void Add(string it,params string[] translations){words[it]=translations;}
 static int Language(){return Array.IndexOf(new[]{"en","es","fr","de","pt"},Core.Pref.Language);}
 public static string ToEnglish(string original){string mapped=EnglishUi.Translate(original);if(mapped!=original)return mapped;string[] found;return words.TryGetValue(original,out found)?found[0]:original;}
 static string Translate(string original){if(Core.Pref.Language=="en")return ToEnglish(original);string[] translations;int index=Language();if(words.TryGetValue(original,out translations))return index>=0?translations[index]:original;foreach(var pair in words)if(pair.Value[0]==original)return index>=0?pair.Value[index]:pair.Key;return original;}
 static bool Light(){if(Core.Pref.Theme=="light")return true;if(Core.Pref.Theme!="system")return false;try{using(var key=Registry.CurrentUser.OpenSubKey(@"Software\Microsoft\Windows\CurrentVersion\Themes\Personalize"))return key!=null&&Convert.ToInt32(key.GetValue("AppsUseLightTheme",0))!=0;}catch{return false;}}
 static void Property(DependencyObject node,DependencyProperty property,bool text){object current=node.GetValue(property);if(text&&!(current is string)||!text&&!(current is SolidColorBrush))return;var map=saved.GetOrCreateValue(node);Value value;if(!map.TryGetValue(property,out value)){value=new Value{Original=current};map[property]=value;}else if(!Object.Equals(current,value.Last))value.Original=current;object target=value.Original;if(text)target=Translate((string)target);else if(light){var brush=(SolidColorBrush)target;string hex=brush.Color.ToString(),mapped;if(colors.TryGetValue(hex,out mapped))target=new SolidColorBrush((Color)ColorConverter.ConvertFromString(mapped));else if(property==Control.ForegroundProperty||property==TextBlock.ForegroundProperty){var color=brush.Color;if(color.R>130&&color.G>130&&color.B>130)target=new SolidColorBrush(Color.FromRgb(44,57,72));else if(color.R>190&&color.G>130&&color.B<160)target=new SolidColorBrush(Color.FromRgb(137,83,5));}}value.Last=target;if(!Object.Equals(current,target))node.SetCurrentValue(property,target);}
 static void Walk(DependencyObject node,HashSet<DependencyObject> seen){if(node==null||!seen.Add(node))return;if(node is Control){Property(node,Control.BackgroundProperty,false);Property(node,Control.ForegroundProperty,false);Property(node,Control.BorderBrushProperty,false);}if(node is Border){Property(node,Border.BackgroundProperty,false);Property(node,Border.BorderBrushProperty,false);}if(node is Panel)Property(node,Panel.BackgroundProperty,false);if(node is Window)Property(node,Window.TitleProperty,true);if(node is TextBox&&((TextBox)node).IsReadOnly)Property(node,TextBox.TextProperty,true);if(node is TextBlock){Property(node,TextBlock.ForegroundProperty,false);Property(node,TextBlock.TextProperty,true);}if(node is ContentControl)Property(node,ContentControl.ContentProperty,true);if(node is HeaderedContentControl)Property(node,HeaderedContentControl.HeaderProperty,true);if(node is Visual)for(int i=0;i<VisualTreeHelper.GetChildrenCount(node);i++)Walk(VisualTreeHelper.GetChild(node,i),seen);foreach(object child in LogicalTreeHelper.GetChildren(node))if(child is DependencyObject)Walk((DependencyObject)child,seen);}
 public static void Refresh(){light=Light();if(Application.Current==null)return;foreach(Window w in Application.Current.Windows){if(w is SceneOverlay||w is LiveOverlay)continue;Walk(w,new HashSet<DependencyObject>());}}
 static bool refreshPending;
 static void QueueRefresh(){var app=Application.Current;if(app==null||app.Dispatcher.HasShutdownStarted||refreshPending)return;refreshPending=true;app.Dispatcher.BeginInvoke(System.Windows.Threading.DispatcherPriority.Loaded,new Action(()=>{refreshPending=false;Refresh();}));}
 public static void Start(){EventManager.RegisterClassHandler(typeof(Window),FrameworkElement.LoadedEvent,new RoutedEventHandler((s,e)=>QueueRefresh()));EventManager.RegisterClassHandler(typeof(Window),UIElement.PreviewMouseUpEvent,new System.Windows.Input.MouseButtonEventHandler((s,e)=>{if(Core.Pref.Language!="it"||Core.Pref.Theme!="dark")QueueRefresh();}));SystemEvents.UserPreferenceChanged+=(s,e)=>{if(Core.Pref.Theme=="system"&&Application.Current!=null)QueueRefresh();};}
}
public static class AppOptions {
 public static void Show(Window owner,Action shortcut){Create(owner,shortcut).ShowDialog();}
 public static Window Create(Window owner,Action shortcut){StackPanel body;var window=Dialogs.Create(owner,"Opzioni",out body);window.Width=760;body.Children.Add(Dialogs.Text("Lingua",17));var languages=new WrapPanel();body.Children.Add(languages);string[] names={"Italiano","English","Español","Français","Deutsch","Português"},codes={"it","en","es","fr","de","pt"};
  Action save=()=>{Core.SavePrefs();Appearance.Refresh();};
  for(int i=0;i<names.Length;i++){int n=i;var b=new Button{Content=names[i],Margin=new Thickness(0,0,8,8),Padding=new Thickness(12,9,12,9)};b.Click+=(s,e)=>{string old=Core.Pref.Language;try{Core.Pref.Language=codes[n];save();foreach(Button item in languages.Children)item.Style=window.TryFindResource(item==b?(object)"Primary":typeof(Button)) as Style;Appearance.Refresh();}catch(Exception ex){Core.Pref.Language=old;Dialogs.Notice(window,"Errore",ex.Message,null).ShowDialog();}};b.Style=window.TryFindResource(Core.Pref.Language==codes[n]?(object)"Primary":typeof(Button)) as Style;languages.Children.Add(b);}
  body.Children.Add(Dialogs.Text("Menu e comandi principali tradotti. Guide, descrizioni tecniche e log restano in italiano. / Main controls translated; technical help and logs remain in Italian.",12));body.Children.Add(Dialogs.Text("Aspetto",17));var themes=new WrapPanel();body.Children.Add(themes);string[] titles={"Chiaro","Scuro","Come Windows"},values={"light","dark","system"};for(int i=0;i<titles.Length;i++){int n=i;var b=new Button{Content=titles[i],Margin=new Thickness(0,0,8,16),Padding=new Thickness(16,9,16,9)};b.Style=window.TryFindResource(Core.Pref.Theme==values[n]?(object)"Primary":typeof(Button)) as Style;b.Click+=(s,e)=>{string old=Core.Pref.Theme;try{Core.Pref.Theme=values[n];save();foreach(Button item in themes.Children)item.Style=window.TryFindResource(item==b?(object)"Primary":typeof(Button)) as Style;Appearance.Refresh();}catch(Exception ex){Core.Pref.Theme=old;Dialogs.Notice(window,"Errore",ex.Message,null).ShowDialog();}};themes.Children.Add(b);}
  var key=new Button{Content="Configura tasto overlay…",Margin=new Thickness(0,0,0,12)};key.Click+=(s,e)=>shortcut();body.Children.Add(key);body.Children.Add(Dialogs.Text("Dati portable: "+Core.Data+"\nLe scelte vengono salvate automaticamente. Conserva questa cartella quando aggiorni l’app.",12));var close=new Button{Content="Chiudi"};close.Click+=(s,e)=>window.Close();body.Children.Add(close);return window;}
}
}
