using System;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net;
using System.Diagnostics;
using System.Collections.Generic;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
namespace HdrPilot {
public static class AsiLoader {
 public const string Repo="ThirteenAG/Ultimate-ASI-Loader",Marker="hdlss-asi-loader.json",Asset="Ultimate-ASI-Loader-NoPDB_x64.zip";
 public const string Help="ASI Loader downloads the latest stable Ultimate ASI Loader x64 from its author. Choose the DLL name required by your mod. Existing ASI loaders are detected and updated in place; duplicate loaders and occupied names stop installation. Installing the loader does not install ASI mods or guarantee game compatibility. Keep the data folder for restoration.";
 public static readonly string[] Names={"dinput8.dll","version.dll","winmm.dll","winhttp.dll","wininet.dll","dsound.dll","dxgi.dll","d3d9.dll","d3d10.dll","d3d11.dll","d3d12.dll","binkw64.dll","bink2w64.dll","xinput1_1.dll","xinput1_2.dll","xinput1_3.dll","xinput1_4.dll","xinput9_1_0.dll","xinputuap.dll"};
 static string L(string s){return Appearance.Localize(s);}
 public static bool IsLoader(string path){if(!File.Exists(path)||!DlssCore.Pe64(path))return false;var v=FileVersionInfo.GetVersionInfo(path);return (v.ProductName??"").Equals("Ultimate-ASI-Loader-x64",StringComparison.OrdinalIgnoreCase)&&(v.FileDescription??"").IndexOf("Ultimate ASI Loader",StringComparison.OrdinalIgnoreCase)>=0;}
 public static string[] Installed(Game g){string root=Path.GetDirectoryName(g.Exe);return Names.Where(n=>IsLoader(DlssCore.Safe(root,n))).ToArray();}
 public static FrameworkElement Panel(Window owner,Game g,Action<DlssPlan> review){var body=new StackPanel{Margin=new Thickness(0,8,0,12)};body.Children.Add(Dialogs.Text(L(Help),13));var names=new ComboBox{ItemsSource=Names,Margin=new Thickness(0,8,0,8)};body.Children.Add(names);var installed=Installed(g);names.SelectedItem=installed.Length==1?installed[0]:"dinput8.dll";names.IsEnabled=installed.Length==0;var info=Dialogs.Text("",13);body.Children.Add(info);var install=new Button{Content=L("Install / update ASI Loader"),HorizontalAlignment=HorizontalAlignment.Left};body.Children.Add(install);install.Click+=async(s,e)=>{if(ModCenter.Busy||RenoDxUi.IsBusy)return;ModCenter.Busy=true;body.IsEnabled=false;try{Core.Closed(g);string selected=Convert.ToString(names.SelectedItem);info.Text=L("Checking the latest ASI Loader release…");var plan=await Task.Run(()=>Prepare(g,Fetch(),selected));review(plan);}catch(Exception ex){info.Text=L(ex.Message);}finally{ModCenter.Busy=false;body.IsEnabled=true;}};return body;}
 public static void Show(Window owner,Game g,Action<DlssPlan> review){StackPanel body;var d=Dialogs.Create(owner,"ASI Loader",out body);body.Children.Add(Panel(owner,g,review));d.ShowDialog();}
 public static string Extract(string zip){string dir=Path.Combine(Core.Data,"asi-packages",Guid.NewGuid().ToString("N"));Directory.CreateDirectory(dir);using(var input=File.OpenRead(zip))using(var z=new ZipArchive(input,ZipArchiveMode.Read)){var entries=z.Entries.Where(e=>e.FullName=="dinput8.dll").ToArray();if(entries.Length!=1||entries[0].Length<4096||entries[0].Length>16000000)throw new Exception(L("ASI Loader: unsupported package."));string file=Path.Combine(dir,"dinput8.dll");using(var src=entries[0].Open())using(var dst=File.Create(file))src.CopyTo(dst);if(!IsLoader(file))throw new Exception(L("ASI Loader: invalid x64 library."));return file;}}
 public static string Fetch(){ServicePointManager.SecurityProtocol|=SecurityProtocolType.Tls12;using(var web=new DlssCore.DownloadClient()){web.Headers[HttpRequestHeader.UserAgent]="HDLSS";web.Headers[HttpRequestHeader.CacheControl]="no-cache";var r=Core.Json.Deserialize<Dictionary<string,object>>(web.DownloadString("https://api.github.com/repos/"+Repo+"/releases/latest"));if(Convert.ToBoolean(r["draft"])||Convert.ToBoolean(r["prerelease"]))throw new Exception(L("ASI Loader: no stable release available."));var matches=((System.Collections.IEnumerable)r["assets"]).Cast<Dictionary<string,object>>().Where(a=>Convert.ToString(a["name"])==Asset).ToArray();if(matches.Length!=1)throw new Exception(L("ASI Loader: unsupported package."));var a1=matches[0];string tag=Convert.ToString(r["tag_name"]),url=Convert.ToString(a1["browser_download_url"]),digest=a1.ContainsKey("digest")?Convert.ToString(a1["digest"]):"";long size=Convert.ToInt64(a1["size"]);if(!Regex.IsMatch(tag,@"^v\d+\.\d+\.\d+$")||url!="https://github.com/"+Repo+"/releases/download/"+tag+"/"+Asset||!Regex.IsMatch(digest,@"^sha256:[a-fA-F0-9]{64}$")||size<4096||size>20000000)throw new Exception(L("ASI Loader: invalid release origin or checksum."));string zip=Path.Combine(Core.Data,"asi-"+Guid.NewGuid().ToString("N")+".zip");try{web.DownloadFile(url,zip);if(new FileInfo(zip).Length!=size||!DlssCore.Hash(zip).Equals(digest.Substring(7),StringComparison.OrdinalIgnoreCase))throw new Exception(L("ASI Loader: download verification failed."));return Extract(zip);}finally{if(File.Exists(zip))File.Delete(zip);}}}
 public static DlssPlan Prepare(Game g,string source,string selected){Core.Closed(g);if(g.ProtectedInstall)throw new Exception(g.Evidence);if(!DlssCore.Pe64(g.Exe))throw new Exception(L("ASI Loader requires a 64-bit game executable."));if(!IsLoader(source))throw new Exception(L("ASI Loader: invalid x64 library."));string root=Path.GetDirectoryName(Path.GetFullPath(g.Exe));var existing=Installed(g);if(existing.Length>1)throw new Exception(L("Multiple ASI loaders detected. Resolve the duplicate before updating:")+" "+String.Join(", ",existing));string name=existing.Length==1?existing[0]:selected;if(!Names.Contains(name))throw new Exception(L("ASI Loader: unsupported DLL name."));string dest=DlssCore.Safe(root,name),marker=DlssCore.Safe(root,Marker);if(File.Exists(dest)&&!IsLoader(dest))throw new Exception(L("The selected DLL belongs to another component:")+" "+name);if(File.Exists(dest)&&DlssCore.Hash(dest)==DlssCore.Hash(source))throw new Exception(L("ASI Loader is already up to date."));var m=File.Exists(marker)?DlssCore.ReadManifest(root,Marker):new DlssManifest{Game=g.Id,Folder=root,BackupRoot="asi-backups/"+Guid.NewGuid().ToString("N"),PreviousOwner="Before ASI Loader"};if(m.Game!=g.Id||m.Files.Any(f=>f.Name!=name))throw new Exception(L("ASI Loader installation record does not match this game."));foreach(var f in m.Files){if(!File.Exists(dest)||DlssCore.Hash(dest)!=f.After||f.Before!=null&&(!File.Exists(DlssCore.Safe(Core.Data,f.Backup))||DlssCore.Hash(DlssCore.Safe(Core.Data,f.Backup))!=f.Before))throw new Exception(L("ASI Loader file or backup changed. Restore stopped."));}m.Build=Repo;m.Release=FileVersionInfo.GetVersionInfo(source).FileVersion;var p=new DlssPlan{Folder=root,MarkerName=Marker,MarkerExpected=File.Exists(marker)?DlssCore.Hash(marker):null,Manifest=m,Summary=g.Name+"\nASI Loader · "+m.Release+" · "+name+"\n"+L(Help)};p.Changes.Add(new DlssChange{Name=name,Source=source,SourceHash=DlssCore.Hash(source),Expected=File.Exists(dest)?DlssCore.Hash(dest):null});return p;}
 public static DlssPlan Restore(Game g){Core.Closed(g);if(g.ProtectedInstall)throw new Exception(g.Evidence);string root=Path.GetDirectoryName(Path.GetFullPath(g.Exe));var m=DlssCore.ReadManifest(root,Marker);if(m.Game!=g.Id||m.Files.Count!=1||!Names.Contains(m.Files[0].Name))throw new Exception(L("ASI Loader installation record does not match this game."));var f=m.Files[0];string path=DlssCore.Safe(root,f.Name),backup=f.Before==null?null:DlssCore.Safe(Core.Data,f.Backup);if(!File.Exists(path)||DlssCore.Hash(path)!=f.After||backup!=null&&(!File.Exists(backup)||DlssCore.Hash(backup)!=f.Before))throw new Exception(L("ASI Loader file or backup changed. Restore stopped."));var p=new DlssPlan{Folder=root,Uninstall=true,Summary=L("Restore ASI Loader. ASI mods and their settings are preserved.")};p.Changes.Add(new DlssChange{Name=f.Name,Expected=f.After,Source=backup,SourceHash=f.Before,Delete=backup==null,RestoreAttributes=f.Attributes});p.Changes.Add(new DlssChange{Name=Marker,Delete=true,Expected=DlssCore.Hash(DlssCore.Safe(root,Marker))});return p;}
}
}
