using System;
using System.IO;
using System.Runtime.InteropServices;
using System.Text;
namespace HdrPilot {
public struct SceneStats {public double Peak,Mean,Min;public long Pixels;public DateTime Time;public double AnalysisMs;}
// Desktop Duplication preserves FP16 HDR. This class never stores or transmits images.
public sealed class MaskedFrameException:Exception { public MaskedFrameException():base("Windows oscura parte del desktop: misura sospesa. Non riguarda i file INI."){} }
public sealed class HdrCapture:IDisposable {
 [StructLayout(LayoutKind.Sequential)]public struct Rect {public int Left,Top,Right,Bottom;}
 [StructLayout(LayoutKind.Sequential)]struct Point {public int X,Y;}
 [StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)]struct OutputDesc { [MarshalAs(UnmanagedType.ByValTStr,SizeConst=32)]public string Name;public Rect Bounds;public int Attached,Rotation;public IntPtr Monitor;}
 [StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)]struct OutputDesc1 { [MarshalAs(UnmanagedType.ByValTStr,SizeConst=32)]public string Name;public Rect Bounds;public int Attached,Rotation;public IntPtr Monitor;public uint Bits,ColorSpace;public float Rx,Ry,Gx,Gy,Bx,By,Wx,Wy,Min,Max,Full;}
 [StructLayout(LayoutKind.Sequential)]struct FrameInfo {public long Present,Mouse;public uint Frames;public int Coalesced,Protected;public Point Pointer;public int Visible;public uint Metadata,Shape;}
 [StructLayout(LayoutKind.Sequential)]struct TextureDesc {public uint Width,Height,Mips,Array,Format,SampleCount,SampleQuality,Usage,Bind,Cpu,Misc;}
 [StructLayout(LayoutKind.Sequential)]struct Mapped {public IntPtr Data;public uint RowPitch,DepthPitch;}
 [UnmanagedFunctionPointer(CallingConvention.StdCall)]delegate int EnumItem(IntPtr self,uint index,out IntPtr item);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)]delegate int GetOutput(IntPtr self,out OutputDesc desc);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)]delegate int GetOutput1(IntPtr self,out OutputDesc1 desc);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)]delegate int Duplicate(IntPtr self,IntPtr device,uint flags,uint count,[In]uint[] formats,out IntPtr dupl);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)]delegate int DuplicateOld(IntPtr self,IntPtr device,out IntPtr dupl);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)]delegate int Acquire(IntPtr self,uint ms,out FrameInfo info,out IntPtr resource);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)]delegate int ReleaseFrame(IntPtr self);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)]delegate void GetTexture(IntPtr self,out TextureDesc desc);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)]delegate int CreateTexture(IntPtr self,ref TextureDesc desc,IntPtr initial,out IntPtr texture);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)]delegate void Copy(IntPtr self,IntPtr destination,IntPtr source);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)]delegate int Map(IntPtr self,IntPtr resource,uint sub,uint type,uint flags,out Mapped data);
 [UnmanagedFunctionPointer(CallingConvention.StdCall)]delegate void Unmap(IntPtr self,IntPtr resource,uint sub);
 [DllImport("dxgi.dll")]static extern int CreateDXGIFactory1(ref Guid iid,out IntPtr factory);
 [DllImport("d3d11.dll")]static extern int D3D11CreateDevice(IntPtr adapter,uint type,IntPtr software,uint flags,IntPtr levels,uint count,uint sdk,out IntPtr device,out uint level,out IntPtr context);
 [DllImport("user32.dll")]static extern IntPtr GetForegroundWindow();
 [DllImport("user32.dll")]static extern uint GetWindowThreadProcessId(IntPtr window,out uint pid);
 [DllImport("user32.dll")]static extern bool GetClientRect(IntPtr window,out Rect rect);
 [DllImport("user32.dll")]static extern bool ClientToScreen(IntPtr window,ref Point point);
 [DllImport("kernel32.dll")]static extern IntPtr OpenProcess(uint access,bool inherit,uint pid);
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode)]static extern bool QueryFullProcessImageName(IntPtr process,uint flags,StringBuilder path,ref uint length);
 [DllImport("kernel32.dll")]static extern bool CloseHandle(IntPtr handle);
 [DllImport("user32.dll")]static extern bool IsIconic(IntPtr window);
 static T Fn<T>(IntPtr p,int slot) where T:class{return Marshal.GetDelegateForFunctionPointer(Marshal.ReadIntPtr(Marshal.ReadIntPtr(p),slot*IntPtr.Size),typeof(T)) as T;}
 static IntPtr Query(IntPtr p,string iid){Guid g=new Guid(iid);IntPtr result;Check(Marshal.QueryInterface(p,ref g,out result));return result;}
 static void Check(int hr){if(hr<0)Marshal.ThrowExceptionForHR(hr);}
 static void Drop(ref IntPtr p){if(p!=IntPtr.Zero){Marshal.Release(p);p=IntPtr.Zero;}}
 IntPtr device,context,duplicate,staging;uint width,height;public Rect Bounds;public string DeviceName;public uint ColorSpace;
 public HdrCapture(string name){IntPtr factory=IntPtr.Zero,adapter=IntPtr.Zero,output=IntPtr.Zero,output5=IntPtr.Zero,output6=IntPtr.Zero;try{Guid iid=new Guid("770aae78-f26f-4dba-a829-253c83d1b387");Check(CreateDXGIFactory1(ref iid,out factory));bool found=false;for(uint a=0;a<32&&!found;a++){if(Fn<EnumItem>(factory,12)(factory,a,out adapter)<0)break;for(uint o=0;o<16;o++){if(Fn<EnumItem>(adapter,7)(adapter,o,out output)<0)break;OutputDesc desc;Check(Fn<GetOutput>(output,7)(output,out desc));if(desc.Attached!=0&&String.Equals(desc.Name,name,StringComparison.OrdinalIgnoreCase)){if(desc.Rotation!=1)throw new Exception("Analisi non disponibile con display ruotato.");Bounds=desc.Bounds;DeviceName=desc.Name;output6=Query(output,"068346e8-aaec-4b84-add7-137f513f77a1");OutputDesc1 hdr;Check(Fn<GetOutput1>(output6,27)(output6,out hdr));ColorSpace=hdr.ColorSpace;if(ColorSpace!=12&&ColorSpace!=1)throw new Exception("HDR non attivo sul monitor selezionato. Attivalo in Windows.");uint level;int createHr=D3D11CreateDevice(adapter,0,IntPtr.Zero,0x20,IntPtr.Zero,0,7,out device,out level,out context);if(createHr<0)throw new Exception("Creazione dispositivo HDR: 0x"+createHr.ToString("X8"));output5=Query(output,"80a07424-ab52-42eb-833c-0c42fd282d98");OverlayDiagnostics.Log("Avvio cattura: "+name+"; color space "+ColorSpace);int duplicateHr=Fn<Duplicate>(output5,26)(output5,device,0,2,new uint[]{10,87},out duplicate);if(duplicateHr<0){OverlayDiagnostics.Log("DuplicateOutput1: 0x"+duplicateHr.ToString("X8"));Drop(ref duplicate);duplicateHr=Fn<DuplicateOld>(output5,22)(output5,device,out duplicate);}if(duplicateHr<0)OverlayDiagnostics.Log("DuplicateOutput fallback: 0x"+duplicateHr.ToString("X8"));if(duplicateHr<0)throw new Exception(duplicateHr==unchecked((int)0x80070005)?"Windows nega la cattura a questo processo. Nessuna misura disponibile.":"Cattura HDR non supportata in questa sessione (0x"+duplicateHr.ToString("X8")+").");found=true;break;}Drop(ref output);}Drop(ref output);Drop(ref adapter);}if(!found)throw new Exception("Monitor selezionato non disponibile.");}catch{Dispose();throw;}finally{Drop(ref output6);Drop(ref output5);Drop(ref output);Drop(ref adapter);Drop(ref factory);}}
 public static bool GameArea(Game game,out Rect area){string reason;return GameArea(game,out area,out reason);}
 public static bool GameArea(Game game,out Rect area,out string reason){reason="In pausa · porta il gioco selezionato in primo piano";area=new Rect();IntPtr window=GetForegroundWindow();if(window==IntPtr.Zero||IsIconic(window)||String.IsNullOrEmpty(game.Exe))return false;uint pid;GetWindowThreadProcessId(window,out pid);IntPtr process=OpenProcess(0x1000,false,pid);if(process==IntPtr.Zero){reason="Impossibile identificare il gioco: accesso al processo negato.";return false;}try{var text=new StringBuilder(32768);uint len=(uint)text.Capacity;if(!QueryFullProcessImageName(process,0,text,ref len)){reason="Windows non consente di identificare il processo in primo piano.";return false;}if(!String.Equals(Path.GetFullPath(text.ToString()),Path.GetFullPath(game.Exe),StringComparison.OrdinalIgnoreCase))return false;}finally{CloseHandle(process);}Rect client;if(!GetClientRect(window,out client))return false;Point pos=new Point();if(!ClientToScreen(window,ref pos))return false;area=new Rect{Left=pos.X,Top=pos.Y,Right=pos.X+client.Right,Bottom=pos.Y+client.Bottom};return client.Right>0&&client.Bottom>0;}
 public SceneStats? Capture(Rect area,Rect? overlay=null){if(area.Left<Bounds.Left||area.Top<Bounds.Top||area.Right>Bounds.Right||area.Bottom>Bounds.Bottom)throw new Exception("Sposta tutto il gioco sul monitor selezionato.");FrameInfo info;IntPtr resource=IntPtr.Zero,texture=IntPtr.Zero;int hr=Fn<Acquire>(duplicate,8)(duplicate,60,out info,out resource);if(unchecked((uint)hr)==0x887A0027)return null;Check(hr);try{if(info.Protected!=0)throw new MaskedFrameException();if(info.Present==0)return null;texture=Query(resource,"6f15aaf2-d208-4e89-9ab4-489535d34f9c");TextureDesc desc;Fn<GetTexture>(texture,10)(texture,out desc);if(desc.Format!=10)throw new Exception("La cattura non fornisce pixel HDR FP16. Nessun valore in nit stimato da SDR.");if(desc.Width!=Bounds.Right-Bounds.Left||desc.Height!=Bounds.Bottom-Bounds.Top)throw new Exception("Dimensioni cambiate: riapri l’overlay.");if(staging==IntPtr.Zero||width!=desc.Width||height!=desc.Height){Drop(ref staging);width=desc.Width;height=desc.Height;desc.Usage=3;desc.Bind=0;desc.Cpu=0x20000;desc.Misc=0;Check(Fn<CreateTexture>(device,5)(device,ref desc,IntPtr.Zero,out staging));}Fn<Copy>(context,47)(context,staging,texture);Mapped data;Check(Fn<Map>(context,14)(context,staging,0,1,0,out data));try{Rect? omit=null;if(overlay.HasValue){var r=overlay.Value;r.Left-=Bounds.Left;r.Right-=Bounds.Left;r.Top-=Bounds.Top;r.Bottom-=Bounds.Top;omit=r;}return Analyze(data.Data,(int)data.RowPitch,area.Left-Bounds.Left,area.Top-Bounds.Top,area.Right-area.Left,area.Bottom-area.Top,omit);}finally{Fn<Unmap>(context,15)(context,staging,0);}}finally{Drop(ref texture);Drop(ref resource);Fn<ReleaseFrame>(duplicate,14)(duplicate);}}
 static readonly float[] Halves=HalfTable();
 static float[] HalfTable(){var t=new float[65536];for(int i=0;i<t.Length;i++){int exp=(i>>10)&31,m=i&1023;double sign=(i&32768)==0?1:-1;t[i]=(float)(exp==31?(m==0?sign*Double.PositiveInfinity:Double.NaN):exp==0?sign*m*Math.Pow(2,-24):sign*(1+m/1024.0)*Math.Pow(2,exp-15));}return t;}
 public static unsafe SceneStats Analyze(IntPtr data,int pitch,int left,int top,int w,int h,Rect? omit=null){if(data==IntPtr.Zero||left<0||top<0||w<=0||h<=0||pitch<(left+w)*8)throw new ArgumentException("Area cattura non valida");var watch=System.Diagnostics.Stopwatch.StartNew();double sum=0,min=Double.PositiveInfinity,max=0;long count=0;for(int y=top;y<top+h;y++){ushort* row=(ushort*)((byte*)data+y*(long)pitch)+left*4;for(int x=0;x<w;x++,row+=4){if(omit.HasValue&&x+left>=omit.Value.Left&&x+left<omit.Value.Right&&y>=omit.Value.Top&&y<omit.Value.Bottom)continue;double lum=80.0*(0.2126*Halves[row[0]]+0.7152*Halves[row[1]]+0.0722*Halves[row[2]]);if(Double.IsNaN(lum)||Double.IsInfinity(lum))throw new Exception("Pixel HDR non valido: misura scartata.");lum=Math.Max(0,lum);sum+=lum;if(lum>max)max=lum;if(lum<min)min=lum;count++;}}if(count==0)throw new Exception("Area di gioco coperta dall’overlay: nessun pixel misurabile.");return new SceneStats{Peak=max,Min=min,Mean=sum/count,Pixels=count,Time=DateTime.UtcNow,AnalysisMs=watch.Elapsed.TotalMilliseconds};}
 public void Dispose(){Drop(ref staging);Drop(ref duplicate);Drop(ref context);Drop(ref device);}
}
}
