using System;
using System.IO;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Reflection;
namespace HdrPilot {
public static class ComponentTests {
 public static void ModelTest(string manifest,string catalog,string output){Directory.CreateDirectory(output);var entries=NrModels.Parse(File.ReadAllText(manifest));Check(entries.Count==4&&entries.All(x=>x.Tag.StartsWith("dlssnr-")),"actual NR family filtering");Reject(()=>NrModels.Compatible(entries.First(x=>!x.Community),40),"original NR on RTX40");NrModels.Compatible(entries.First(x=>!x.Community),50);NrModels.Compatible(entries.First(x=>x.Community),40);foreach(string file in DlssLibraries.Names)Check(DllCatalog.Parse(File.ReadAllText(catalog),file).Count==10,"ten historical component versions");Core.Data=Path.Combine(output,"data");Directory.CreateDirectory(Core.Data);var g=new Game{Id="fixture",Name="NR fixture",Root=Path.Combine(output,Guid.NewGuid().ToString("N"))};Directory.CreateDirectory(g.Root);g.Exe=Path.Combine(g.Root,"game.exe");Pe(g.Exe,false);string source=Path.Combine(output,"nr-fixture.dll");Pe(source,false);DlssCore.Apply(g,NrModels.Prepare(g,source,entries[0]));Check(File.Exists(Path.Combine(g.Root,"nvngx_dlssnr.dll")),"NR install");DlssCore.Apply(g,NrModels.Restore(g));Check(!File.Exists(Path.Combine(g.Root,"nvngx_dlssnr.dll")),"NR removal");File.WriteAllText(Path.Combine(output,"model.txt"),"PASS: four actual NR repository variants filtered; RTX40 original rejection; GPU variant matching; ten historical SR/RR/FG versions; isolated model installation and restoration fixtures. Downloads of live NR models not exercised.");}
 public static void Catalog(string manifest,string archive,string output){Directory.CreateDirectory(output);string json=File.ReadAllText(manifest);foreach(string name in DlssLibraries.Names){var versions=DllCatalog.Parse(json,name);Check(versions.Count==10&&versions.Select(x=>x.Version).Distinct().Count()==10,"ten distinct component versions");Check(versions.All(x=>new Uri(x.Url).Host=="dlss-swapper-downloads.beeradmoore.com"),"catalog source");}var item=DllCatalog.Parse(json,"nvngx_dlssg.dll")[0];DllCatalog.Extract(item,archive,Path.Combine(output,item.File));item.ZipMd5=new string('0',32);Reject(()=>DllCatalog.Extract(item,archive,Path.Combine(output,"invalid.dll")),"tampered archive accepted");File.WriteAllText(Path.Combine(output,"catalog.txt"),"PASS: actual catalog contains ten distinct signed non-development versions per component; newest FG ZIP extracted and hash, NVIDIA signature, component and exact version verified; altered digest rejected.");}
 public static void Individual(string sr,string fg,string output){Directory.CreateDirectory(output);Core.Data=Path.Combine(output,"data");Directory.CreateDirectory(Core.Data);var g=new Game{Id="fixture",Name="Individual restore",Root=Path.Combine(output,Guid.NewGuid().ToString("N"))};Directory.CreateDirectory(g.Root);g.Exe=Path.Combine(g.Root,"game.exe");Pe(g.Exe,false);var a=new DlssLibrary{File="nvngx_dlss.dll",Relative="nvngx_dlss.dll",Path=Path.Combine(g.Root,"nvngx_dlss.dll"),Version="fixture baseline"};var b=new DlssLibrary{File="nvngx_dlssg.dll",Relative="nvngx_dlssg.dll",Path=Path.Combine(g.Root,"nvngx_dlssg.dll"),Version="fixture baseline"};Pe(a.Path,false);Pe(b.Path,false);string before=DlssCore.Hash(a.Path);DlssCore.Apply(g,DlssLibraries.Prepare(g,a,sr));DlssCore.Apply(g,DlssLibraries.Prepare(g,b,fg));DlssCore.Apply(g,DlssLibraries.Restore(g,a));Check(DlssCore.Hash(a.Path)==before&&DlssCore.Hash(b.Path)==DlssCore.Hash(fg),"individual restoration changed other component");Check(DlssCore.ReadManifest(g.Root,DlssLibraries.Marker).Files.Count==1,"remaining component manifest lost");DlssCore.Apply(g,DlssLibraries.Restore(g,b));Check(!File.Exists(Path.Combine(g.Root,DlssLibraries.Marker))&&DlssCore.Hash(b.Path)==before,"last component restore");File.WriteAllText(Path.Combine(output,"individual.txt"),"PASS: SR and FG independently installed from real NVIDIA signed DLLs; SR restored without changing FG; final FG restoration removed only its tracking record. No real game changes.");}
 static void ClickLabel(System.Windows.DependencyObject node,string label){var button=node as Button;if(button!=null&&Convert.ToString(button.Content)==label){button.RaiseEvent(new RoutedEventArgs(Button.ClickEvent));return;}foreach(var child in LogicalTreeHelper.GetChildren(node).OfType<System.Windows.DependencyObject>())ClickLabel(child,label);}
 static void Render(Window w,string path){w.UpdateLayout();var bitmap=new System.Windows.Media.Imaging.RenderTargetBitmap((int)w.ActualWidth,(int)w.ActualHeight,96,96,System.Windows.Media.PixelFormats.Pbgra32);bitmap.Render(w);var png=new System.Windows.Media.Imaging.PngBitmapEncoder();png.Frames.Add(System.Windows.Media.Imaging.BitmapFrame.Create(bitmap));using(var f=File.Create(path))png.Save(f);}
 static void Check(bool ok,string why){if(!ok)throw new Exception(why);}
 static void Reject(Action action,string why){bool rejected=false;try{action();}catch{rejected=true;}Check(rejected,why);}
 static void Pe(string file,bool opti){byte[] b=new byte[256];b[0]=77;b[1]=90;b[60]=64;b[64]=80;b[65]=69;b[68]=100;b[69]=134;if(opti)System.Text.Encoding.ASCII.GetBytes("OptiScaler.ini OptiScaler").CopyTo(b,90);File.WriteAllBytes(file,b);}
 public static void Run(string stable,string nightly,string output){Directory.CreateDirectory(output);string root=Path.Combine(output,Guid.NewGuid().ToString("N"));Directory.CreateDirectory(root);Core.Data=Path.Combine(root,"data");Directory.CreateDirectory(Core.Data);
  string a=RenoDx.Extract(stable,Path.Combine(root,"stable")),b=RenoDx.Extract(nightly,Path.Combine(root,"nightly"));Check(RenoDx.IsReShade(a)&&RenoDx.IsReShade(b),"real stable and nightly extraction");
  var g=new Game{Id="fixture",Name="Fixture",Root=Path.Combine(root,"game"),Exe=Path.Combine(root,"game","game.exe")};Directory.CreateDirectory(g.Root);Pe(g.Exe,false);
  var p=RenoDx.InstallReShade(g,a,"stable fixture");Check(p.Changes.Single().Name=="dxgi.dll","standalone loader");DlssCore.Apply(g,p);Check(RenoDx.IsReShade(Path.Combine(g.Root,"dxgi.dll")),"standalone install");File.WriteAllText(Path.Combine(g.Root,"ReShade.ini"),"[GENERAL]\nPresetPath=keep.ini\n");DlssCore.Apply(g,RenoDx.MenuKey(g,"0x22"));Check(Core.Get(File.ReadAllText(Path.Combine(g.Root,"ReShade.ini")),"INPUT","KeyOverlay")=="34,0,0,0","ReShade standalone PgDn mapping");Check(File.ReadAllText(Path.Combine(g.Root,"ReShade.ini")).Contains("PresetPath=keep.ini"),"ReShade preset preservation");DlssCore.Apply(g,RenoDx.Restore(g,RenoDx.KeyMarker));Check(!File.ReadAllText(Path.Combine(g.Root,"ReShade.ini")).Contains("KeyOverlay"),"ReShade key restoration");DlssCore.Apply(g,RenoDx.InstallReShade(g,b,"nightly fixture"));DlssCore.Apply(g,RenoDx.Restore(g,RenoDx.Marker));Check(!File.Exists(Path.Combine(g.Root,"dxgi.dll")),"baseline remove after nightly switch");
  File.WriteAllText(Path.Combine(g.Root,"dxgi.dll"),"unknown mod");Reject(()=>RenoDx.InstallReShade(g,a,"test"),"unknown loader overwritten");File.Delete(Path.Combine(g.Root,"dxgi.dll"));
  Pe(Path.Combine(g.Root,"dxgi.dll"),true);File.WriteAllText(Path.Combine(g.Root,"version.dll"),"UE4SS preserve");string original="[FrameGen]\nEnabled=true\n[HDR]\nEnabled=true\n";File.WriteAllText(Path.Combine(g.Root,"OptiScaler.ini"),original);File.SetAttributes(Path.Combine(g.Root,"OptiScaler.ini"),FileAttributes.ReadOnly);
  p=RenoDx.InstallReShade(g,a,"test");Check(p.Changes.Any(c=>c.Name=="ReShade64.dll")&&!p.Changes.Any(c=>c.Name=="dxgi.dll"),"Opti chain");DlssCore.Apply(g,p);Check(Core.Get(File.ReadAllText(Path.Combine(g.Root,"OptiScaler.ini")),"Plugins","LoadReshade")=="true","chain enabled");
  string addon=Path.Combine(root,"renodx-fixture.addon64");Pe(addon,false);DlssCore.Apply(g,RenoDx.InstallAddon(g,addon));Check(File.Exists(Path.Combine(g.Root,"renodx-fixture.addon64")),"addon applied");DlssCore.Apply(g,RenoDx.Restore(g,RenoDx.AddonMarker));Check(!File.Exists(Path.Combine(g.Root,"renodx-fixture.addon64")),"addon removal");
  Reject(()=>DlssCore.PrepareUninstall(g),"dependent ReShade allowed Opti removal");
  File.Copy(a,Path.Combine(g.Root,"d3d11.dll"));Reject(()=>RenoDx.InstallReShade(g,b,"test"),"duplicate ReShade accepted");File.Delete(Path.Combine(g.Root,"d3d11.dll"));
  DlssCore.Apply(g,RenoDx.Restore(g,RenoDx.Marker));Check(File.ReadAllText(Path.Combine(g.Root,"OptiScaler.ini"))==original,"Opti ini exact restore");Check((File.GetAttributes(Path.Combine(g.Root,"OptiScaler.ini"))&FileAttributes.ReadOnly)!=0,"readonly lost");Check(File.ReadAllText(Path.Combine(g.Root,"version.dll"))=="UE4SS preserve"&&DlssCore.IsOpti(Path.Combine(g.Root,"dxgi.dll")),"other loaders changed");
  p=RenoDx.InstallReShade(g,a,"test");File.WriteAllText(Path.Combine(g.Root,"ReShade64.dll"),"third party changed");Reject(()=>DlssCore.Apply(g,p),"stale plan accepted");
  Check(DlssLibraries.ParseTags("[{\"name\":\"v310.9.1\"},{\"name\":\"v3.7.20\"},{\"name\":\"v310.7.0\"},{\"name\":\"../bad\"}]").SequenceEqual(new[]{"v310.9.1","v310.7.0","v3.7.20"}),"version ordering/filter");
  new Application();Window owner;using(var s=Assembly.GetExecutingAssembly().GetManifestResourceStream("Main.xaml"))owner=(Window)System.Windows.Markup.XamlReader.Load(s);HdrChoices.Apply(owner);owner.Show();File.Delete(Path.Combine(g.Root,"ReShade64.dll"));
  var ui=new DlssUi();ui.Create(owner,g,true);Check(ui.EmbeddedContent!=null,"embedded section missing");var host=(Grid)owner.FindName("DlssSection");host.Visibility=Visibility.Visible;host.Children.Add(ui.EmbeddedContent);owner.UpdateLayout();
  var field=typeof(DlssUi).GetField("scale",BindingFlags.NonPublic|BindingFlags.Instance);var slider=(Slider)field.GetValue(ui);slider.Value=63;var options=(DlssOptions)typeof(DlssUi).GetMethod("Options",BindingFlags.NonPublic|BindingFlags.Instance).Invoke(ui,null);Check(options.Scale==63,"slider value not applied");Check(owner.FindName("HdrMethod") is ComboBox&&owner.FindName("HdrSection") is Button,"HDR navigation missing");
  var pilot=new Pilot();var flags=BindingFlags.NonPublic|BindingFlags.Instance;typeof(Pilot).GetField("window",flags).SetValue(pilot,owner);typeof(Pilot).GetField("current",flags).SetValue(pilot,g);typeof(Pilot).GetField("games",flags).SetValue(pilot,new System.Collections.Generic.List<Game>{g});typeof(Pilot).GetMethod("SwitchSection",flags).Invoke(pilot,new object[]{true});Check(((Grid)owner.FindName("LibrarySection")).Visibility==Visibility.Visible&&host.Visibility==Visibility.Visible,"DLSS 5 navigation failed");((ContentControl)owner.FindName("ActivityLogHost")).Content=ActivityLog.Panel();Render(owner,Path.Combine(output,"sezione-dlss.png"));var currentPanel=(DlssUi)typeof(Pilot).GetField("dlssPanel",flags).GetValue(pilot);var controls=(StackPanel)typeof(DlssUi).GetField("controls",flags).GetValue(currentPanel);foreach(var child in controls.Children)if(child is Expander)((Expander)child).IsExpanded=true;owner.UpdateLayout();var parent=System.Windows.Media.VisualTreeHelper.GetParent(controls);while(parent!=null&&!(parent is ScrollViewer))parent=System.Windows.Media.VisualTreeHelper.GetParent(parent);if(parent is ScrollViewer)((ScrollViewer)parent).ScrollToBottom();Render(owner,Path.Combine(output,"advanced-buttons.png"));Check(Grid.GetColumn(host)==1&&Grid.GetRow(host)==2,"DLSS 5 must not replace the shared library");typeof(Pilot).GetMethod("SwitchSection",flags).Invoke(pilot,new object[]{false});Check(((Grid)owner.FindName("LibrarySection")).Visibility==Visibility.Visible&&host.Visibility==Visibility.Collapsed,"HDR navigation failed");
  ((ComboBox)owner.FindName("HdrMethod")).SelectedIndex=1;typeof(Pilot).GetMethod("HdrMode",flags).Invoke(pilot,null);Check(((StackPanel)owner.FindName("UeHdrControls")).Visibility==Visibility.Collapsed&&((Button)owner.FindName("Apply")).Visibility==Visibility.Collapsed,"ReShade mode exposes UE apply");Check(!((ComboBoxItem)((ComboBox)owner.FindName("HdrMethod")).Items[0]).IsEnabled,"INI HDR must be disabled for unsupported engine");g.Confirmed=true;typeof(Pilot).GetMethod("HdrMode",flags).Invoke(pilot,null);Check(((ComboBoxItem)((ComboBox)owner.FindName("HdrMethod")).Items[0]).IsEnabled,"UE5 HDR option should be enabled");g.Confirmed=false;typeof(Pilot).GetMethod("HdrMode",flags).Invoke(pilot,null);
  Appearance.Start();var optionsWindow=AppOptions.Create(owner,()=>{});optionsWindow.Show();ClickLabel(optionsWindow,"English");ClickLabel(optionsWindow,"Light");Appearance.Refresh();Check(Core.Pref.Language=="en"&&Core.Pref.Theme=="light","option buttons not applied");Check(Convert.ToString(((Button)owner.FindName("Options")).Content)=="Options","English controls not translated");Check(((System.Windows.Media.SolidColorBrush)owner.Background).Color.R>200,"light mode failed");Render(optionsWindow,Path.Combine(output,"options-light.png"));Render(owner,Path.Combine(output,"main-light.png"));ClickLabel(optionsWindow,"Italiano");ClickLabel(optionsWindow,"Scuro");Appearance.Refresh();Check(Convert.ToString(((Button)owner.FindName("Options")).Content)=="Opzioni","Italian restoration failed");Check(((System.Windows.Media.SolidColorBrush)owner.Background).Color.R<50,"dark restoration failed");Render(optionsWindow,Path.Combine(output,"options-dark.png"));optionsWindow.Close();var rs=RenoDxUi.Create(owner,g);rs.Show();Render(rs,Path.Combine(output,"reshade.png"));rs.Close();owner.Close();
  File.WriteAllText(Path.Combine(output,"components.txt"),"PASS: real ReShade stable/nightly archives extracted without execution; standalone and OptiScaler chain; nightly update and baseline restore; read-only INI restore; unrelated loaders preserved; RenoDX addon install/restore; duplicate/unknown loader and stale plan rejection; NVIDIA tag validation/order; embedded DLSS 5 section and slider roundtrip. No real game modifications.");
 }
}
}
