using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Web.Script.Serialization;
using Microsoft.Win32;

namespace HdrPilot {
public class Game {
 public override string ToString(){return Name??"Gioco";}
 public string Id {get;set;} public string Name {get;set;} public string Root {get;set;}
 public string Exe {get;set;} public string Project {get;set;} public string EngineLabel {get;set;}
 public bool Confirmed {get;set;} public string Evidence {get;set;} public string Cover {get;set;}
 public string Hero {get;set;} public string Config {get;set;}
 public string Store {get;set;} public string LaunchId {get;set;} public bool ProtectedInstall {get;set;}
 public bool IsXbox {get{return Store=="Xbox / Game Pass";}}
 public string ArtworkLabel {get{return IsXbox?"XBOX / GAME PASS":Store=="Manual"?"PC":"STEAM";}}
 public string ConfigLabel {get{return ProtectedInstall?"Cartella protetta":!Confirmed?"HDR INI non verificato":String.IsNullOrEmpty(Config)?"Impostazioni da collegare":"Impostazioni trovate";}}
}
public class Preferences {public List<Game> ManualGames=new List<Game>();public string NexusDownloads;public Dictionary<string,InjectionProfile> InjectionProfiles=new Dictionary<string,InjectionProfile>(); public string Language="en",Theme="dark"; public Dictionary<string,DlssOptions> DlssChoices=new Dictionary<string,DlssOptions>(); public Dictionary<string,int> HdrMethods=new Dictionary<string,int>(); public uint HotkeyMods=6; public uint HotkeyKey=72; public string MonitorId; public Dictionary<string,int> MonitorModes=new Dictionary<string,int>(); public List<string> Libraries=new List<string>(); public Dictionary<string,string> Configs=new Dictionary<string,string>(); public Dictionary<string,string> Covers=new Dictionary<string,string>(); public Dictionary<string,string> Sections=new Dictionary<string,string>();}
public class Backup {public string AppId; public string Name; public string Config; public string Created; public string[] Names; public bool[] Existed; public int[] Attributes;}
public static class Core {
 public static string Data=Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"data");
 public static JavaScriptSerializer Json=new JavaScriptSerializer();
 public static Preferences Pref=new Preferences();
 public static List<string> Warnings=new List<string>();
 public static void Init(){Pref=PreferenceStore.Load(Data);ActivityLog.Write("Preferenze caricate · "+Path.Combine(Data,"preferences.json")+" · overlay "+Shortcut.Label(Pref.HotkeyMods,Pref.HotkeyKey));}
 public static void SavePrefs(){PreferenceStore.Save();}
 public static string[] Dirs(string p){try{return Directory.GetDirectories(p);}catch{return new string[0];}}
 public static string[] Files(string p,string pattern){try{return Directory.GetFiles(p,pattern);}catch{return new string[0];}}
 public static string Field(string text,string name){var m=Regex.Match(text,"\""+Regex.Escape(name)+"\"\\s+\"((?:\\\\.|[^\"])*)\"");return m.Success?m.Groups[1].Value.Replace("\\\\","\\").Replace("\\\"","\""):"";}
 public static string SteamRoot(){try{using(var k=Registry.CurrentUser.OpenSubKey(@"Software\Valve\Steam")){if(k!=null){var p=k.GetValue("SteamPath") as string;if(Directory.Exists(p))return p;}}}catch{}return Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86),"Steam");}
 public static List<string> Libraries(){var result=new HashSet<string>(StringComparer.OrdinalIgnoreCase);string steam=SteamRoot();if(Directory.Exists(steam))result.Add(steam);string file=Path.Combine(steam,@"steamapps\libraryfolders.vdf");if(File.Exists(file)){foreach(Match m in Regex.Matches(File.ReadAllText(file),"\"path\"\\s+\"((?:\\\\.|[^\"])*)\"")){string p=m.Groups[1].Value.Replace("\\\\","\\");if(Directory.Exists(p))result.Add(p);}}foreach(string p in Pref.Libraries)if(Directory.Exists(p))result.Add(p);return result.ToList();}
 public static List<Game> Scan(){Warnings.Clear();var list=new List<Game>();var seen=new HashSet<string>();string steam=SteamRoot();foreach(string lib in Libraries())foreach(string mf in Files(Path.Combine(lib,"steamapps"),"appmanifest_*.acf")){
  try{string text=File.ReadAllText(mf);string id=Field(text,"appid");string install=Field(text,"installdir");if(!Regex.IsMatch(id,"^[0-9]+$")||seen.Contains(id)||id=="228980"||String.IsNullOrWhiteSpace(install))continue;
   string common=Path.GetFullPath(Path.Combine(lib,@"steamapps\common"));string root=Path.GetFullPath(Path.Combine(common,install));if(!Under(root,common)||!Directory.Exists(root))continue;
   var g=new Game{Id=id,Name=Field(text,"name"),Root=root};bool unreal=Detect(g);if(!unreal)DetectOther(g);try{InjectionSetup.RestoreTarget(g);}catch(Exception ex){g.Exe="";g.Evidence+=" Target salvato non valido: "+ex.Message;Warnings.Add(g.Name+": target da selezionare.");}seen.Add(id);
   g.Config=unreal?FindConfig(g):"";g.Cover=Artwork(steam,id,"library_600x900.jpg");if(String.IsNullOrEmpty(g.Cover))g.Cover=Artwork(steam,id,"library_capsule.jpg");g.Hero=Artwork(steam,id,"library_hero.jpg");if(String.IsNullOrEmpty(g.Hero))g.Hero=Artwork(steam,id,"library_header.jpg");
   string cover;if(Pref.Covers.TryGetValue(id,out cover)){if(!Path.IsPathRooted(cover))cover=Path.Combine(Data,cover);if(File.Exists(cover))g.Cover=cover;}list.Add(g);
  }catch(Exception ex){Warnings.Add(Path.GetFileName(mf)+": "+ex.Message);}
 }list.AddRange(XboxLibrary.Scan());foreach(var saved in Pref.ManualGames??new List<Game>()){try{if(list.Any(item=>String.Equals(item.Exe,saved.Exe,StringComparison.OrdinalIgnoreCase)))continue;var g=ManualGame(saved.Exe);g.Name=saved.Name;InjectionSetup.RestoreTarget(g);string cover;if(Pref.Covers.TryGetValue(g.Id,out cover)){g.Cover=Path.IsPathRooted(cover)?cover:Path.Combine(Data,cover);}list.Add(g);}catch(Exception ex){Warnings.Add(saved.Name+": "+ex.Message);}}return list.OrderBy(g=>g.Name,StringComparer.CurrentCultureIgnoreCase).ToList();}
 public static Game ManualGame(string executable){string path=Path.GetFullPath(executable);if(!File.Exists(path)||!String.Equals(Path.GetExtension(path),".exe",StringComparison.OrdinalIgnoreCase))throw new Exception("Choose an existing game executable (.exe).");using(var f=File.OpenRead(path)){if(f.ReadByte()!=77||f.ReadByte()!=90)throw new Exception("The selected file is not a Windows executable.");}string id;using(var hash=System.Security.Cryptography.SHA256.Create())id="manual-"+BitConverter.ToString(hash.ComputeHash(Encoding.UTF8.GetBytes(path.ToUpperInvariant()))).Replace("-","").Substring(0,24);string root=Path.GetDirectoryName(path);string project=Path.GetFileName(root);if(project=="Win64"||project=="WinGDK")project=Directory.GetParent(Directory.GetParent(root).FullName).Name;var game=new Game{Id=id,Name=Path.GetFileNameWithoutExtension(path),Exe=path,Root=root,Store="Manual",Project=project,Confirmed=FindEngineMarker(path)=="UE5",Evidence="Manually added executable. Component compatibility must be checked for this game."};game.EngineLabel=game.Confirmed?"UNREAL ENGINE 5":"PC";game.Config=game.Confirmed?FindConfig(game):"";return game;}
 public static bool Under(string child,string parent){return Path.GetFullPath(child).StartsWith(Path.GetFullPath(parent).TrimEnd(Path.DirectorySeparatorChar)+Path.DirectorySeparatorChar,StringComparison.OrdinalIgnoreCase);}
 public static bool Detect(Game g){
  var exes=new List<string>();foreach(string d in Dirs(g.Root)){if(String.Equals(Path.GetFileName(d),"Engine",StringComparison.OrdinalIgnoreCase))continue;foreach(string bin in new[]{Path.Combine(d,@"Binaries\Win64"),Path.Combine(d,@"Binaries\WinGDK")})exes.AddRange(Files(bin,"*.exe"));}
  exes.AddRange(Files(Path.Combine(g.Root,@"Binaries\Win64"),"*.exe"));exes.AddRange(Files(Path.Combine(g.Root,@"Binaries\WinGDK"),"*.exe"));exes=exes.Where(x=>!Path.GetFileName(x).ToLowerInvariant().Contains("crash")).OrderByDescending(x=>new FileInfo(x).Length).ToList();
  if(exes.Count==0)return false;bool layout=Directory.Exists(Path.Combine(g.Root,"Engine"));
  foreach(string exe in exes){string ver="";try{var v=FileVersionInfo.GetVersionInfo(exe);ver=(v.FileVersion??"")+" "+(v.ProductVersion??"");}catch{}
   if(Regex.IsMatch(ver,@"UE4[-+]|\+\+UE4",RegexOptions.IgnoreCase))return false;
   bool ue5=Regex.IsMatch(ver,@"UE5[-+]|\+\+UE5",RegexOptions.IgnoreCase);string marker=ue5?ver.Trim():FindEngineMarker(exe);
   if(marker=="UE4")return false;if(!ue5&&marker=="UE5")ue5=true;
   if(ue5||layout){g.Exe=exe;g.Project=Path.GetFileName(Directory.GetParent(Directory.GetParent(Path.GetDirectoryName(exe)).FullName).FullName);g.Confirmed=ue5;g.EngineLabel=ue5?"UNREAL ENGINE 5":"UNREAL · DA VERIFICARE";g.Evidence=ue5?"UE5 rilevato nei metadati o nella firma del file eseguibile.":"Struttura Unreal rilevata; versione 5 non confermata. Verificala prima di applicare.";return true;}
  }return false;
 }
 public static void DetectOther(Game g){g.EngineLabel=g.IsXbox?"XBOX / GAME PASS":"STEAM";g.Project="";g.Evidence="HDR tramite INI Unreal non verificato per questo gioco. ReShade / RenoDX richiede una mod compatibile; DLSS 5 dipende da gioco e build.";var candidates=new List<string>();var queue=new Queue<Tuple<string,int>>();queue.Enqueue(Tuple.Create(g.Root,0));while(queue.Count>0&&candidates.Count<2000){var item=queue.Dequeue();candidates.AddRange(Files(item.Item1,"*.exe").Where(f=>!Regex.IsMatch(Path.GetFileName(f),"crash|unins|redist|setup|report|helper|prereq",RegexOptions.IgnoreCase)));if(item.Item2<5)foreach(string dir in Dirs(item.Item1)){if((File.GetAttributes(dir)&FileAttributes.ReparsePoint)!=0||Regex.IsMatch(Path.GetFileName(dir),"^(_CommonRedist|Engine|Support|Installer|EasyAntiCheat|BattlEye)$",RegexOptions.IgnoreCase))continue;queue.Enqueue(Tuple.Create(dir,item.Item2+1));}}g.Exe=candidates.OrderByDescending(f=>DlssCore.Pe64(f)).ThenByDescending(f=>new FileInfo(f).Length).FirstOrDefault()??"";if(g.Exe=="")g.Evidence+=" Seleziona manualmente il target.exe.";}
 static string FindEngineMarker(string file){try{using(var s=File.OpenRead(file)){byte[] buffer=new byte[1024*1024+128];int remain=0;long total=0;while(total<512L*1024*1024){int n=s.Read(buffer,remain,1024*1024);if(n==0)break;int length=remain+n;string a=Encoding.ASCII.GetString(buffer,0,length);string u=Encoding.Unicode.GetString(buffer,0,length-length%2);if(a.Contains("++UE5+")||u.Contains("++UE5+")||a.Contains("Unreal Engine 5")||u.Contains("Unreal Engine 5"))return "UE5";if(a.Contains("++UE4+Release")||u.Contains("++UE4+Release"))return "UE4";remain=Math.Min(128,length);Buffer.BlockCopy(buffer,length-remain,buffer,0,remain);total+=n;}}}catch{}return "";}
 public static string Artwork(string steam,string id,string name){string root=Path.Combine(steam,@"appcache\librarycache");string old=Path.Combine(root,id+"_"+name);if(File.Exists(old))return old;string per=Path.Combine(root,id);string direct=Path.Combine(per,name);if(File.Exists(direct))return direct;foreach(string d in Dirs(per)){string p=Path.Combine(d,name);if(File.Exists(p))return p;}return "";}
 public static string FindConfig(Game g){string saved;if(Pref.Configs.TryGetValue(g.Id,out saved)&&File.Exists(Path.Combine(saved,"GameUserSettings.ini")))return saved;
  var names=new HashSet<string>(StringComparer.OrdinalIgnoreCase){g.Project,g.Project+"_Demo",g.Project+"Demo",Path.GetFileName(g.Root)};
  var matches=new HashSet<string>(StringComparer.OrdinalIgnoreCase);string local=Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
  foreach(string name in names){if(String.IsNullOrWhiteSpace(name))continue;foreach(string platform in new[]{"Windows","WindowsNoEditor","WindowsClient","WinGDK"}){string p=Path.Combine(local,name,"Saved","Config",platform);if(File.Exists(Path.Combine(p,"GameUserSettings.ini")))matches.Add(p);}}
  foreach(string platform in new[]{"Windows","WindowsNoEditor","WindowsClient","WinGDK"}){string p=Path.Combine(g.Root,g.Project,"Saved","Config",platform);if(File.Exists(Path.Combine(p,"GameUserSettings.ini")))matches.Add(p);}
  return matches.Count==1?matches.First():"";
 }
 public static List<string> Sections(string text){return Regex.Matches(text,@"(?m)^\s*\[([^\]\r\n]+)\]\s*\r?$").Cast<Match>().Select(m=>m.Groups[1].Value).Where(s=>s.IndexOf("UserSettings",StringComparison.OrdinalIgnoreCase)>=0).Distinct().ToList();}
 public static string Get(string text,string section,string key){bool inside=false;string value=null;foreach(string l in Regex.Split(text,"\r?\n")){var m=Regex.Match(l,@"^\s*\[([^\]]+)\]\s*$");if(m.Success){inside=String.Equals(m.Groups[1].Value,section,StringComparison.OrdinalIgnoreCase);continue;}if(inside){var k=Regex.Match(l,"^\\s*"+Regex.Escape(key)+"\\s*=\\s*(.*)$",RegexOptions.IgnoreCase);if(k.Success)value=k.Groups[1].Value.Trim();}}return value;}
 public static string Set(string text,string section,string key,string value){string nl=text.Contains("\r\n")?"\r\n":"\n";var lines=Regex.Split(text,"\r?\n").ToList();bool inside=false,found=false,keyFound=false;int insert=-1;for(int i=0;i<lines.Count;i++){var m=Regex.Match(lines[i],@"^\s*\[([^\]]+)\]\s*$");if(m.Success){if(inside&&insert<0)insert=i;inside=String.Equals(m.Groups[1].Value,section,StringComparison.OrdinalIgnoreCase);if(inside)found=true;}else if(inside&&Regex.IsMatch(lines[i],"^\\s*"+Regex.Escape(key)+"\\s*=",RegexOptions.IgnoreCase)){lines[i]=key+"="+value;keyFound=true;}}
  if(!keyFound){if(!found){lines.Add("");lines.Add("["+section+"]");lines.Add(key+"="+value);}else if(insert>=0)lines.Insert(insert,key+"="+value);else lines.Add(key+"="+value);}return String.Join(nl,lines);
 }
 public static int Number(string text,string name,int min,int max){int n;if(!Regex.IsMatch(text.Trim(),"^[0-9]+$")||!Int32.TryParse(text,out n)||n<min||n>max)throw new Exception(name+": inserisci un intero tra "+min+" e "+max+".");return n;}
 public static void Closed(Game g){if(g.ProtectedInstall)throw new Exception(g.Evidence);foreach(var p in Process.GetProcesses()){try{if(p.Id==Process.GetCurrentProcess().Id)continue;string name=Path.GetFileNameWithoutExtension(g.Exe??"");if(!String.IsNullOrEmpty(name)&&String.Equals(p.ProcessName,name,StringComparison.OrdinalIgnoreCase))throw new InvalidOperationException("Chiudi "+g.Name+" prima di modificare le impostazioni.");}finally{p.Dispose();}}}
 public static string Apply(Game g,string section,int peak,int mid,int ui,string black,AdvancedHdr advanced=null){ActivityLog.Write("HDR UE5 · preparo le impostazioni per "+g.Name);Closed(g);if(String.IsNullOrEmpty(g.Config))throw new Exception("Scegli la cartella delle impostazioni.");string up=Path.Combine(g.Config,"GameUserSettings.ini"),ep=Path.Combine(g.Config,"Engine.ini");string user=File.ReadAllText(up);if(!Sections(user).Contains(section))throw new Exception("La sezione selezionata non esiste più. Ricarica il gioco nella libreria.");string engine=File.Exists(ep)?File.ReadAllText(ep):"";
  var values=new Dictionary<string,string>{{"r.AllowHDR","1"},{"r.HDR.EnableHDROutput","1"},{"r.HDR.Display.OutputDevice","5"},{"r.HDR.Display.ColorGamut","0"},{"r.HDR.Display.MaxLuminance",peak.ToString(CultureInfo.InvariantCulture)},{"r.HDR.Display.MidLuminance",mid.ToString(CultureInfo.InvariantCulture)},{"r.HDR.UI.CompositeMode","1"},{"r.HDR.UI.Level",(ui/100.0m).ToString(CultureInfo.InvariantCulture)}};
  if(advanced!=null){foreach(var pair in advanced.Values())values[pair.Key]=pair.Value;}else{foreach(string key in new[]{"r.HDR.Display.OutputDevice","r.HDR.Display.ColorGamut","r.HDR.UI.CompositeMode"})if(Get(engine,"SystemSettings",key)!=null)values.Remove(key);}
  if(black!=null)values["r.HDR.Display.MinLuminanceLog10"]=black;foreach(var kv in values)engine=Set(engine,"SystemSettings",kv.Key,kv.Value);user=Set(user,section,"bUseHDRDisplayOutput","True");user=Set(user,section,"HDRDisplayOutputNits",peak.ToString(CultureInfo.InvariantCulture));return WritePair(g,EncodeLike(ep,engine),EncodeLike(up,user));
 }
 static byte[] EncodeLike(string path,string text){Encoding enc=new UTF8Encoding(false);if(File.Exists(path)){byte[] b=File.ReadAllBytes(path);if(b.Length>=2&&b[0]==255&&b[1]==254)enc=Encoding.Unicode;else if(b.Length>=2&&b[0]==254&&b[1]==255)enc=Encoding.BigEndianUnicode;else if(b.Length>=3&&b[0]==239&&b[1]==187&&b[2]==191)enc=new UTF8Encoding(true);}return enc.GetPreamble().Concat(enc.GetBytes(text)).ToArray();}
 public static string WritePair(Game g,byte[] engine,byte[] user){try{return WritePairImpl(g,engine,user);}catch(Exception ex){ActivityLog.Write("ERRORE HDR: "+ex.Message);throw;}}
 static string WritePairImpl(Game g,byte[] engine,byte[] user){
  ActivityLog.Write("HDR · lettura originali e attributi");
  string config=Path.GetFullPath(g.Config);string[] names={"Engine.ini","GameUserSettings.ini"};var originals=new byte[2][];bool[] exists=new bool[2];int[] attrs=new int[2];for(int i=0;i<2;i++){string f=Path.Combine(config,names[i]);exists[i]=File.Exists(f);attrs[i]=exists[i]?(int)File.GetAttributes(f):(int)FileAttributes.Normal;originals[i]=exists[i]?File.ReadAllBytes(f):null;}
  string dir=Path.Combine(Data,"backups",g.Id,DateTime.Now.ToString("yyyyMMdd-HHmmss-fff")+"-"+Guid.NewGuid().ToString("N").Substring(0,6));Directory.CreateDirectory(dir);
  for(int i=0;i<2;i++)if(exists[i])File.WriteAllBytes(Path.Combine(dir,names[i]),originals[i]);var meta=new Backup{AppId=g.Id,Name=g.Name,Config=config,Created=DateTime.Now.ToString("s"),Names=names,Existed=exists,Attributes=attrs};File.WriteAllText(Path.Combine(dir,"backup.json"),Json.Serialize(meta));
  ActivityLog.Write("HDR · backup creato: "+dir);var touched=new List<int>();try{
   for(int i=0;i<2;i++){string f=Path.Combine(config,names[i]);if(exists[i]){File.SetAttributes(f,(FileAttributes)(attrs[i]&~(int)FileAttributes.ReadOnly));using(File.Open(f,FileMode.Open,FileAccess.Write,FileShare.Read)){}}}
   byte[][] targets={engine,user};for(int i=0;i<2;i++){string f=Path.Combine(config,names[i]);touched.Add(i);ActivityLog.Write("HDR · "+(targets[i]==null?"rimozione ":"scrittura ")+names[i]);if(targets[i]==null){if(File.Exists(f))File.Delete(f);}else File.WriteAllBytes(f,targets[i]);}
   for(int i=0;i<2;i++){string f=Path.Combine(config,names[i]);if(targets[i]==null?File.Exists(f):!File.ReadAllBytes(f).SequenceEqual(targets[i]))throw new Exception("Verifica del salvataggio fallita.");}
  }catch(Exception ex){var errors=new List<string>();foreach(int i in touched){try{string f=Path.Combine(config,names[i]);if(exists[i])File.WriteAllBytes(f,originals[i]);else if(File.Exists(f))File.Delete(f);}catch(Exception e){errors.Add(e.Message);}}throw new Exception(ex.Message+"\nBackup: "+dir+(errors.Count>0?"\nRipristino incompleto: "+String.Join("; ",errors):"\nFile precedenti conservati o ripristinati."));}
  finally{var errors=new List<string>();for(int i=0;i<2;i++){try{string f=Path.Combine(config,names[i]);if(File.Exists(f))File.SetAttributes(f,(FileAttributes)attrs[i]);}catch(Exception e){errors.Add(e.Message);}}if(errors.Count>0)throw new Exception("Controlla gli attributi dei file: "+String.Join("; ",errors)+"\nBackup: "+dir);}
  ActivityLog.Write("HDR · rilettura verificata, attributi ripristinati, operazione completata");return dir;
 }
 public static List<string> Backups(Game g){string root=Path.Combine(Data,"backups",g.Id);return Dirs(root).Where(d=>File.Exists(Path.Combine(d,"backup.json"))).OrderByDescending(d=>d).ToList();}
 public static string Restore(Game g,string backup){ActivityLog.Write("HDR · ripristino richiesto per "+g.Name);Closed(g);if(!Under(backup,Path.Combine(Data,"backups",g.Id)))throw new Exception("Backup non appartenente al gioco.");var b=Json.Deserialize<Backup>(File.ReadAllText(Path.Combine(backup,"backup.json")));if(b.AppId!=g.Id||!String.Equals(Path.GetFullPath(b.Config),Path.GetFullPath(g.Config),StringComparison.OrdinalIgnoreCase)||b.Names.Length!=2||b.Names[0]!="Engine.ini"||b.Names[1]!="GameUserSettings.ini")throw new Exception("Il backup appartiene a una cartella diversa.");byte[] e=b.Existed[0]?File.ReadAllBytes(Path.Combine(backup,"Engine.ini")):null;byte[] u=b.Existed[1]?File.ReadAllBytes(Path.Combine(backup,"GameUserSettings.ini")):null;return WritePair(g,e,u);}
 public static string Report(Game g,string section){string e=File.Exists(Path.Combine(g.Config,"Engine.ini"))?File.ReadAllText(Path.Combine(g.Config,"Engine.ini")):"";string u=File.ReadAllText(Path.Combine(g.Config,"GameUserSettings.ini"));var sb=new StringBuilder("VERIFICA DEI FILE — NON DEI VALORI IN MEMORIA\n\n");sb.AppendLine(g.Name);sb.AppendLine(g.Config);sb.AppendLine();foreach(string k in new[]{"r.HDR.EnableHDROutput","r.HDR.Display.MaxLuminance","r.HDR.Display.MidLuminance","r.HDR.Display.MinLuminanceLog10","r.HDR.UI.Level","r.HDR.Display.OutputDevice"})sb.AppendLine(k+" = "+(Get(e,"SystemSettings",k)??"non impostato"));sb.AppendLine("bUseHDRDisplayOutput = "+Get(u,section,"bUseHDRDisplayOutput"));sb.AppendLine("HDRDisplayOutputNits = "+Get(u,section,"HDRDisplayOutputNits"));string log=Path.Combine(Path.GetDirectoryName(g.Exe),"OptiScaler.log");if(File.Exists(log)){sb.AppendLine("\nOptiScaler: log del "+File.GetLastWriteTime(log).ToString("g"));try{foreach(string l in File.ReadLines(log).Where(l=>l.Contains("Output HDR Active:")||l.Contains("MenuHdrCheck")).Reverse().Take(3).Reverse())sb.AppendLine(l);}catch{}sb.AppendLine("Il log può appartenere a un avvio precedente.");}sb.AppendLine("\nPer i valori in gioco serve la console Unreal. Premi F10 solo se la console è già stata abilitata, poi digita il nome del parametro senza assegnare un valore. HDLSS non installa UE4SS automaticamente.");return sb.ToString();}
}
}

