using System;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Collections.Generic;
using System.Net;
using System.Security.Cryptography;
using System.Text.RegularExpressions;
using System.Diagnostics;
namespace HdrPilot {
public sealed class DllDownload {public string Version,Url,File,Md5,ZipMd5,Origin;public override string ToString(){return Version+" · "+Origin;}}
public static class DllCatalog {
 public const string ManifestUrl="https://raw.githubusercontent.com/beeradmoore/dlss-swapper-manifest-builder/main/manifest.json";
 public static List<DllDownload> Parse(string json,string file){string key=file=="nvngx_dlss.dll"?"dlss":file=="nvngx_dlssd.dll"?"dlss_d":file=="nvngx_dlssg.dll"?"dlss_g":null;if(key==null)throw new Exception("Componente non supportato.");var serializer=new System.Web.Script.Serialization.JavaScriptSerializer{MaxJsonLength=16000000};var root=serializer.Deserialize<Dictionary<string,object>>(json);var list=((System.Collections.IEnumerable)root[key]).Cast<Dictionary<string,object>>();var result=new List<DllDownload>();foreach(var x in list){if(Convert.ToBoolean(x["is_dev_file"])||!Convert.ToBoolean(x["is_signature_valid"]))continue;string version=Convert.ToString(x["version"]),url=Convert.ToString(x["download_url"]),md5=Convert.ToString(x["md5_hash"]),zip=Convert.ToString(x["zip_md5_hash"]);Uri u;if(!Regex.IsMatch(version,@"^\d+\.\d+\.\d+\.\d+$")||!Uri.TryCreate(url,UriKind.Absolute,out u)||u.Scheme!="https"||u.Host!="dlss-swapper-downloads.beeradmoore.com"||!u.AbsolutePath.StartsWith("/"+key+"/")||!u.AbsolutePath.EndsWith(".zip")||!Regex.IsMatch(md5,@"^[a-fA-F0-9]{32}$")||!Regex.IsMatch(zip,@"^[a-fA-F0-9]{32}$"))continue;result.Add(new DllDownload{Version=version,Url=url,Md5=md5,ZipMd5=zip,File=file,Origin=Convert.ToString(x["dll_source"])});}return result.OrderByDescending(x=>new Version(x.Version)).GroupBy(x=>x.Version).Select(x=>x.First()).Take(10).ToList();}
 public static List<DllDownload> Fetch(string file){ServicePointManager.SecurityProtocol|=SecurityProtocolType.Tls12;using(var web=new DlssCore.DownloadClient()){web.Headers[HttpRequestHeader.UserAgent]="HDR-Unlock/0.1";return Parse(web.DownloadString(ManifestUrl),file);}}
 static string Md5(string path){using(var s=File.OpenRead(path))using(var hash=MD5.Create())return BitConverter.ToString(hash.ComputeHash(s)).Replace("-","");}
 public static string Extract(DllDownload item,string zip,string dest){if(!Md5(zip).Equals(item.ZipMd5,StringComparison.OrdinalIgnoreCase))throw new Exception("Archivio diverso dal catalogo.");Directory.CreateDirectory(Path.GetDirectoryName(dest));using(var stream=File.OpenRead(zip))using(var archive=new ZipArchive(stream,ZipArchiveMode.Read)){var entries=archive.Entries.Where(x=>x.FullName.Equals(item.File,StringComparison.OrdinalIgnoreCase)).ToList();if(entries.Count!=1||entries[0].Length>250000000)throw new Exception("Componente non univoco o troppo grande nell’archivio.");using(var input=entries[0].Open())using(var output=File.Create(dest))input.CopyTo(output);}if(!Md5(dest).Equals(item.Md5,StringComparison.OrdinalIgnoreCase))throw new Exception("DLL diversa dal catalogo.");DlssLibraries.Validate(dest,item.File);var info=FileVersionInfo.GetVersionInfo(dest);string v=info.FileMajorPart+"."+info.FileMinorPart+"."+info.FileBuildPart+"."+info.FilePrivatePart;if(v!=item.Version)throw new Exception("Versione interna diversa da quella scelta.");return dest;}
 public static string Download(DllDownload item,Action<string> progress){Uri u=new Uri(item.Url);if(u.Scheme!="https"||u.Host!="dlss-swapper-downloads.beeradmoore.com"||!DlssLibraries.Names.Contains(item.File))throw new Exception("Fonte del componente non valida.");ServicePointManager.SecurityProtocol|=SecurityProtocolType.Tls12;string dir=Path.Combine(Core.Data,"dll-library","catalog",Guid.NewGuid().ToString("N"));Directory.CreateDirectory(dir);string zip=Path.Combine(dir,"package.zip");progress("Scarico "+item.File+" "+item.Version+" · catalogo DLSS Swapper…");using(var web=new DlssCore.DownloadClient()){web.Headers[HttpRequestHeader.UserAgent]="HDR-Unlock/0.1";web.DownloadFile(item.Url,zip);}string dest=Extract(item,zip,Path.Combine(dir,item.File));File.WriteAllText(Path.Combine(dir,"origine.txt"),"Catalogo DLSS Swapper\n"+ManifestUrl+"\n"+item.Url+"\nOrigine dichiarata: "+item.Origin+"\nFirma NVIDIA verificata\nSHA256 "+DlssCore.Hash(dest));return dest;}
}
}
