using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
namespace HdrPilot {
public sealed class DlssBuild {
 public string Id,Name,Repo,Description;
 public override string ToString(){return Name;}
 public static readonly DlssBuild[] All={
 new DlssBuild{Id="dagherbou",Name="Dagherbou · DLSS-NR",Repo="Dagherbou/OptiScaler_DLSSNR",Description="Aggiunge Neural Rendering dopo l’upscaling: il modello rielabora l’immagine e sintetizza dettagli. È la variante di partenza dei tre fork. Richiede un modello NR compatibile; il costo in FPS dipende da gioco e risoluzione."},
 new DlssBuild{Id="wilsjo2",Name="wilsjo2 · Pre-SR / Multipass",Repo="wilsjo2/OptiScaler-DLSSNR-PreSR-Multipass",Description="Permette Neural Rendering prima o dopo l’upscaling e da 1 a 3 passaggi, con regolazioni per ciascun passaggio nel menu OptiScaler. Prima dell’upscaling il modello può lavorare su meno pixel. Parti da 1 passaggio: aumentarli costa prestazioni e può trasformare maggiormente l’immagine."},
 new DlssBuild{Id="y4my4my4m",Name="y4my4my4m · Multipass / MFG",Repo="y4my4my4m/OptiScaler_DLSSNR_Multipass_MFG",Description="Variante sperimentale con più passaggi NR e funzioni MFG, cioè generazione di più fotogrammi intermedi. Include un percorso sperimentale per RTX 4000/Ada, legato a gioco e componenti Streamline compatibili. HDLSS non attiva MFG automaticamente: conserva la generazione fotogrammi esistente. Le regolazioni specifiche sono nel menu della build."}};
}
public static class FrameGeneration {
 public static string Configure(string text,DlssOptions o){string mode=o.FrameMode??"keep";if(!new[]{"keep","off","opti","native"}.Contains(mode)||o.FrameMultiplier<2||o.FrameMultiplier>6)throw new Exception("Scelta Frame Generation non valida.");if(mode=="keep")return text;if(o.AdaMfg&&(mode!="native"||o.Build!="y4my4my4m"))throw new Exception("MFG RTX 4000 sperimentale richiede la build y4my4my4m e FG del gioco.");text=Core.Set(text,"FrameGen","Enabled",mode=="opti"?"true":"false");text=Core.Set(text,"FrameGen","FGInput",mode=="opti"?"upscaler":"nofg");text=Core.Set(text,"FrameGen","FGOutput",mode=="opti"?"dlssg":"nofg");if(Core.Get(text,"FrameGen","External")!=null)text=Core.Set(text,"FrameGen","External","false");text=Core.Set(text,"FrameGen","FGNvngxReplacement","None");text=Core.Set(text,"DLSSG","InterpolationCount",mode=="opti"?(o.FrameMultiplier-1).ToString():"auto");text=Core.Set(text,"DLSSG","OverrideInterpolationCount",mode=="native"?(o.FrameMultiplier-1).ToString():"auto");text=Core.Set(text,"DLSSG","ForceDMFG","false");text=Core.Set(text,"DLSSG","OverrideForceDMFG","false");if(o.Build=="y4my4my4m"||Core.Get(text,"DLSSG","AdaMfgUnlock")!=null)text=Core.Set(text,"DLSSG","AdaMfgUnlock",o.AdaMfg&&mode=="native"?"true":"false");return text;}
 public static void ValidateChoice(DlssOptions o,int series){if(o.FrameMode=="keep"||o.FrameMode=="off"||o.FrameMode==null)return;if(series!=40&&series!=50)throw new Exception("GPU RTX 4000/5000 non rilevata: impossibile verificare Frame Generation.");if(o.AdaMfg&&series!=40)throw new Exception("Lo sblocco Ada è riservato a RTX 4000.");if(series==40&&o.FrameMultiplier>2&&!(o.AdaMfg&&o.FrameMode=="native"&&o.Build=="y4my4my4m"))throw new Exception("RTX 4000: DLSS FG standard supporta 2×. Per MFG del gioco serve lo sblocco sperimentale y4my4my4m.");}
 public static void Validate(Game g,DlssOptions o,string package){if(o.FrameMode==null||o.FrameMode=="keep"||o.FrameMode=="off")return;ValidateChoice(o,DlssHardware.Detect().Series);string root=Path.GetDirectoryName(g.Exe);if(InjectionSetup.Profile(g).Api=="dx11"||InjectionSetup.Profile(g).Api=="vulkan")throw new Exception("Questi controlli FG sono previsti per DirectX 12. I ponti DX11/Vulkan richiedono verifica separata.");var dirs=new[]{root,Path.Combine(root,"OptiScaler"),Path.Combine(root,"OptiScaler","streamline")};string[] needed=o.FrameMode=="opti"?new[]{"sl.interposer.dll","sl.common.dll","sl.dlss_g.dll","sl.reflex.dll","sl.pcl.dll","nvngx_dlssg.dll"}:new[]{"sl.interposer.dll","sl.dlss_g.dll","nvngx_dlssg.dll"};foreach(string name in needed)if(!dirs.Any(d=>DlssCore.Pe64(Path.Combine(d,name))))throw new Exception("Componente FG non trovato: "+name+". Occorre uno stack Streamline/FG compatibile già installato. Nessuna DLL del gioco viene sostituita automaticamente.");if(o.FrameMode=="native"){var interposer=dirs.Select(d=>Path.Combine(d,"sl.interposer.dll")).First(File.Exists);var v=FileVersionInfo.GetVersionInfo(interposer);if(v.FileMajorPart<2||(v.FileMajorPart==2&&(v.FileMinorPart<7||(v.FileMinorPart==7&&v.FileBuildPart<1))))throw new Exception("Il moltiplicatore del gioco richiede Streamline 2.7.1 o successivo.");}if(o.AdaMfg){string ini=package==null?Path.Combine(root,"OptiScaler.ini"):Path.Combine(package,"OptiScaler.ini");if(!File.Exists(ini)||Core.Get(File.ReadAllText(ini),"DLSSG","AdaMfgUnlock")==null)throw new Exception("Questa installazione non dichiara AdaMfgUnlock. Aggiorna prima la build y4my4my4m.");}}
}
public sealed class DlssOptions {
 public string Build="dagherbou",Runtime="",Package="",Proxy="auto";public bool Enabled=true;public int Scale=75,Style=-1,Placement=-1,Passes=1,Strength=100;public string Key="keep";public string FrameMode="keep";public int FrameMultiplier=2;public bool AdaMfg=false;
}
public sealed class DlssScan {
 public string Folder,Owner="Nessuna installazione riconosciuta",Build="",Proxy="",Runtime="",Ini="";
 public bool Autopilot,Managed;public List<string> Notes=new List<string>();public List<string> Blockers=new List<string>();
 public override string ToString(){return Owner+"\n"+(String.IsNullOrEmpty(Proxy)?"Loader: non rilevato":"Loader: "+Proxy)+"\n"+(File.Exists(Runtime)?"File del modello DLSS 5 presente":"File del modello DLSS 5 mancante")+"\n"+String.Join("\n",Notes.Concat(Blockers));}
}
public sealed class DlssRelease {public string Tag,Url,Digest,Asset;}
public sealed class DlssFile {public string Name,Before,After,Backup;public int Attributes;}
public sealed class DlssManifest {public int Schema=1;public string Game,Folder,Build,Release,BackupRoot,PreviousOwner;public List<DlssFile> Files=new List<DlssFile>();}
public sealed class DlssChange {public string Name,Source,Expected,SourceHash;public int? RestoreAttributes;public byte[] Bytes;public bool Delete;}
public sealed class DlssPlan {public RenoHdrProfile HdrProfile;public string Folder,Summary,Build,Release;public bool Uninstall,NativeSwap;public string MarkerName=DlssCore.Marker,MarkerExpected;public List<DlssChange> Changes=new List<DlssChange>();public DlssManifest Manifest;public override string ToString(){return Summary+"\n\n"+String.Join("\n",Changes.Select(c=>(c.Delete?"Rimuovi con copia di recupero: ":c.Expected==null?"Aggiungi: ":"Backup e aggiorna: ")+c.Name));}}
public static class DlssCore {
 public const string Marker="hdr-unlock-dlss.json";
 public static readonly string[] Proxies={"dxgi.dll","winmm.dll","version.dll","dbghelp.dll","d3d12.dll","wininet.dll","winhttp.dll"};
 static readonly string[] BackupSuffixes={".dlss5-autopilot-backup",".dlss5kur-yedek",".dlss5-installer-backup"};
 public static string Hash(string file){using(var s=File.OpenRead(file))using(var h=SHA256.Create())return BitConverter.ToString(h.ComputeHash(s)).Replace("-","").ToLowerInvariant();}
 static string BytesHash(byte[] data){using(var h=SHA256.Create())return BitConverter.ToString(h.ComputeHash(data)).Replace("-","").ToLowerInvariant();}
 public static string Safe(string root,string relative){
  if(String.IsNullOrWhiteSpace(relative)||Path.IsPathRooted(relative)||relative.IndexOf(':')>=0||relative.IndexOf('\0')>=0)throw new Exception("Percorso del pacchetto non valido.");
  var parts=relative.Replace('\\','/').Split('/');if(parts.Any(x=>x==".."||x=="."||x.TrimEnd(' ','.')!=x||Regex.IsMatch(x,@"^(CON|PRN|AUX|NUL|COM[1-9]|LPT[1-9])(\.|$)",RegexOptions.IgnoreCase)))throw new Exception("Percorso non sicuro: "+relative);
  string top=Path.GetFullPath(root).TrimEnd(Path.DirectorySeparatorChar)+Path.DirectorySeparatorChar,path=Path.GetFullPath(Path.Combine(top,relative.Replace('/',Path.DirectorySeparatorChar)));
  if(!path.StartsWith(top,StringComparison.OrdinalIgnoreCase))throw new Exception("Percorso fuori dalla cartella.");
  string cursor=path;while(cursor!=null){if((File.Exists(cursor)||Directory.Exists(cursor))&&(File.GetAttributes(cursor)&FileAttributes.ReparsePoint)!=0)throw new Exception("Collegamento filesystem non supportato: "+cursor);if(String.Equals(cursor.TrimEnd('\\'),top.TrimEnd('\\'),StringComparison.OrdinalIgnoreCase))break;cursor=Path.GetDirectoryName(cursor);}return path;
 }
 public static bool Pe64(string file){try{using(var r=new BinaryReader(File.OpenRead(file))){if(r.ReadUInt16()!=0x5a4d)return false;r.BaseStream.Position=60;int offset=r.ReadInt32();if(offset<64||offset>r.BaseStream.Length-6)return false;r.BaseStream.Position=offset;return r.ReadUInt32()==0x4550&&r.ReadUInt16()==0x8664;}}catch{return false;}}
 public static bool IsOpti(string file){if(!File.Exists(file))return false;try{var v=FileVersionInfo.GetVersionInfo(file);if(((v.ProductName??"")+" "+(v.FileDescription??"")).IndexOf("OptiScaler",StringComparison.OrdinalIgnoreCase)>=0)return true;
 if(new FileInfo(file).Length>80000000)return false;byte[] bytes=File.ReadAllBytes(file);string t=Encoding.ASCII.GetString(bytes);return Pe64(file)&&t.Contains("OptiScaler.ini")&&t.Contains("OptiScaler");}catch{return false;}}
 // This exact DLSS 5 Swapper UI overlay is not the separate RenoDX NR renderer.
 // Source: rakanki911/DLSS5-Swapper overlay/README.md and overlay/overlay.cpp.
 // Never exempt arbitrary files merely because their name includes "overlay".
 static bool KnownControlOverlay(string file){
  if(!Regex.IsMatch(Path.GetFileName(file),@"^dlss5-lab-overlay-[0-9a-f]{16}\.addon64$",RegexOptions.IgnoreCase))return false;
  try{return Pe64(file)&&Hash(file)=="0d90c616cc1b051f7417b823e5de46eca36767fe1f3716ba9571fbddae492631";}catch{return false;}
 }
 public static string ReadIni(string folder){string p=Safe(folder,"OptiScaler.ini");return File.Exists(p)?File.ReadAllText(p):"";}
 public static DlssScan Inspect(Game g,bool checkExecutable=true,bool installingNeuralRendering=true){
  if(String.IsNullOrEmpty(g.Exe)||!File.Exists(g.Exe))throw new Exception("Eseguibile del gioco non trovato.");
  var s=new DlssScan{Folder=Path.GetDirectoryName(Path.GetFullPath(g.Exe))};Safe(s.Folder,Path.GetFileName(g.Exe));s.Ini=ReadIni(s.Folder);s.Runtime=Safe(s.Folder,"nvngx_dlssnr.dll");
  if(checkExecutable&&!XboxLibrary.IsGameX64(g,g.Exe))s.Blockers.Add("Impossibile verificare un eseguibile x64: il file potrebbe essere protetto o non compatibile. Lo scambio delle DLL DLSS 5 verifica separatamente la DLL selezionata.");
  var loaders=Proxies.Where(p=>IsOpti(Safe(s.Folder,p))).ToList();if(loaders.Count>1)s.Blockers.Add("Più loader OptiScaler rilevati: risolvi il doppione prima di installare.");s.Proxy=loaders.FirstOrDefault()??"";
  if(s.Proxy!="")s.Owner="OptiScaler rilevato · provenienza da verificare";
  string own=Safe(s.Folder,Marker),foreign=Safe(s.Folder,"dlss5-autopilot.json");
  if(File.Exists(foreign)){try{var m=Core.Json.Deserialize<Dictionary<string,object>>(File.ReadAllText(foreign));object v;if(m.TryGetValue("path",out v)&&Convert.ToString(v)=="optiscaler"){s.Autopilot=true;s.Owner=s.Proxy!=""?"Neural Rendering installato precedentemente con DLSS 5 Autopilot":"Registro di una precedente installazione con DLSS 5 Autopilot · file da verificare";if(m.TryGetValue("opti_build",out v))s.Build=Convert.ToString(v);s.Notes.Add("Provenienza del registro precedente: DLSS 5 Autopilot. Il registro serve solo a riconoscere i file e i backup già presenti; HDLSS non usa Autopilot per installare.");}else s.Blockers.Add("Altra modalità DLSS Autopilot presente: rimuovila dalla sua app prima di aggiungere OptiScaler.");}catch{s.Blockers.Add("Registro Autopilot non leggibile: nessuna rimozione automatica.");}}
  if(File.Exists(own)){var m=ReadManifest(s.Folder);s.Managed=true;s.Build=m.Build;s.Owner="Gestito da HDLSS · "+m.Release;s.Notes.Add("Ripristino: stato precedente a HDLSS ("+m.PreviousOwner+").");}
  foreach(string p in Proxies){string path=Safe(s.Folder,p);if(File.Exists(path)&&!loaders.Contains(p))s.Notes.Add(p+": componente esistente conservato");}
  if(File.Exists(Safe(s.Folder,"ReShade64.dll")))s.Notes.Add("ReShade64.dll presente: caricamento tramite OptiScaler disponibile.");
  foreach(string p in Directory.GetFiles(s.Folder,"*.addon64")){string n=Path.GetFileName(p);if(installingNeuralRendering&&!KnownControlOverlay(Safe(s.Folder,n))&&(n.IndexOf("dlss",StringComparison.OrdinalIgnoreCase)>=0||n.IndexOf("neural",StringComparison.OrdinalIgnoreCase)>=0))s.Blockers.Add("Altro add-on DLSS 5 rilevato: "+n+". Evita due passaggi NR contemporanei.");else s.Notes.Add("Add-on conservato: "+n);}
  if(Directory.Exists(Safe(g.Root,"EasyAntiCheat"))||Directory.Exists(Safe(g.Root,"BattlEye"))||Directory.GetFiles(s.Folder,"*EasyAntiCheat*").Length>0)s.Blockers.Add("Anti-cheat rilevato: installazione non supportata.");
  s.Notes.Add("La presenza dei file non conferma l’attivazione in gioco.");return s;
 }
 public static DlssManifest ReadManifest(string root,string marker=Marker){var m=Core.Json.Deserialize<DlssManifest>(File.ReadAllText(Safe(root,marker)));if(m==null||m.Schema!=1||m.Files==null||m.Files.Count>2000||!String.Equals(m.Folder,Path.GetFullPath(root),StringComparison.OrdinalIgnoreCase))throw new Exception("Registro HDLSS non valido per questa cartella.");foreach(var f in m.Files){Safe(root,f.Name);if(f.Before!=null)Safe(Core.Data,f.Backup);}return m;}
 public static DlssRelease PickRelease(string json,DlssBuild build){
  var releases=Core.Json.Deserialize<List<Dictionary<string,object>>>(json);foreach(var r in releases.OrderByDescending(r=>r.ContainsKey("published_at")?Convert.ToString(r["published_at"]):"",StringComparer.Ordinal)){if(r.ContainsKey("draft")&&Convert.ToBoolean(r["draft"]))continue;object[] assets=(r["assets"] as System.Collections.ArrayList??new System.Collections.ArrayList((object[])r["assets"])).ToArray();
   var candidates=assets.Cast<Dictionary<string,object>>().Where(a=>{string n=Convert.ToString(a["name"]).ToLowerInvariant();return n.Contains("optiscaler")&&(n.EndsWith(".zip")||n.EndsWith(".7z"))&&!n.Contains("with_dlss")&&!n.Contains("rtx40-mfg")&&!n.Contains("symbols");}).ToList();
   if(candidates.Count==0)continue;var a2=candidates.OrderByDescending(a=>Convert.ToString(a["name"]),StringComparer.OrdinalIgnoreCase).First();string url=Convert.ToString(a2["browser_download_url"]);if(!url.StartsWith("https://github.com/"+build.Repo+"/releases/download/",StringComparison.OrdinalIgnoreCase))throw new Exception("Origine del pacchetto non valida.");return new DlssRelease{Tag=Convert.ToString(r["tag_name"]),Url=url,Asset=Convert.ToString(a2["name"]),Digest=a2.ContainsKey("digest")?Convert.ToString(a2["digest"]):""};
  }throw new Exception("Nessun pacchetto OptiScaler compatibile trovato nelle ultime release.");
 }
 public sealed class DownloadClient:WebClient {
 public new string DownloadString(string url){ActivityLog.Progress("Ricerca delle versioni disponibili…");try{string result=base.DownloadString(url);ActivityLog.Progress("Catalogo aggiornato",100);return result;}catch{ActivityLog.Progress("Download non riuscito",100);throw;}}
 public new void DownloadFile(string url,string path){ActivityLog.Progress("Download del componente…");ActivityLog.Write("Download del componente avviato");try{base.DownloadFile(url,path);ActivityLog.Write("Download completato");ActivityLog.Progress("Download terminato · verifica del pacchetto",100);}catch{ActivityLog.Progress("Download non riuscito",100);throw;}}
protected override WebResponse GetWebResponse(WebRequest request){try{var response=base.GetWebResponse(request);ActivityLog.Write("Connessione riuscita: "+request.RequestUri.Host);return response;}catch(Exception ex){ActivityLog.Write("Errore download: "+ex.Message);throw;}}protected override WebRequest GetWebRequest(Uri address){ActivityLog.Write("Download / verifica: "+address.ToString());var req=base.GetWebRequest(address);req.CachePolicy=new System.Net.Cache.RequestCachePolicy(System.Net.Cache.RequestCacheLevel.NoCacheNoStore);req.Timeout=30000;var http=req as HttpWebRequest;if(http!=null)http.ReadWriteTimeout=30000;return req;}}
 static DownloadClient Client(){ServicePointManager.SecurityProtocol|=SecurityProtocolType.Tls12;var w=new DownloadClient();w.Headers[HttpRequestHeader.UserAgent]="HDR-Unlock/0.1";return w;}
 public static string Fetch(DlssBuild b,Action<string> progress,out DlssRelease release){
  progress("Cerco la release sul repository dell’autore…");using(var w=Client())release=PickRelease(w.DownloadString("https://api.github.com/repos/"+b.Repo+"/releases?per_page=10"),b);
  string dir=Path.Combine(Core.Data,"packages",b.Id,Guid.NewGuid().ToString("N"));Directory.CreateDirectory(dir);string archive=Safe(dir,release.Asset);progress("Scarico "+release.Tag+" · "+release.Asset+"…");using(var w=Client())w.DownloadFile(release.Url,archive);
  string hash=Hash(archive);if(!String.IsNullOrEmpty(release.Digest)&&!String.Equals(release.Digest,"sha256:"+hash,StringComparison.OrdinalIgnoreCase))throw new Exception("SHA-256 diverso da quello pubblicato: pacchetto non utilizzato.");
  File.WriteAllText(Path.Combine(dir,"origine.txt"),release.Url+"\nSHA256 "+hash+"\n");progress("Verifico ed estraggo il pacchetto…");return Unpack(archive,Path.Combine(dir,"files"));
 }
 static string Tar(string args){var psi=new ProcessStartInfo(Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.System),"tar.exe"),args){UseShellExecute=false,CreateNoWindow=true,RedirectStandardOutput=true,RedirectStandardError=true};using(var p=Process.Start(psi)){var err=p.StandardError.ReadToEndAsync();string text=p.StandardOutput.ReadToEnd();p.WaitForExit();if(p.ExitCode!=0)throw new Exception("Estrazione non riuscita: "+err.Result);return text;}}
 static string Q(string text){if(text.Contains("\""))throw new Exception("Percorso non valido");return "\""+text+"\"";}
 public static string Unpack(string archive,string root){
  Directory.CreateDirectory(root);if(Directory.GetFileSystemEntries(root).Length!=0)throw new Exception("La cartella di estrazione deve essere vuota.");
  string list=Tar("-tf "+Q(archive)),verbose=Tar("-tvf "+Q(archive));foreach(string line in verbose.Split('\n'))if(line.Length>0&&line[0]!='-'&&line[0]!='d'&&line.Trim().Length>0)throw new Exception("Archivio con collegamenti o elementi speciali non supportato.");
  var names=list.Split(new[]{'\r','\n'},StringSplitOptions.RemoveEmptyEntries);if(names.Length>4000)throw new Exception("Pacchetto troppo grande.");foreach(string n in names){string clean=n.TrimEnd('/');if(clean.StartsWith("./"))clean=clean.Substring(2);if(clean.Length>0)Safe(root,clean);}
  Tar("-xf "+Q(archive)+" -C "+Q(root));var dlls=Directory.GetFiles(root,"OptiScaler.dll",SearchOption.AllDirectories);if(dlls.Length!=1)throw new Exception("L’archivio non contiene un unico OptiScaler.dll.");return Path.GetDirectoryName(dlls[0]);
 }
 public static string Config(string text,DlssOptions o){
  if(o.Scale<25||o.Scale>100||o.Style< -1||o.Style>2||o.Passes<1||o.Passes>3||o.Strength<0||o.Strength>100||o.Placement< -1||o.Placement>1)throw new Exception("Regolazioni DLSS 5 fuori intervallo.");
  text=Core.Set(text,"DlssNr","Enabled",o.Enabled?"true":"false");text=Core.Set(text,"DlssNr","WorkingScale",(o.Scale/100m).ToString(CultureInfo.InvariantCulture));text=Core.Set(text,"DlssNr","Style",o.Style<0?"auto":o.Style.ToString());text=Core.Set(text,"DlssNr","TransferStrength",(o.Strength/100m).ToString(CultureInfo.InvariantCulture));
  if(o.Build=="wilsjo2"){if(o.Placement>=0){text=Core.Set(text,"DlssNr","RunBeforeSR",o.Placement==1?"true":"false");text=Core.Set(text,"DlssNr","FinishedPicture","false");text=Core.Set(text,"DlssNr","DeferredDLSS","false");text=Core.Set(text,"DlssNr","ResidualAcrossRR","false");text=Core.Set(text,"DlssNr","ApplyModel","true");}text=Core.Set(text,"DlssNr","Passes",o.Passes.ToString());}
  text=Core.Set(text,"DlssNr","AutoCapture","false");text=Core.Set(text,"Log","LogToFile","true");if(String.IsNullOrEmpty(Core.Get(text,"Log","LogLevel"))||Core.Get(text,"Log","LogLevel")=="auto")text=Core.Set(text,"Log","LogLevel","2");text=Core.Set(text,"Hotfix","CheckForUpdate","false");text=Core.Set(text,"ProcessFilter","TargetProcessName","auto");
  text=FrameGeneration.Configure(text,o);
  if(o.Key!="keep"){if(!InjectionSetup.ValidMenuKey(o.Key))throw new Exception("Tasto OptiScaler non valido.");text=Core.Set(text,"Menu","ShortcutKey",o.Key);}return text;
 }
 static DlssChange Change(string folder,string name,string source,byte[] bytes,bool delete=false){string dest=Safe(folder,name);return new DlssChange{Name=name,Source=source,SourceHash=source==null?null:Hash(source),Bytes=bytes,Delete=delete,Expected=File.Exists(dest)?Hash(dest):null};}
 public static DlssPlan Prepare(Game g,DlssOptions o,string package,string release){
  ActivityLog.Write("DLSS 5 · controllo loader, compatibilità e piano per "+g.Name);
  var scan=Inspect(g);if(scan.Blockers.Count>0)throw new Exception(String.Join("\n",scan.Blockers));string root=scan.Folder;
  var reshade=RenoDx.Loaders(root);if(reshade.Count>1)throw new Exception("Più loader ReShade: installazione fermata per evitare duplicati.");
  if(File.Exists(Safe(root,"ReShade64.dll"))&&!RenoDx.IsReShade(Safe(root,"ReShade64.dll")))throw new Exception("ReShade64.dll non riconosciuto: verifica il componente prima di collegarlo a OptiScaler.");
  string proxy=o.Proxy=="auto"?(scan.Proxy!=""?scan.Proxy:Proxies.FirstOrDefault(p=>!File.Exists(Safe(root,p)))):o.Proxy;
  if(proxy==null||!Proxies.Contains(proxy))throw new Exception("Nessun nome loader disponibile.");if(scan.Proxy!=""&&proxy!=scan.Proxy)throw new Exception("Conserva il loader già presente; cambia percorso solo dopo la rimozione.");if(File.Exists(Safe(root,proxy))&&!IsOpti(Safe(root,proxy)))throw new Exception(proxy+" appartiene a un altro componente e viene preservato.");
  var plan=new DlssPlan{Folder=root,Build=o.Build,Release=release,Summary=g.Name+"\nBuild: "+o.Build+" · "+release+"\nLoader: "+proxy+"\nNR "+(o.Enabled?"attivo":"spento")+" · modello "+o.Scale+"%\nGenerazione fotogrammi, HDR e altre mod: impostazioni conservate.\nInstallazione nei file; funzionamento in gioco da verificare."};
  var old=scan.Managed?ReadManifest(root):null;
  var manifest=old??new DlssManifest{Game=g.Id,Folder=root,PreviousOwner=scan.Owner,BackupRoot="dlss-backups/"+Guid.NewGuid().ToString("N")};manifest.Build=o.Build;manifest.Release=release;plan.Manifest=manifest;plan.MarkerExpected=File.Exists(Safe(root,Marker))?Hash(Safe(root,Marker)):null;
  if(!String.IsNullOrEmpty(package)){
   string main=Safe(package,"OptiScaler.dll");if(!Pe64(main)||!IsOpti(main)||!File.Exists(Safe(package,"OptiScaler.ini"))||!Directory.Exists(Safe(package,"OptiScaler")))throw new Exception("Seleziona il pacchetto completo x64: OptiScaler.dll, OptiScaler.ini e cartella OptiScaler.");
   foreach(string src in Directory.GetFiles(package,"*",SearchOption.AllDirectories)){
    string rel=src.Substring(Path.GetFullPath(package).TrimEnd('\\').Length+1).Replace('\\','/');Safe(package,rel);string ext=Path.GetExtension(rel).ToLowerInvariant();
    if(rel.Equals("OptiScaler.ini",StringComparison.OrdinalIgnoreCase))continue;
    bool allowed=rel.Equals("OptiScaler.dll",StringComparison.OrdinalIgnoreCase)||rel.Equals("nvngx.dll_dlssnr.dll",StringComparison.OrdinalIgnoreCase)||(rel.StartsWith("OptiScaler/",StringComparison.OrdinalIgnoreCase)&&new[]{".dll",".bin",".json",".ini",".hlsl",".cso"}.Contains(ext));
    if(!allowed||DlssLibraries.Names.Contains(Path.GetFileName(rel),StringComparer.OrdinalIgnoreCase))continue;string target=rel.Equals("OptiScaler.dll",StringComparison.OrdinalIgnoreCase)?proxy:rel;
    plan.Changes.Add(Change(root,target,src,null));
   }
  }else if(scan.Proxy=="")throw new Exception("Prima scarica una build o scegli il pacchetto estratto.");
  string runtime=String.IsNullOrEmpty(o.Runtime)?scan.Runtime:o.Runtime;if(o.Enabled&&!Pe64(runtime))throw new Exception("Manca nvngx_dlssnr.dll x64. Scegli il runtime NR adatto alla tua GPU oppure conserva quello già funzionante.");
  if(!String.IsNullOrEmpty(o.Runtime)&&!String.Equals(Path.GetFullPath(o.Runtime),scan.Runtime,StringComparison.OrdinalIgnoreCase))plan.Changes.Add(Change(root,"nvngx_dlssnr.dll",o.Runtime,null));
  FrameGeneration.Validate(g,o,package);
  string ini=scan.Ini;if(ini.Length==0&&package!=null)ini=File.ReadAllText(Safe(package,"OptiScaler.ini"));ini=Config(ini,o);if(reshade.Contains("ReShade64.dll"))ini=Core.Set(ini,"Plugins","LoadReshade","true");else if(reshade.Count==1)ini=Core.Set(ini,"Plugins","LoadReshade","false");
  plan.Changes.Add(Change(root,"OptiScaler.ini",null,new UTF8Encoding(false).GetBytes(ini)));
  if(o.FrameMode!="keep")plan.Summary+="\nFrame Generation: "+o.FrameMode+" · moltiplicatore richiesto "+o.FrameMultiplier+"×"+(o.AdaMfg?" · RTX 4000 sperimentale":"")+"\nLa configurazione non certifica il funzionamento in gioco. Riavvia dopo l’applicazione.";
  return plan;
 }
 public static DlssPlan PrepareUninstall(Game g,bool removeExternalBaseline=false){
  var s=Inspect(g);var plan=new DlssPlan{Folder=s.Folder,Uninstall=true,Summary=g.Name};
  if(s.Proxy==""&&!s.Managed&&!s.Autopilot)throw new Exception("OptiScaler non rilevato: non c’è un’installazione OptiScaler da rimuovere. ReShade e le mod MFG separate non vengono disinstallati da questo pulsante.");
  if(RenoDx.IsReShade(Safe(s.Folder,"ReShade64.dll"))&&Core.Get(s.Ini,"Plugins","LoadReshade")=="true")throw new Exception("ReShade dipende dal loader OptiScaler. Ripristina prima ReShade dalla sezione HDR, poi rimuovi OptiScaler, per non lasciare una catena incompleta.");
  if(s.Managed){var m=ReadManifest(s.Folder);foreach(var f in m.Files){string p=Safe(s.Folder,f.Name);if(!File.Exists(p)||Hash(p)!=f.After)throw new Exception("File cambiato da un’altra app: "+f.Name+". Ripristino fermato per non perdere modifiche successive.");string backup=f.Before==null?null:Safe(Core.Data,f.Backup);if(backup!=null&&(!File.Exists(backup)||Hash(backup)!=f.Before))throw new Exception("Backup mancante o modificato: "+f.Name);var restore=Change(s.Folder,f.Name,backup,null,backup==null);restore.RestoreAttributes=f.Attributes;plan.Changes.Add(restore);}plan.Changes.Add(Change(s.Folder,Marker,null,null,true));if(removeExternalBaseline){var restores=plan.Changes.ToDictionary(c=>c.Name,StringComparer.OrdinalIgnoreCase);Func<string,string> prior=n=>{Safe(s.Folder,n);DlssChange c;if(restores.TryGetValue(n,out c))return c.Delete?null:c.Source;string path=Safe(s.Folder,n);return File.Exists(path)?path:null;};if(prior("dlss5-autopilot.json")!=null){plan.Summary+="\nRimuove HDLSS e la precedente installazione OptiScaler di Autopilot in un’unica operazione.";return RemoveAutopilotBaseline(plan,prior);}}plan.Summary+="\nRipristina lo stato precedente a HDLSS: "+m.PreviousOwner+".\nSe era già installata una mod esterna, verrà ripristinata anch’essa.";return plan;}
  if(!s.Autopilot)throw new Exception("Installazione esterna senza registro supportato. Nessuna cancellazione alla cieca: usa il disinstallatore originale e Verifica integrità in Steam.");
  return RemoveAutopilotBaseline(plan,n=>{string path=Safe(s.Folder,n);return File.Exists(path)?path:null;});
 }
 static DlssPlan RemoveAutopilotBaseline(DlssPlan plan,Func<string,string> prior){
  Action<DlssChange> put=c=>{plan.Changes.RemoveAll(old=>String.Equals(old.Name,c.Name,StringComparison.OrdinalIgnoreCase));plan.Changes.Add(c);};
  var foreign=Core.Json.Deserialize<Dictionary<string,object>>(File.ReadAllText(prior("dlss5-autopilot.json")));object mode;if(!foreign.TryGetValue("path",out mode)||Convert.ToString(mode)!="optiscaler")throw new Exception("Registro esterno non supportato per la rimozione completa.");object files;if(!foreign.TryGetValue("files",out files))throw new Exception("Elenco Autopilot mancante.");var list=((System.Collections.IEnumerable)files).Cast<object>().Select(Convert.ToString).Distinct(StringComparer.OrdinalIgnoreCase).ToList();if(list.Count>2000)throw new Exception("Registro troppo grande.");
  int restored=0,removed=0;foreach(string name in list){Safe(plan.Folder,name);if(BackupSuffixes.Any(x=>name.EndsWith(x,StringComparison.OrdinalIgnoreCase)))continue;
   string normalized=name.Replace('\\','/'),ext=Path.GetExtension(name).ToLowerInvariant();
   if(ext==".addon64"&&normalized.IndexOf("dlss",StringComparison.OrdinalIgnoreCase)<0)continue;
   if(normalized.StartsWith("ue4ss/",StringComparison.OrdinalIgnoreCase)||normalized.StartsWith("D3D12/",StringComparison.OrdinalIgnoreCase)||new[]{".exe",".pak",".ucas",".utoc",".sav"}.Contains(ext)||Path.GetFileName(name).Equals("Engine.ini",StringComparison.OrdinalIgnoreCase)||Path.GetFileName(name).Equals("GameUserSettings.ini",StringComparison.OrdinalIgnoreCase))throw new Exception("Il registro indica un file del gioco/mod estraneo: "+name);
   if(Proxies.Contains(name,StringComparer.OrdinalIgnoreCase)&&prior(name)!=null&&!IsOpti(prior(name)))throw new Exception("Il loader "+name+" non è più OptiScaler: niente rimozione automatica.");
   var backups=BackupSuffixes.Select(x=>name+x).Where(n=>prior(n)!=null).ToList();
   if(backups.Select(n=>Hash(prior(n))).Distinct().Count()>1)throw new Exception("Più backup diversi per "+name+". Non è possibile scegliere automaticamente l’originale.");
   string backup=backups.Count==0?null:prior(backups[0]);
   if(backup!=null){if(new FileInfo(backup).Length==0)throw new Exception("Backup vuoto: "+name);put(Change(plan.Folder,name,backup,null));foreach(string used in backups)put(Change(plan.Folder,used,null,null,true));restored++;}
   else if(prior(name)!=null){put(Change(plan.Folder,name,null,null,true));removed++;}
  }
  put(Change(plan.Folder,"dlss5-autopilot.json",null,null,true));plan.Summary+="\nRimuovi l’installazione registrata da DLSS Autopilot.\nBackup esterni recuperabili: "+restored+" · file da mettere da parte: "+removed+".\nUna copia di recupero viene creata prima di ogni modifica. I backup utilizzati vengono spostati nella copia di recupero. Gli originali non presenti nei backup NON sono ricostruibili: per certificarli usa Verifica integrità di Steam. ReShade/RenoDX/UE4SS non elencati restano invariati.";return plan;
 }
 static void Write(string path,byte[] bytes,int attrs){Directory.CreateDirectory(Path.GetDirectoryName(path));if(File.Exists(path))File.SetAttributes(path,FileAttributes.Normal);string temp=path+".hdr-unlock-"+Guid.NewGuid().ToString("N")+".tmp";File.WriteAllBytes(temp,bytes);if(File.Exists(path))File.Replace(temp,path,null);else File.Move(temp,path);File.SetAttributes(path,(FileAttributes)attrs);}
 public static string Apply(Game g,DlssPlan plan){ActivityLog.Write((plan.Uninstall?"RIPRISTINO":"INSTALLAZIONE")+" · "+g.Name+" · "+plan.MarkerName);try{ActivityLog.Progress("Verifica dei componenti…");if(plan.HdrProfile!=null)plan.HdrProfile.Validate(g);string recovery=ApplyImpl(g,plan);if(plan.HdrProfile!=null){try{plan.HdrProfile.Commit(g,recovery);}catch{ApplyImpl(g,Recovery(g,Path.Combine(recovery,"transaction.json")));throw;}}ActivityLog.Progress("Operazione completata",100);return recovery;}catch(Exception ex){ActivityLog.Progress("Operazione interrotta · consulta il registro",100);ActivityLog.Write("ERRORE · "+ex.Message);throw;}}
 static string ApplyImpl(Game g,DlssPlan plan){
  Core.Closed(g);if(!String.Equals(plan.NativeSwap?Path.GetFullPath(g.Root):Path.GetDirectoryName(Path.GetFullPath(g.Exe)),plan.Folder,StringComparison.OrdinalIgnoreCase))throw new Exception("Il gioco selezionato è cambiato.");
  string tx=Path.Combine(Core.Data,"dlss-recovery",DateTime.Now.ToString("yyyyMMdd-HHmmss")+"-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(tx);
  if(plan.Manifest!=null&&(File.Exists(Safe(plan.Folder,plan.MarkerName))?Hash(Safe(plan.Folder,plan.MarkerName)):null)!=plan.MarkerExpected)throw new Exception("Registro cambiato dopo l’anteprima: prepara di nuovo.");
  if(plan.Changes.Select(c=>c.Name).Distinct(StringComparer.OrdinalIgnoreCase).Count()!=plan.Changes.Count)throw new Exception("Percorsi duplicati nel piano.");
  ActivityLog.Write("Verifica percorsi, file correnti e hash delle sorgenti");var changes=new List<DlssChange>(plan.Changes);var before=new List<DlssFile>();var payload=new Dictionary<string,byte[]>();
  foreach(var c in changes){string path=Safe(plan.Folder,c.Name);if((File.Exists(path)?Hash(path):null)!=c.Expected)throw new Exception("File cambiato dopo l’anteprima: "+c.Name+". Prepara di nuovo.");if(!c.Delete){if(c.SourceHash!=null&&Hash(c.Source)!=c.SourceHash)throw new Exception("Sorgente cambiata dopo l’anteprima: "+c.Name);payload[c.Name]=c.Bytes??File.ReadAllBytes(c.Source);}}
  if(plan.Manifest!=null){var m=plan.Manifest;foreach(var c in changes){var entry=m.Files.FirstOrDefault(f=>String.Equals(f.Name,c.Name,StringComparison.OrdinalIgnoreCase));if(entry==null){entry=new DlssFile{Name=c.Name,Before=c.Expected,Attributes=File.Exists(Safe(plan.Folder,c.Name))?(int)File.GetAttributes(Safe(plan.Folder,c.Name)):(int)FileAttributes.Normal,Backup=m.BackupRoot+"/"+c.Name};m.Files.Add(entry);if(entry.Before!=null){string dst=Safe(Core.Data,entry.Backup);Directory.CreateDirectory(Path.GetDirectoryName(dst));if(File.Exists(dst)){if(Hash(dst)!=entry.Before)throw new Exception("Backup preesistente diverso: "+c.Name);}else File.Copy(Safe(plan.Folder,c.Name),dst,false);}}entry.After=BytesHash(payload[c.Name]);}
   var mc=Change(plan.Folder,plan.MarkerName,null,new UTF8Encoding(false).GetBytes(Core.Json.Serialize(m)));changes.Add(mc);payload[plan.MarkerName]=mc.Bytes;
  }
  foreach(var c in changes){string path=Safe(plan.Folder,c.Name);var f=new DlssFile{Name=c.Name,Before=c.Expected,After=c.Delete?null:BytesHash(payload[c.Name]),Attributes=File.Exists(path)?(int)File.GetAttributes(path):(int)FileAttributes.Normal,Backup=c.Name};before.Add(f);if(File.Exists(path)){string dst=Safe(tx,c.Name);Directory.CreateDirectory(Path.GetDirectoryName(dst));File.Copy(path,dst);}}
  ActivityLog.Progress("Backup dei file originali…");ActivityLog.Write("Backup e copia di recupero creati: "+tx);File.WriteAllText(Path.Combine(tx,"transaction.json"),Core.Json.Serialize(new DlssManifest{Folder=plan.Folder,Files=before}));File.WriteAllText(Path.Combine(tx,"state.txt"),"pending");var touched=new List<DlssFile>();
  try{int completed=0;foreach(var c in changes){ActivityLog.Progress("Applicazione dei file · "+completed+" / "+changes.Count,100.0*completed/Math.Max(1,changes.Count));string path=Safe(plan.Folder,c.Name);var f=before.First(x=>x.Name==c.Name);touched.Add(f);ActivityLog.Write((c.Delete?"Rimozione: ":"Scrittura: ")+c.Name);if(c.Delete){if(File.Exists(path)){File.SetAttributes(path,FileAttributes.Normal);File.Delete(path);}}else Write(path,payload[c.Name],c.RestoreAttributes??f.Attributes);if((File.Exists(path)?Hash(path):null)!=f.After)throw new Exception("Verifica fallita: "+c.Name);completed++;}File.WriteAllText(Path.Combine(tx,"state.txt"),"complete");ActivityLog.Write("Hash finali verificati · operazione completata");}
  catch(Exception ex){ActivityLog.Write("Errore di scrittura · annullamento delle modifiche");var errors=new List<string>();foreach(var f in touched.AsEnumerable().Reverse()){try{string path=Safe(plan.Folder,f.Name);if(f.Before==null){if(File.Exists(path)){File.SetAttributes(path,FileAttributes.Normal);File.Delete(path);}}else Write(path,File.ReadAllBytes(Safe(tx,f.Name)),f.Attributes);}catch(Exception err){errors.Add(err.Message);}}File.WriteAllText(Path.Combine(tx,"state.txt"),errors.Count==0?"rolled-back":"recovery-needed");throw new Exception(ex.Message+"\n"+(errors.Count==0?"Modifiche annullate.":"Recupero richiesto: "+String.Join("; ",errors))+"\nCopia di recupero: "+tx);}
  return tx;
 }
 public static DlssPlan Recovery(Game g,string transaction){string recoveryRoot=Path.GetFullPath(Path.Combine(Core.Data,"dlss-recovery"))+Path.DirectorySeparatorChar;string full=Path.GetFullPath(transaction);if(!full.StartsWith(recoveryRoot,StringComparison.OrdinalIgnoreCase)||Path.GetFileName(full)!="transaction.json")throw new Exception("Scegli un registro dalla cartella dlss-recovery di questa app.");var m=Core.Json.Deserialize<DlssManifest>(File.ReadAllText(full));if(m==null||m.Files==null)throw new Exception("Registro non valido.");var plan=new DlssPlan{Folder=m.Folder,NativeSwap=String.Equals(Path.GetFullPath(g.Root),m.Folder,StringComparison.OrdinalIgnoreCase),Uninstall=true,Summary="Annulla l’operazione usando la copia di recupero. Sono ripristinati solo i file elencati nel registro; gli altri restano invariati."};foreach(var f in m.Files){string dst=Safe(m.Folder,f.Name);if((File.Exists(dst)?Hash(dst):null)!=f.After)throw new Exception("File cambiato dopo l’operazione: "+f.Name);string backup=f.Before==null?null:Safe(Path.GetDirectoryName(full),f.Backup);if(backup!=null&&(!File.Exists(backup)||Hash(backup)!=f.Before))throw new Exception("Backup non valido: "+f.Name);var c=Change(m.Folder,f.Name,backup,null,backup==null);c.RestoreAttributes=f.Attributes;plan.Changes.Add(c);}return plan;}
 public static string Diagnose(Game g){var s=Inspect(g);var text=new StringBuilder(s.ToString());foreach(string name in new[]{"OptiScaler.log","ReShade.log"}){string p=Safe(s.Folder,name);if(!File.Exists(p))continue;text.AppendLine("\n"+name+" · "+File.GetLastWriteTime(p).ToString("g"));using(var stream=new FileStream(p,FileMode.Open,FileAccess.Read,FileShare.ReadWrite)){stream.Seek(Math.Max(0,stream.Length-160000),SeekOrigin.Begin);using(var r=new StreamReader(stream)){var lines=r.ReadToEnd().Split('\n').Where(l=>Regex.IsMatch(l,"dlssnr|neural|reshade|renodx|error|fail",RegexOptions.IgnoreCase)).Reverse().Take(22).Reverse();foreach(string l in lines)text.AppendLine(l.Trim());}}}text.AppendLine("\nEstratti diagnostici: un log vecchio o la sola presenza di una DLL non certificano DLSS 5 attivo.");return text.ToString();}
}
}
