using System;
using System.IO;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;
namespace HdrPilot {
public static class DlssTests {
 static void Check(bool ok,string why){if(!ok)throw new Exception(why);}
 static void Reject(Action action,string why){bool rejected=false;try{action();}catch{rejected=true;}Check(rejected,why);}
 static void FakePe(string path,bool opti){Directory.CreateDirectory(Path.GetDirectoryName(path));var b=new byte[256];b[0]=77;b[1]=90;b[60]=64;b[64]=80;b[65]=69;b[68]=100;b[69]=134;if(opti)System.Text.Encoding.ASCII.GetBytes("OptiScaler.ini OptiScaler").CopyTo(b,90);File.WriteAllBytes(path,b);}
 public static void Run(string folder,string controlOverlay=null){Directory.CreateDirectory(folder);string fixture=Path.Combine(folder,"fixture-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(fixture);Core.Data=Path.Combine(fixture,"data");Directory.CreateDirectory(Core.Data);var game=new Game{Id="test",Name="Test",Root=Path.Combine(fixture,"game"),Exe=Path.Combine(fixture,"game","Game.exe")};FakePe(game.Exe,false);
  // Names alone must not turn an unknown DLSS/NR add-on into a trusted UI overlay.
  string overlayName="dlss5-lab-overlay-0d90c616cc1b051f.addon64",overlay=Path.Combine(game.Root,overlayName);
  foreach(string name in new[]{overlayName,"dlss5-custom-overlay.addon64","renodx-dlss5.addon64","neural-rendering.addon64"}){
   string file=Path.Combine(game.Root,name);FakePe(file,false);
   Check(DlssCore.Inspect(game).Blockers.Any(b=>b.Contains(name)),"unknown/NR add-on not blocked: "+name);
   Check(!DlssCore.Inspect(game,true,false).Blockers.Any(b=>b.Contains(name)),"NR conflict blocks unrelated HDR operation");File.Delete(file);
  }
  string overlayHash=null;
  if(controlOverlay!=null){
   overlayHash=DlssCore.Hash(controlOverlay);File.Copy(controlOverlay,overlay);
   Check(!DlssCore.Inspect(game).Blockers.Any(),"verified control overlay still blocks installation");
   Check(DlssCore.Inspect(game).Notes.Any(n=>n.Contains(overlayName)),"preserved overlay absent from scan");
   string renderer=Path.Combine(game.Root,"renodx-dlss5.addon64");FakePe(renderer,false);
   Check(DlssCore.Inspect(game).Blockers.Any(b=>b.Contains("renodx-dlss5")),"UI overlay hid separate NR renderer");File.Delete(renderer);
   File.AppendAllText(overlay,"modified");Check(DlssCore.Inspect(game).Blockers.Any(b=>b.Contains(overlayName)),"modified overlay accepted");File.Copy(controlOverlay,overlay,true);
  }
  var external=new Game{Id="cleanup-fixture",Name="External installation",Root=Path.Combine(fixture,"external"),Exe=Path.Combine(fixture,"external","External.exe")};FakePe(external.Exe,false);
  foreach(string n in new[]{"renodx-dlss5.addon64","nvngx_dlssnr.dll","renodx-mfgunlock.addon64","renodx-hdr.addon64","nvngx_dlss.dll"})FakePe(Path.Combine(external.Root,n),false);
  FakePe(Path.Combine(external.Root,"dxgi.dll"),true);File.WriteAllText(Path.Combine(external.Root,"OptiScaler.ini"),"[DlssNr]\nEnabled=true\n");
  if(controlOverlay!=null)File.Copy(controlOverlay,Path.Combine(external.Root,overlayName));
  var cleanup=ComponentCleanup.Prepare(external,false);
  foreach(string n in new[]{"dxgi.dll","OptiScaler.ini","renodx-dlss5.addon64","nvngx_dlssnr.dll"})Check(cleanup.Changes.Any(c=>c.Name==n&&c.Delete),"external NR cleanup missed "+n);
  foreach(string n in new[]{overlayName,"renodx-mfgunlock.addon64","renodx-hdr.addon64","nvngx_dlss.dll"})Check(!cleanup.Changes.Any(c=>c.Name==n),"cleanup removes unrelated component "+n);
  string cleanupBackup=DlssCore.Apply(external,cleanup);
  Check(!File.Exists(Path.Combine(external.Root,"renodx-dlss5.addon64")),"external renderer not removed");
  Check(File.Exists(Path.Combine(external.Root,"renodx-mfgunlock.addon64")),"external MFG removed");
  if(controlOverlay!=null)Check(DlssCore.Hash(Path.Combine(external.Root,overlayName))==overlayHash,"cleanup changed UI overlay");
  DlssCore.Apply(external,DlssCore.Recovery(external,Path.Combine(cleanupBackup,"transaction.json")));
  Check(File.Exists(Path.Combine(external.Root,"renodx-dlss5.addon64"))&&DlssCore.IsOpti(Path.Combine(external.Root,"dxgi.dll")),"external cleanup not recoverable");
  string copyRoot=Path.Combine(fixture,"copy-audit");Directory.CreateDirectory(copyRoot);string copyA=Path.Combine(copyRoot,"a.dll"),copyB=Path.Combine(copyRoot,"b.dll");File.WriteAllText(copyA,"same");File.WriteAllText(copyB,"same");var copyFiles=new System.Collections.Generic.List<DlssLibrary>{new DlssLibrary{Path=copyA},new DlssLibrary{Path=copyB}};Check(DlssLibraries.CopyState(copyFiles)=="identical","identical content comparison");File.WriteAllText(copyB,"changed");Check(DlssLibraries.CopyState(copyFiles)=="different","changed content must not be classified identical");File.Delete(copyB);Check(DlssLibraries.CopyState(copyFiles)=="unreadable","missing copy must not look healthy");Check(File.ReadAllText(copyA)=="same","audit changed a file");
  string fgBase="[FrameGen]\nEnabled=true\nFGOutput=fsrfg\n[DLSSG]\nOverrideInterpolationCount=3\n";Check(FrameGeneration.Configure(fgBase,new DlssOptions())==fgBase,"preserve FG exact");var fgOpt=new DlssOptions{FrameMode="opti",FrameMultiplier=4};string fg=FrameGeneration.Configure(fgBase,fgOpt);Check(Core.Get(fg,"DLSSG","InterpolationCount")=="3"&&Core.Get(fg,"DLSSG","OverrideInterpolationCount")=="auto"&&Core.Get(fg,"FrameGen","FGOutput")=="dlssg","own FG count and native override reset");Reject(()=>FrameGeneration.ValidateChoice(fgOpt,40),"RTX40 MFG without unlock");FrameGeneration.ValidateChoice(fgOpt,50);fgOpt.FrameMode="native";fgOpt.Build="y4my4my4m";fgOpt.AdaMfg=true;FrameGeneration.ValidateChoice(fgOpt,40);fg=FrameGeneration.Configure(fgBase,fgOpt);Check(Core.Get(fg,"FrameGen","Enabled")=="false"&&Core.Get(fg,"DLSSG","AdaMfgUnlock")=="true"&&Core.Get(fg,"DLSSG","OverrideInterpolationCount")=="3","Ada native routing");Reject(()=>FrameGeneration.ValidateChoice(fgOpt,50),"Ada on RTX50");fgOpt.Build="wilsjo2";Reject(()=>FrameGeneration.Configure(fgBase,fgOpt),"Ada wrong build");fgOpt.Build="y4my4my4m";fgOpt.AdaMfg=false;fgOpt.FrameMode="off";fg=FrameGeneration.Configure(fg,fgOpt);Check(Core.Get(fg,"DLSSG","AdaMfgUnlock")=="false"&&Core.Get(fg,"DLSSG","OverrideInterpolationCount")=="auto","disable unlock and override");var fgSaved=Core.Json.Deserialize<DlssOptions>(Core.Json.Serialize(fgOpt));Check(fgSaved.FrameMode=="off"&&fgSaved.FrameMultiplier==4,"FG preferences roundtrip");Check(Core.Json.Deserialize<DlssOptions>("{\"Build\":\"dagherbou\"}").FrameMode=="keep","legacy preference preserves FG");
  Check(InjectionSetup.Target(game,"Game.exe")==game.Exe,"target exe validation");Reject(()=>InjectionSetup.Target(game,"../escape.exe"),"target escaped game");var launch=new Game{Id="123",Root=game.Root,Exe=game.Exe,EngineLabel="UNREAL ENGINE 5"};Core.Pref.InjectionProfiles["123"]=new InjectionProfile{Target="Game.exe",Api="dx12"};Check(InjectionSetup.LaunchArguments(launch)=="-applaunch 123 -dx12","API launch arguments");launch.EngineLabel="STEAM";Check(InjectionSetup.LaunchArguments(launch)=="-applaunch 123","non-Unreal launch flags must be preserved");Core.DetectOther(launch);Check(launch.Exe==game.Exe&&!launch.Confirmed,"non-Unreal library classification");InjectionSetup.RestoreTarget(launch);Check(launch.Exe==game.Exe,"target preference restoration");foreach(string key in InjectionSetup.MenuKeys.Skip(1)){Check(Core.Get(DlssCore.Config("",new DlssOptions{Key=key}),"Menu","ShortcutKey")==key,"OptiScaler key mapping");}

  Reject(()=>DlssCore.Safe(game.Root,"../outside"),"traversal accepted");Reject(()=>DlssCore.Safe(game.Root,"C:/outside"),"absolute accepted");Reject(()=>DlssCore.Safe(game.Root,"dir/CON.dll"),"device accepted");Reject(()=>DlssCore.Safe(game.Root,"file.dll:stream"),"ADS accepted");
  string package=Path.Combine(fixture,"package");FakePe(Path.Combine(package,"OptiScaler.dll"),true);Directory.CreateDirectory(Path.Combine(package,"OptiScaler"));File.WriteAllText(Path.Combine(package,"OptiScaler","backend.bin"),"data");File.WriteAllText(Path.Combine(package,"OptiScaler.ini"),"[DlssNr]\nEnabled=auto\n[FrameGen]\nEnabled=false\n");FakePe(Path.Combine(game.Root,"nvngx_dlssnr.dll"),false);File.WriteAllText(Path.Combine(game.Root,"version.dll"),"UE4SS preserve");File.WriteAllText(Path.Combine(game.Root,"OptiScaler.ini"),";preserve\n[FrameGen]\nEnabled=true\n[HDR]\nEnabled=true\n");File.SetAttributes(Path.Combine(game.Root,"OptiScaler.ini"),FileAttributes.ReadOnly);
  var options=new DlssOptions{Build="wilsjo2",Scale=75,Placement=1,Key="0x4B"};var plan=DlssCore.Prepare(game,options,package,"test-release");DlssCore.Apply(game,plan);Check(DlssCore.Inspect(game).Managed,"not managed");string ini=File.ReadAllText(Path.Combine(game.Root,"OptiScaler.ini"));Check(Core.Get(ini,"DlssNr","RunBeforeSR")=="true"&&Core.Get(ini,"DlssNr","WorkingScale")=="0.75","options conversion");Check(Core.Get(ini,"Menu","ShortcutKey")=="0x4B","captured key not saved");Check(Core.Get(ini,"FrameGen","Enabled")=="true"&&Core.Get(ini,"HDR","Enabled")=="true","existing FG/HDR changed");Check(File.ReadAllText(Path.Combine(game.Root,"version.dll"))=="UE4SS preserve","UE4SS modified");
  var appliedScan=DlssCore.Inspect(game);Check(DlssUi.AppliedChoice(appliedScan,"Posizione del passaggio · wilsjo2",2,""),"applied placement not gold");Check(!DlssUi.AppliedChoice(appliedScan,"Posizione del passaggio · wilsjo2",1,""),"pending placement shown applied");Check(!DlssUi.AppliedChoice(appliedScan,"Posizione del passaggio · wilsjo2",0,""),"keep shown applied");Check(DlssUi.AppliedChoice(appliedScan,"Passaggi · wilsjo2",0,""),"applied passes not gold");Check(!DlssUi.AppliedChoice(new DlssScan(),"Stile",0,""),"absent component shown applied");
  options.Scale=50;var second=DlssCore.Prepare(game,options,null,"settings");DlssCore.Apply(game,second);Check(DlssCore.ReadManifest(game.Root).Files.Count==3,"baseline duplicates");var undo=DlssCore.PrepareUninstall(game);DlssCore.Apply(game,undo);Check(!File.Exists(Path.Combine(game.Root,"dxgi.dll")),"new proxy not removed");Check(File.ReadAllText(Path.Combine(game.Root,"OptiScaler.ini")).Contains(";preserve"),"original ini not restored");Check((File.GetAttributes(Path.Combine(game.Root,"OptiScaler.ini"))&FileAttributes.ReadOnly)!=0,"readonly lost");
  plan=DlssCore.Prepare(game,options,package,"test");File.WriteAllText(Path.Combine(game.Root,"dxgi.dll"),"new external mod");Reject(()=>DlssCore.Apply(game,plan),"stale preview accepted");Check(File.ReadAllText(Path.Combine(game.Root,"dxgi.dll"))=="new external mod","stale file overwritten");File.Delete(Path.Combine(game.Root,"dxgi.dll"));
  FakePe(Path.Combine(game.Root,"dxgi.dll"),true);File.WriteAllText(Path.Combine(game.Root,"dlss5-autopilot.json"),"{\"path\":\"optiscaler\",\"opti_build\":\"wilsjo2\",\"files\":[\"dxgi.dll\",\"OptiScaler.ini\"]}");File.WriteAllText(Path.Combine(game.Root,"OptiScaler.ini.dlss5-autopilot-backup"),"original-settings");Check(DlssCore.Inspect(game).Autopilot,"foreign not detected");undo=DlssCore.PrepareUninstall(game);string recovery=DlssCore.Apply(game,undo);Check(File.Exists(Path.Combine(recovery,"dxgi.dll"))&&!File.Exists(Path.Combine(game.Root,"dxgi.dll")),"foreign removal not recoverable");Check(File.ReadAllText(Path.Combine(game.Root,"OptiScaler.ini"))=="original-settings","foreign original not restored");
  var rescue=DlssCore.Recovery(game,Path.Combine(recovery,"transaction.json"));DlssCore.Apply(game,rescue);Check(DlssCore.IsOpti(Path.Combine(game.Root,"dxgi.dll"))&&File.Exists(Path.Combine(game.Root,"dlss5-autopilot.json")),"foreign uninstall cannot be undone");
  Check(File.Exists(Path.Combine(game.Root,"OptiScaler.ini.dlss5-autopilot-backup")),"recovery lost external backup");
  string alternate=Path.Combine(game.Root,"OptiScaler.ini.dlss5-installer-backup");File.WriteAllText(alternate,"different original");Reject(()=>DlssCore.PrepareUninstall(game,true),"conflicting originals accepted");File.Delete(alternate);
  var overForeign=DlssCore.Prepare(game,options,package,"over-autopilot");DlssCore.Apply(game,overForeign);
  var combined=DlssCore.PrepareUninstall(game,true);Check(combined.Changes.Count(c=>c.Name=="dxgi.dll")==1,"duplicate layered loader operation");
  string combinedRecovery=DlssCore.Apply(game,combined);Check(!File.Exists(Path.Combine(game.Root,"dxgi.dll"))&&!File.Exists(Path.Combine(game.Root,"dlss5-autopilot.json"))&&!File.Exists(Path.Combine(game.Root,DlssCore.Marker)),"layered uninstall reinstated Autopilot");
  Check(File.ReadAllText(Path.Combine(game.Root,"OptiScaler.ini"))=="original-settings","layered original not restored");Check(!File.Exists(Path.Combine(game.Root,"OptiScaler.ini.dlss5-autopilot-backup")),"consumed backup remained");Check(File.ReadAllText(Path.Combine(game.Root,"version.dll"))=="UE4SS preserve","layered uninstall altered other component");
  DlssCore.Apply(game,DlssCore.Recovery(game,Path.Combine(combinedRecovery,"transaction.json")));Check(DlssCore.Inspect(game).Managed&&File.Exists(Path.Combine(game.Root,"dlss5-autopilot.json")),"layered recovery incomplete");DlssCore.Apply(game,DlssCore.PrepareUninstall(game));
  File.Delete(Path.Combine(game.Root,"dlss5-autopilot.json"));File.Delete(Path.Combine(game.Root,"dxgi.dll"));
  var staleSource=DlssCore.Prepare(game,options,package,"source test");File.AppendAllText(Path.Combine(package,"OptiScaler","backend.bin"),"changed");Reject(()=>DlssCore.Apply(game,staleSource),"changed source accepted");Check(!File.Exists(Path.Combine(game.Root,"dxgi.dll")),"changed source caused partial write");
  var lockPlan=DlssCore.Prepare(game,options,package,"locked");using(var locked=new FileStream(Path.Combine(game.Root,"version.dll"),FileMode.Open,FileAccess.Read,FileShare.None)){lockPlan.Changes.Add(new DlssChange{Name="version.dll",Expected=DlssCore.Hash(Path.Combine(package,"OptiScaler.dll")),Bytes=new byte[]{1}});Reject(()=>DlssCore.Apply(game,lockPlan),"locked file accepted");}Check(!File.Exists(Path.Combine(game.Root,"dxgi.dll")),"locked preflight caused partial write");
  File.WriteAllText(Path.Combine(game.Root,"dlss5-autopilot.json"),"{\"path\":\"optiscaler\",\"files\":[\"Game.exe\"]}");Reject(()=>DlssCore.PrepareUninstall(game),"foreign game executable accepted");
  string release="[{\"tag_name\":\"wrong\",\"assets\":[{\"name\":\"display-filter.zip\"}]},{\"tag_name\":\"v0.8.5\",\"assets\":[{\"name\":\"OptiScaler-rtx40-mfg.zip\"},{\"name\":\"OptiScaler.zip\",\"browser_download_url\":\"https://github.com/wilsjo2/OptiScaler-DLSSNR-PreSR-Multipass/releases/download/v0.8.5/OptiScaler.zip\"}]}]";
  Check(DlssCore.PickRelease(release,DlssBuild.All[1]).Tag=="v0.8.5","wrong release/variant selected");Reject(()=>DlssLibraries.Validate(game.Exe,"nvngx_dlss.dll"),"invalid NVIDIA DLL accepted");
  var h=new DlssHardware{Series=40,Driver="615.00"};Reject(()=>h.Validate(40,"missing"),"old driver accepted");h.Driver="616.92";h.Validate(40,"missing");Reject(()=>h.Validate(50,"missing"),"GPU mismatch accepted");
  if(controlOverlay!=null)Check(DlssCore.Hash(overlay)==overlayHash&&DlssCore.Hash(controlOverlay)==overlayHash,"install/update/uninstall/recovery modified control overlay");
  File.WriteAllText(Path.Combine(folder,"tests.txt"),"PASS: third-party NR cleanup without manifest and recovery; preserved separate MFG/HDR/native DLSS; unknown and modified overlays blocked; separate NR renderer detected; verified overlay preserved when supplied; confined paths/ADS/device names; x64 fixtures; install/update and original baseline restore; readonly; preserved HDR/FG/UE4SS/ReShade; stale preview rejection; external Autopilot detection and reversible uninstall; original backup restore; protected game executable rejection; release filtering; invalid component rejection; GPU/driver checks; source mutation and locked-file rejection; recovery of foreign removal. No real game files changed.");
 }
 public static void Package(string archive,string folder){Directory.CreateDirectory(folder);string package=DlssCore.Unpack(archive,Path.Combine(folder,"extracted"));Core.Data=Path.Combine(folder,"data");var g=new Game{Id="test",Name="Package test",Root=Path.Combine(folder,"game"),Exe=Path.Combine(folder,"game","Test.exe")};FakePe(g.Exe,false);FakePe(Path.Combine(g.Root,"nvngx_dlssnr.dll"),false);var plan=DlssCore.Prepare(g,new DlssOptions(),package,"archive test");Check(plan.Changes.Any(c=>c.Name=="dxgi.dll"),"main DLL missing");Check(plan.Changes.Any(c=>c.Name.StartsWith("OptiScaler/")),"backend missing");Check(plan.Changes.All(c=>!c.Name.EndsWith(".exe")&&!c.Name.EndsWith(".bat")),"executable installer copied");File.WriteAllText(Path.Combine(folder,"package-test.txt"),"PASS: archive listing/path validation, complete x64 package recognition, installation plan with "+plan.Changes.Count+" files; no package code executed.\n"+plan.ToString());}
 public static void NativeTest(string source,string folder){Directory.CreateDirectory(folder);Core.Data=Path.Combine(folder,"data");Directory.CreateDirectory(Core.Data);var g=new Game{Id="native-test",Name="DLL test",Root=Path.Combine(folder,"game"),Exe=Path.Combine(folder,"game","Game.exe")};FakePe(g.Exe,false);string dest=Path.Combine(g.Root,"Engine","Plugins","nvngx_dlss.dll");FakePe(dest,false);string original=DlssCore.Hash(dest);var target=DlssLibraries.Scan(g).Single();Reject(()=>DlssLibraries.Validate(source,"nvngx_dlssd.dll"),"SR accepted as RR");var plan=DlssLibraries.Prepare(g,target,source);DlssCore.Apply(g,plan);Check(DlssCore.Hash(dest)==DlssCore.Hash(source),"native DLL swap failed");Reject(()=>DlssLibraries.Prepare(g,target,source),"identical swap accepted");var restore=DlssLibraries.Restore(g);DlssCore.Apply(g,restore);Check(DlssCore.Hash(dest)==original,"native baseline not restored");File.WriteAllText(Path.Combine(folder,"native-test.txt"),"PASS: signed NVIDIA SR validation; wrong component rejected; nested game DLL swap; identical update rejected; original baseline restored. Only fixture modified.");}
 public static void NativeInspect(string root,string report){var g=new Game{Root=root};var files=DlssLibraries.Scan(g);var text=new System.Text.StringBuilder();foreach(var f in files){text.AppendLine(f.ToString());try{DlssLibraries.Validate(f.Path,f.File);text.AppendLine("Signature and component: PASS");}catch(Exception e){text.AppendLine("Signature validation: "+e.Message);}}File.WriteAllText(report,text.ToString());}
 public static void Scan(string exe,string output){var g=new Game{Id="test",Name="Gioco",Root=Path.GetDirectoryName(exe),Exe=exe};File.WriteAllText(output,DlssCore.Inspect(g).ToString());}
 public static void Preview(string exe,string output){new Application();Window owner;using(var s=System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream("Main.xaml"))owner=(Window)System.Windows.Markup.XamlReader.Load(s);owner.Show();var g=new Game{Id="5184670",Name="Clive Barker’s Hellraiser: Revival Demo",Root=Path.GetDirectoryName(exe),Exe=exe};var ui=new DlssUi();var window=ui.Create(owner,g);window.Show();window.UpdateLayout();var b=new RenderTargetBitmap((int)window.ActualWidth,(int)window.ActualHeight,96,96,PixelFormats.Pbgra32);b.Render(window);var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(b));using(var f=File.Create(output))encoder.Save(f);window.Close();owner.Close();}
}
}
