using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
namespace HdrPilot {
public sealed class DlssUi {
 public FrameworkElement EmbeddedContent; public bool IsBusy {get{return busy;}} Window window;Game game;DlssScan scan;DlssHardware hardware;ComboBox gpu;ComboBox builds,styles,placement,passes,proxy,fgMode,fgCount;CheckBox adaMfg;TextBlock fgInfo;Slider scale;TextBox strength;CheckBox enabled;TextBlock status,description,packageLabel,runtimeLabel,installedLabel;Button install,save,remove;StackPanel controls;string package="",runtime="",packageBuild="";string menuKey="keep";Button keyCapture;bool busy,rememberReady;System.Windows.Threading.DispatcherTimer rememberTimer;
 System.Collections.Generic.List<Action> choiceRefresh=new System.Collections.Generic.List<Action>();
 static Brush Gold=new SolidColorBrush(Color.FromRgb(230,172,80));
 static TextBlock Text(string text,int size=12){return Dialogs.Text(text,Math.Max(14,size));}
 static string ChoiceHint(string label,int index,object value,string fallback){
  var build=value as DlssBuild;if(build!=null)return build.Description;
  if(label.StartsWith("Posizione"))return new[]{"Mantiene la posizione già impostata. Se manca, usa il comportamento predefinito della build.","Il modello modifica l’immagine dopo che è stata ingrandita alla risoluzione di uscita. Elabora in genere più pixel e può richiedere più tempo GPU.","Il modello modifica l’immagine prima che venga ingrandita. Con un ingresso a risoluzione ridotta elabora meno pixel; resa e prestazioni vanno confrontate nel gioco. In DLAA il vantaggio può ridursi."}[index];
  if(label.StartsWith("Passaggi"))return new[]{"Esegue il modello una sola volta per immagine: il punto di partenza consigliato per contenere il carico GPU.","Esegue due passaggi del modello. Può trasformare maggiormente l’immagine, aumentando il costo GPU; non genera fotogrammi intermedi.","Esegue tre passaggi del modello. È l’opzione più impegnativa delle tre; può accentuare anche artefatti e alterazioni. Non equivale a MFG 3×."}[index];
  if(label=="Stile")return new[]{"Usa il profilo predefinito della build, senza scegliere un’impostazione artistica specifica.","Richiede il profilo Standard del modello. Il risultato dipende dal runtime e dal gioco; non è una regolazione di risoluzione.","Richiede il profilo Naturale del modello. Confronta la stessa scena: il nome non garantisce colori più fedeli o meno artefatti.","Richiede il profilo Cinematico del modello. Cambia la scelta artistica del modello, non il formato HDR o il numero di FPS."}[index];
  if(label=="Chi genera i fotogrammi?")return new[]{"Lascia invariata la configurazione FG attuale. Non annulla modifiche che hai già applicato.","Fa generare i fotogrammi a OptiScaler partendo dall’upscaler. Richiede i componenti NVIDIA FG / Streamline compatibili già installati.","Richiede il moltiplicatore alla FG nativa: devi attivare DLSS Frame Generation nel menu del gioco. Disabilita la generazione propria di OptiScaler per evitare due percorsi concorrenti.","Spegne FG e override gestiti da OptiScaler. La Frame Generation nativa si disattiva nel menu del gioco."}[index];
  if(label=="Moltiplicatore richiesto")return (index+2)+"×: per ogni fotogramma reale richiede "+(index+1)+" fotogramm"+(index==0?"a generato":"i generati")+". Non moltiplica la reattività. I valori superiori a 2× richiedono RTX 5000 oppure lo sblocco Ada sperimentale della build y4my4my4m con FG del gioco; restano subordinati al runtime.";
  if(label=="DLL di caricamento")return index==0?"Mantiene il loader OptiScaler riconosciuto, oppure cerca un nome libero. Scelta consigliata per ridurre il rischio di conflitti.":"Richiede di caricare OptiScaler come "+value+" accanto all’eseguibile. Funziona solo se il gioco carica questo nome. Non migliora la qualità dell’immagine; l’app non sovrascrive una DLL sconosciuta o appartenente ad altre mod.";
  if(label=="Scheda video")return index==0?"Se la GPU non viene rilevata, indica la serie effettivamente presente. La selezione non aggiunge funzionalità hardware.":index==1?"Serie RTX 4000 / Ada. Neural Rendering richiede un runtime di compatibilità; FG standard è 2×, MFG superiore è un percorso sperimentale separato.":"Serie RTX 5000 / Blackwell. Usa il runtime NR appropriato; il supporto MFG dipende anche dal gioco e dai componenti caricati.";
  return fallback;
 }
 ComboBox Choice(StackPanel p,string label,string help,object items){AddLabel(p,label,help);var values=((System.Collections.IEnumerable)items).Cast<object>().ToArray();var c=new ComboBox{ItemsSource=values,Visibility=Visibility.Collapsed};p.Children.Add(c);var row=new WrapPanel{Margin=new Thickness(0,0,0,4)};p.Children.Add(row);var hint=Text("",13);hint.Margin=new Thickness(0,0,0,10);bool hasSeparateDescription=values.Any(v=>v is DlssBuild)||label=="Chi genera i fotogrammi?";if(!hasSeparateDescription)p.Children.Add(hint);for(int i=0;i<values.Length;i++){int index=i;var button=HdrChoices.Option(Convert.ToString(values[i]));string explanation=ChoiceHint(label,index,values[i],help);HdrChoices.Help(button,explanation);System.Windows.Automation.AutomationProperties.SetHelpText(button,explanation);button.SetBinding(System.Windows.Controls.Button.IsEnabledProperty,new System.Windows.Data.Binding("IsEnabled"){Source=c});button.Click+=(sender,e)=>c.SelectedIndex=index;row.Children.Add(button);}Action update=()=>{for(int i=0;i<row.Children.Count;i++)((Button)row.Children[i]).Style=window.TryFindResource((values[i] is DlssBuild?VerifiedBuild(((DlssBuild)values[i]).Id):AppliedChoice(scan,label,i,values[i]))?(object)"Installed":i==c.SelectedIndex?(object)"Primary":typeof(Button)) as Style;hint.Text=(c.IsEnabled?"":label.Contains("wilsjo2")?"Disponibile solo con la build wilsjo2. ":"Non attivo con la configurazione selezionata. ")+(c.SelectedIndex>=0?ChoiceHint(label,c.SelectedIndex,values[c.SelectedIndex],help):"");};choiceRefresh.Add(update);c.SelectionChanged+=(sender,e)=>update();c.IsEnabledChanged+=(sender,e)=>update();return c;}

 StackPanel Cell(Grid grid,int index){var p=new StackPanel{Margin=new Thickness(index%2==0?0:14,0,index%2==0?14:0,10)};while(grid.RowDefinitions.Count<=index/2)grid.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});Grid.SetRow(p,index/2);Grid.SetColumn(p,index%2);grid.Children.Add(p);return p;}
 TextBox Number(StackPanel p,string label,string help,string initial){AddLabel(p,label,help);var row=new StackPanel{Orientation=Orientation.Horizontal,Margin=new Thickness(0,0,0,6)};var n=new TextBox{Text=initial,Width=70,TextAlignment=TextAlignment.Center};var minus=new Button{Content="−",Width=34,Margin=new Thickness(0,0,6,0)};var plus=new Button{Content="+",Width=34,Margin=new Thickness(6,0,0,0)};minus.Click+=(s,e)=>{int v;if(Int32.TryParse(n.Text,out v))n.Text=Math.Max(0,v-5).ToString();};plus.Click+=(s,e)=>{int v;if(Int32.TryParse(n.Text,out v))n.Text=Math.Min(100,v+5).ToString();};row.Children.Add(minus);row.Children.Add(n);row.Children.Add(plus);p.Children.Add(row);return n;}
 void AddLabel(StackPanel p,string label,string help){var row=new DockPanel{Margin=new Thickness(0,5,0,4)};var button=new Button{Content="?",Width=25,Height=23,Padding=new Thickness(0),ToolTip=new ToolTip{Content=new TextBlock{Text=help,TextWrapping=TextWrapping.Wrap,MaxWidth=440,FontSize=14},Padding=new Thickness(12)}};HdrChoices.Help(button,help);DockPanel.SetDock(button,Dock.Right);button.Click+=(s,e)=>Dialogs.Notice(window,label,help,null).ShowDialog();row.Children.Add(button);var t=Text(label,12);t.Foreground=Brushes.White;t.Margin=new Thickness(0,2,8,3);row.Children.Add(t);p.Children.Add(row);}
 Button Button(Panel p,string label,Action action,bool primary=false){var b=new Button{Content=label,Margin=new Thickness(0,0,8,8),Padding=new Thickness(12,9,12,9)};if(primary)b.Style=window.TryFindResource("Primary") as Style;else if(label.StartsWith("Ripristina")||label.StartsWith("Disinstalla"))b.Style=window.TryFindResource("RestoreAction") as Style;b.Click+=(s,e)=>{try{action();}catch(Exception ex){Error(ex);}};p.Children.Add(b);return b;}
 void Error(Exception ex){ActivityLog.Write("ERRORE DLSS · "+ex.Message);status.Text=ex.Message;Dialogs.Notice(window,"DLSS · operazione non completata",ex.Message,null).ShowDialog();}
 public static void Show(Window owner,Game game){var ui=new DlssUi();ui.Create(owner,game);ui.window.ShowDialog();}
 public Window Create(Window owner,Game g,bool embedded=false){game=g;scan=DlssCore.Inspect(g);hardware=DlssHardware.Detect();StackPanel unused;window=Dialogs.Create(owner,"DLSS 5 / OptiScaler",out unused);window.FontSize=14;window.Width=Math.Min(1080,SystemParameters.WorkArea.Width-40);window.Height=Math.Min(840,SystemParameters.WorkArea.Height-40);window.SizeToContent=SizeToContent.Manual;window.MaxHeight=SystemParameters.WorkArea.Height-40;
  var outer=new Grid();outer.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});outer.RowDefinitions.Add(new RowDefinition());outer.RowDefinitions.Add(new RowDefinition{Height=GridLength.Auto});var border=(Border)window.Content;border.Child=outer;
  var heading=new DockPanel();var close=new Button{Content="×",Padding=new Thickness(12,5,12,5),HorizontalAlignment=HorizontalAlignment.Right};DockPanel.SetDock(close,Dock.Right);close.Click+=(s,e)=>window.Close();if(!embedded)heading.Children.Add(close);var title=Text("DLSS 5 / OptiScaler",20);title.Margin=new Thickness(0,0,0,4);title.Foreground=Gold;heading.Children.Add(title);outer.Children.Add(heading);
  var scroll=new ScrollViewer{VerticalScrollBarVisibility=ScrollBarVisibility.Auto,Margin=new Thickness(0,8,0,12)};Grid.SetRow(scroll,1);outer.Children.Add(scroll);controls=new StackPanel();scroll.Content=controls;var provider=Text("Iniezione tramite OptiScaler · Giallo: installato / applicato · Blu: scelta da applicare",13);provider.Foreground=Gold;provider.Margin=new Thickness(0,0,0,5);controls.Children.Add(provider);var name=Text(g.Name,14);name.Margin=new Thickness(0,0,0,5);name.Foreground=Brushes.White;controls.Children.Add(name);
  var stateBox=new Border{Background=new SolidColorBrush(Color.FromArgb(18,230,172,80)),BorderBrush=Gold,BorderThickness=new Thickness(3,0,0,0),Padding=new Thickness(12,9,12,9),Margin=new Thickness(0,0,0,10)};var stateRow=new DockPanel();var stateIcon=Text(scan.Blockers.Count>0?"⚠":"ⓘ",17);stateIcon.Foreground=Gold;stateIcon.Margin=new Thickness(0,0,12,0);DockPanel.SetDock(stateIcon,Dock.Left);stateRow.Children.Add(stateIcon);status=Text(Summary(scan),14);status.Margin=new Thickness(0);stateRow.Children.Add(status);stateBox.Child=stateRow;controls.Children.Add(stateBox);

  var columns=new Grid();columns.ColumnDefinitions.Add(new ColumnDefinition());columns.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(28)});columns.ColumnDefinitions.Add(new ColumnDefinition());controls.Children.Add(columns);var left=new StackPanel();var right=new StackPanel();Grid.SetColumn(right,2);columns.Children.Add(left);columns.Children.Add(right);
  var installedTitle=Text("COMPONENTI INSTALLATI",14);installedTitle.Foreground=Gold;right.Children.Add(installedTitle);installedLabel=Text("",14);right.Children.Add(installedLabel);RefreshInstalled();Button(right,"Controlla file e percorsi",()=>{RefreshInstalled();var detail=installedLabel.ToolTip as TextBlock;Dialogs.Notice(window,"File installati",detail==null?installedLabel.Text:detail.Text,null).ShowDialog();});
  var dllActions=new System.Windows.Controls.Primitives.UniformGrid{Columns=2,Margin=new Thickness(0,8,0,8)};right.Children.Add(dllActions);Button(dllActions,"Super Resolution",()=>Libraries("nvngx_dlss.dll"));Button(dllActions,"Ray Reconstruction",()=>Libraries("nvngx_dlssd.dll"));Button(dllActions,"Frame Generation",()=>Libraries("nvngx_dlssg.dll"));
  var advanced=new StackPanel{Margin=new Thickness(0,12,0,8)};var setupTitle=Text("Personalizza",16);setupTitle.Foreground=Gold;advanced.Children.Add(setupTitle);var adv=new StackPanel{Margin=new Thickness(0,12,0,0)};advanced.Children.Add(adv);
  right.Children.Add(Text(hardware.Name+" · driver "+hardware.Driver,14));
  gpu=Choice(hardware.Series==0?right:adv,"Scheda video",hardware.Advice(),new[]{"Seleziona GPU","NVIDIA RTX 4000","NVIDIA RTX 5000"});gpu.SelectedIndex=hardware.Series==40?1:hardware.Series==50?2:0;
  builds=Choice(left,"Versione di OptiScaler","Tre fork di OptiScaler della community, non versioni ufficiali NVIDIA.\n\n"+String.Join("\n\n",DlssBuild.All.Select(b=>b.Name+"\n"+b.Description)),DlssBuild.All);description=Text("",14);description.Margin=new Thickness(0,2,0,12);left.Children.Add(description);
  enabled=new CheckBox{Content="Abilita Neural Rendering (DLSS 5)",IsChecked=Core.Get(scan.Ini,"DlssNr","Enabled")!="false",Margin=new Thickness(0,4,0,14)};left.Children.Add(enabled);
  AddLabel(left,"Qualità di elaborazione","La percentuale si applica a larghezza e altezza dell’immagine elaborata dal modello, non alla risoluzione del monitor.");
  var scaleValue=Text("",18);scaleValue.Foreground=Gold;left.Children.Add(scaleValue);
  scale=new Slider{Minimum=25,Maximum=100,TickFrequency=1,IsSnapToTickEnabled=true,SmallChange=1,LargeChange=5,IsMoveToPointEnabled=true,Height=32,Margin=new Thickness(0,0,0,8),Foreground=Gold,Value=Math.Max(25,Percent(scan.Ini,"WorkingScale",75))};left.Children.Add(scale);
  Action scaleInfo=()=>scaleValue.Text=((int)scale.Value)+"% · "+(scale.Value==100?"massimo dettaglio":scale.Value>=75?"equilibrio qualità / prestazioni":"minor carico sul modello");scale.ValueChanged+=(s,e)=>scaleInfo();scaleInfo();
  left.Children.Add(Text("Più basso: meno carico. Più alto: più dettaglio.\nParti da 75%. Non cambia la risoluzione dello schermo.",14));
  styles=Choice(left,"Stile","Auto conserva il comportamento predefinito della build. Gli altri stili cambiano il risultato artistico.",new[]{"Automatico","Standard","Naturale","Cinematico"});int style;styles.SelectedIndex=Int32.TryParse(Core.Get(scan.Ini,"DlssNr","Style"),out style)?Math.Max(0,Math.Min(3,style+1)):0;
  runtimeLabel=Text("",11);right.Children.Add(runtimeLabel);Button(dllActions,"Neural Rendering",()=>NrModels.Show(window,game,gpu.SelectedIndex==1?40:gpu.SelectedIndex==2?50:0,()=>{scan=DlssCore.Inspect(game);status.Text=Summary(scan);RefreshInstalled();}));

  var fgTitle=Text("Fluidità / Frame Generation",16);fgTitle.Foreground=Gold;fgTitle.Margin=new Thickness(0,14,0,4);right.Children.Add(fgTitle);
  fgMode=Choice(right,"Chi genera i fotogrammi?","Conserva non cambia i parametri FG. OptiScaler usa l’upscaler e lo stack NVIDIA FG già installato. FG del gioco richiede di attivare DLSS FG nel menu del gioco e ne richiede il moltiplicatore tramite Streamline. Disattiva OptiScaler non spegne FG nativa del gioco.",new[]{"Conserva","OptiScaler","FG del gioco","Disattiva OptiScaler"});fgMode.SelectedIndex=0;
  fgCount=Choice(right,"Moltiplicatore richiesto","2× = un fotogramma reale più uno generato. 3× ne genera due, fino a 6× con cinque generati. Non moltiplica la reattività dei comandi. Parti da 2×; GPU, runtime e gioco devono supportare il valore scelto.",new[]{"2×","3×","4×","5×","6×"});fgCount.SelectedIndex=0;
  adaMfg=new CheckBox{Content="MFG RTX 4000 · sperimentale",Margin=new Thickness(0,2,0,8)};right.Children.Add(adaMfg);adaMfg.ToolTip="Solo y4my4my4m con FG del gioco. Sblocco non ufficiale NVIDIA: la cadenza può essere irregolare e un aggiornamento driver può renderlo inefficace.";
  fgInfo=Text("",13);right.Children.Add(fgInfo);Action refreshFg=()=>{bool native=fgMode.SelectedIndex==2;adaMfg.IsEnabled=native&&hardware.Series==40&&Selected().Id=="y4my4my4m";if(!adaMfg.IsEnabled)adaMfg.IsChecked=false;fgCount.IsEnabled=fgMode.SelectedIndex==1||native;var parent=(Panel)fgCount.Parent;var row=(WrapPanel)parent.Children[parent.Children.IndexOf(fgCount)+1];bool multi=hardware.Series==50||(adaMfg.IsChecked==true&&adaMfg.IsEnabled);for(int i=0;i<row.Children.Count;i++)((Button)row.Children[i]).IsEnabled=fgCount.IsEnabled&&(i==0||multi);if(!multi)fgCount.SelectedIndex=0;fgInfo.Text=fgMode.SelectedIndex==0?"Mantiene la generazione fotogrammi già configurata.":fgMode.SelectedIndex==3?"Disattiva la generazione e gli override di OptiScaler. FG nativa si gestisce nel gioco.":(native?"Attiva DLSS Frame Generation nel gioco. ":"Richiede i file NVIDIA FG / Streamline già installati. ")+(adaMfg.IsChecked==true?"RTX 4000: percorso sperimentale, cadenza non garantita. ":hardware.Series==40?"RTX 4000: FG standard limitata a 2×. ":"Il valore massimo dipende dal runtime e dal gioco. ")+"Riavvia dopo l’applicazione. Il valore richiesto non è una misura degli FPS.";};
  fgMode.SelectionChanged+=(s,e)=>refreshFg();builds.SelectionChanged+=(s,e)=>refreshFg();adaMfg.Checked+=(s,e)=>refreshFg();adaMfg.Unchecked+=(s,e)=>refreshFg();refreshFg();
  packageLabel=Text("La build viene scaricata dal repository dell’autore durante l’installazione. Nessun download anticipato delle altre build.",11);right.Children.Add(packageLabel);var packageButtons=new WrapPanel();Button(packageButtons,"Pagina della build",()=>Open("https://github.com/"+Selected().Repo+"/releases"));
  controls.Children.Add(advanced);var choices=new Grid();choices.ColumnDefinitions.Add(new ColumnDefinition());choices.ColumnDefinitions.Add(new ColumnDefinition());adv.Children.Add(choices);
  placement=Choice(Cell(choices,0),"Posizione del passaggio · wilsjo2","Prima dell’upscaling può ridurre il costo, ma il risultato dipende dal gioco. La scelta Prima/Dopo usa il percorso diretto: disattiva applicazione sull’immagine finale e trasferimenti differiti. Conserva non modifica la scelta esistente.",new[]{"Conserva / predefinita","Dopo l’upscaling","Prima dell’upscaling"});string before=Core.Get(scan.Ini,"DlssNr","RunBeforeSR");placement.SelectedIndex=before=="true"?2:before=="false"?1:0;
  passes=Choice(Cell(choices,1),"Passaggi · wilsjo2","Consigliato 1. Due o tre passaggi aumentano costo, memoria e trasformazione dell’immagine.",new[]{"1 · consigliato","2 · sperimentale","3 · sperimentale"});int pass;passes.SelectedIndex=Int32.TryParse(Core.Get(scan.Ini,"DlssNr","Passes"),out pass)?Math.Max(0,Math.Min(2,pass-1)):0;
  strength=Number(Cell(choices,2),"Intensità del risultato (%)","100% usa il risultato del modello; 0% conserva il risultato di partenza. Non è un controllo HDR. Intervallo 0–100.",Percent(scan.Ini,"TransferStrength",100).ToString());
  var keyCell=Cell(choices,3);AddLabel(keyCell,"Tasto del menu OptiScaler","Premi un tasto sulla tastiera per assegnarlo. OptiScaler usa un tasto singolo; questa scelta è separata dall’overlay HDR. Salva impostazioni applica la scelta al gioco.");menuKey=Core.Get(scan.Ini,"Menu","ShortcutKey")??"keep";if(!InjectionSetup.ValidMenuKey(menuKey))menuKey="keep";var keyRow=new WrapPanel();keyCell.Children.Add(keyRow);keyCapture=Button(keyRow,"Premi un tasto… · "+InjectionSetup.CapturedKeyLabel(menuKey),()=>InjectionSetup.CaptureMenuKey(window,value=>{menuKey=value;keyCapture.Content="Premi un tasto… · "+InjectionSetup.CapturedKeyLabel(menuKey);Remember();}));Button(keyRow,"Conserva",()=>{menuKey="keep";keyCapture.Content="Premi un tasto… · Conserva";Remember();});

  proxy=Choice(Cell(choices,4),"DLL di caricamento","Automatico conserva il loader OptiScaler rilevato, oppure sceglie un nome libero. Non sovrascrive il loader di ReShade o UE4SS.",new[]{"Automatico","dxgi.dll","winmm.dll","version.dll","dbghelp.dll","d3d12.dll","wininet.dll","winhttp.dll"});proxy.SelectedIndex=0;
  var toolsExpander=new StackPanel{Margin=new Thickness(0,6,0,0)};var toolsPanel=new StackPanel{Margin=new Thickness(0,10,0,0)};toolsExpander.Children.Add(toolsPanel);adv.Children.Add(toolsExpander);AddLabel(toolsPanel,"Compatibilità e componenti","Frame Generation e HDR restano gestiti dalle loro impostazioni. ReShade può essere caricato da OptiScaler; non usare due iniettori NR contemporaneamente. "+hardware.Advice());var imports=new WrapPanel();toolsPanel.Children.Add(imports);Button(imports,"Importa modello…",ChooseRuntime);Button(imports,"Pacchetto locale…",ChoosePackage);Button(right,"Repository della build OptiScaler",()=>Open("https://github.com/"+Selected().Repo+"/releases"));
  var utilities=new WrapPanel();toolsPanel.Children.Add(utilities);Button(utilities,"Recupera operazione…",()=>{var pick=new Microsoft.Win32.OpenFileDialog{Filter="Registro recupero|transaction.json",InitialDirectory=Path.Combine(Core.Data,"dlss-recovery")};if(pick.ShowDialog(window)==true)Review(DlssCore.Recovery(game,pick.FileName));});Button(utilities,"Driver NVIDIA",()=>Open("https://www.nvidia.com/Download/index.aspx"));Button(utilities,"Diagnostica DLSS",()=>ShowReport("Diagnostica DLSS",DlssCore.Diagnose(game)));Button(utilities,"Cartella del gioco",()=>Open(scan.Folder));if(game.IsXbox)Button(utilities,"Riparazione Xbox",()=>ShowReport("Riparazione Xbox","Apri l’app Xbox, seleziona questo gioco e usa Gestisci → File → Verifica e ripara, se disponibile. Non elimina necessariamente file aggiunti dalle mod."));else Button(utilities,"Verifica integrità Steam",()=>Open("steam://validate/"+game.Id));
  var footer=new StackPanel();Grid.SetRow(footer,2);outer.Children.Add(footer);var actions=new WrapPanel();footer.Children.Add(actions);install=Button(actions,"Installa OptiScaler",()=>PrepareInstall(),true);save=Button(actions,"Applica impostazioni",SaveExisting);remove=Button(actions,"Disinstalla / ripristina",()=>Review(DlssCore.PrepareUninstall(game,true)));UpdateRemove();Button(actions,"Pulisci Neural Rendering",()=>Review(ComponentCleanup.Prepare(game,false)));if(!embedded)Button(actions,"▶ Avvia gioco",()=>InjectionSetup.Launch(game));
  builds.SelectionChanged+=(s,e)=>{description.Text=Selected().Description;builds.ToolTip=Selected().Description;bool w=Selected().Id=="wilsjo2";placement.IsEnabled=passes.IsEnabled=w;if(packageBuild!=Selected().Id){package="";packageLabel.Text="Scaricamento dal repository della build selezionata.";}};
  builds.SelectedItem=DlssBuild.All.FirstOrDefault(b=>b.Id==scan.Build)??DlssBuild.All[0];
  DlssOptions remembered;if(Core.Pref.DlssChoices.TryGetValue(g.Id,out remembered)&&remembered!=null){builds.SelectedItem=DlssBuild.All.FirstOrDefault(b=>b.Id==remembered.Build)??builds.SelectedItem;fgMode.SelectedIndex=Array.IndexOf(new[]{"keep","opti","native","off"},remembered.FrameMode??"keep");if(fgMode.SelectedIndex<0)fgMode.SelectedIndex=0;adaMfg.IsChecked=remembered.AdaMfg&&adaMfg.IsEnabled;fgCount.SelectedIndex=Math.Max(0,Math.Min(4,remembered.FrameMultiplier-2));refreshFg();enabled.IsChecked=remembered.Enabled;scale.Value=Math.Max(25,Math.Min(100,remembered.Scale));styles.SelectedIndex=Math.Max(0,Math.Min(3,remembered.Style+1));placement.SelectedIndex=Math.Max(0,Math.Min(2,remembered.Placement+1));passes.SelectedIndex=Math.Max(0,Math.Min(2,remembered.Passes-1));strength.Text=Math.Max(0,Math.Min(100,remembered.Strength)).ToString();menuKey=InjectionSetup.ValidMenuKey(remembered.Key)?remembered.Key:"keep";keyCapture.Content="Premi un tasto… · "+InjectionSetup.CapturedKeyLabel(menuKey);proxy.SelectedIndex=remembered.Proxy=="auto"?0:Math.Max(0,Array.IndexOf(new[]{"auto","dxgi.dll","winmm.dll","version.dll","dbghelp.dll","d3d12.dll","wininet.dll","winhttp.dll"},remembered.Proxy));}
  rememberTimer=new System.Windows.Threading.DispatcherTimer{Interval=TimeSpan.FromMilliseconds(450)};rememberTimer.Tick+=(s,e)=>{rememberTimer.Stop();try{Core.SavePrefs();}catch(Exception ex){Error(ex);}};rememberReady=true;
  foreach(var choice in new[]{builds,styles,placement,passes,proxy,fgMode,fgCount})choice.SelectionChanged+=(s,e)=>Remember();scale.ValueChanged+=(s,e)=>Remember();strength.TextChanged+=(s,e)=>Remember();adaMfg.Checked+=(s,e)=>Remember();adaMfg.Unchecked+=(s,e)=>Remember();enabled.Checked+=(s,e)=>Remember();enabled.Unchecked+=(s,e)=>Remember();outer.Unloaded+=(s,e)=>{if(rememberTimer.IsEnabled){rememberTimer.Stop();try{Core.SavePrefs();}catch(Exception ex){ActivityLog.Write("ERRORE preferenze: "+ex.Message);}}};
  if(embedded){border.Child=null;EmbeddedContent=outer;var shell=window;window=owner;shell.Close();return null;}window.Closing+=(s,e)=>{if(busy){e.Cancel=true;status.Text="Attendi il completamento dell’operazione in corso.";}};return window;
 }
 void Remember(){if(!rememberReady)return;try{var options=Options();options.Runtime="";Core.Pref.DlssChoices[game.Id]=options;rememberTimer.Stop();rememberTimer.Start();}catch{/* Incomplete numeric input is not a valid preference yet. */}}
 public static bool AppliedChoice(DlssScan s,string label,int index,object value){
  if(s==null||String.IsNullOrEmpty(s.Proxy))return false;
  if(label=="DLL di caricamento")return index>0&&String.Equals(s.Proxy,Convert.ToString(value),StringComparison.OrdinalIgnoreCase);
  if(label=="Stile")return Core.Get(s.Ini,"DlssNr","Style")== (index==0?"auto":(index-1).ToString());
  if(label.StartsWith("Passaggi"))return s.Build=="wilsjo2"&&Core.Get(s.Ini,"DlssNr","Passes")== (index+1).ToString();
  if(label.StartsWith("Posizione"))return s.Build=="wilsjo2"&&index>0&&Core.Get(s.Ini,"DlssNr","RunBeforeSR")== (index==2?"true":"false")&&new[]{"FinishedPicture","DeferredDLSS","ResidualAcrossRR"}.All(k=>Core.Get(s.Ini,"DlssNr",k)=="false")&&Core.Get(s.Ini,"DlssNr","ApplyModel")=="true";
  bool opti=Core.Get(s.Ini,"FrameGen","Enabled")=="true"&&Core.Get(s.Ini,"FrameGen","FGOutput")=="dlssg";
  bool stopped=Core.Get(s.Ini,"FrameGen","Enabled")=="false";int count;bool native=stopped&&Int32.TryParse(Core.Get(s.Ini,"DLSSG","OverrideInterpolationCount"),out count)&&count>0;
  if(label=="Chi genera i fotogrammi?")return index==1?opti:index==2?native:index==3&&stopped&&Core.Get(s.Ini,"DLSSG","OverrideInterpolationCount")=="auto";
  if(label=="Moltiplicatore richiesto")return (opti||native)&&Core.Get(s.Ini,"DLSSG",opti?"InterpolationCount":"OverrideInterpolationCount")== (index+1).ToString();
  return false;
 }
 DlssScan buildEvidenceScan;string buildEvidence="";
 bool VerifiedBuild(string id){if(!Object.ReferenceEquals(buildEvidenceScan,scan)){buildEvidenceScan=scan;buildEvidence="";try{if(scan.Managed&&scan.Proxy!=""){var m=DlssCore.ReadManifest(scan.Folder);var entry=m.Files.FirstOrDefault(f=>f.Name.Equals(scan.Proxy,StringComparison.OrdinalIgnoreCase));if(entry!=null&&entry.After==DlssCore.Hash(Path.Combine(scan.Folder,scan.Proxy)))buildEvidence=scan.Build;}}catch{}}return buildEvidence!=""&&buildEvidence==id;}
 static string InstalledVersion(string path){
  if(!File.Exists(path))return "Non installato";
  try{string v=System.Diagnostics.FileVersionInfo.GetVersionInfo(path).FileVersion;return String.IsNullOrWhiteSpace(v)?"Presente · versione non dichiarata":v.Replace(",", ".").Replace(" ","");}catch{return "Presente · versione non leggibile";}
 }
 void RefreshInstalled(){foreach(var refresh in choiceRefresh)refresh();if(installedLabel==null)return;try{
  var files=DlssLibraries.Scan(game);var lines=new System.Collections.Generic.List<string>();var paths=new System.Collections.Generic.List<string>();
  string[] labels={"DLSS · Super Resolution","DLSS · Ray Reconstruction","DLSS · Frame Generation"};
  for(int i=0;i<DlssLibraries.Names.Length;i++){string component=DlssLibraries.Names[i];var found=files.Where(f=>f.File.Equals(component,StringComparison.OrdinalIgnoreCase)).ToList();lines.Add(labels[i]+": "+(found.Count==0?"Non installato":String.Join(" / ",found.Select(f=>InstalledVersion(f.Path)).Distinct())+(found.Count>1?" · "+DlssLibraries.CopyLabel(found):"")));paths.AddRange(found.Select(f=>f.Relative+" · "+InstalledVersion(f.Path)));}
  string nr=Path.Combine(Path.GetDirectoryName(game.Exe),"nvngx_dlssnr.dll");lines.Add("Neural Rendering · modello: "+InstalledVersion(nr));if(File.Exists(nr))paths.Add(nr);
  lines.Add("File su disco · attivazione in gioco da verificare");installedLabel.Text=String.Join("\n",lines);installedLabel.ToolTip=new TextBlock{Text=String.Join("\n",paths)+"\n\n"+DlssLibraries.CopyExplanation(),TextWrapping=TextWrapping.Wrap,MaxWidth=680};
 }catch(Exception ex){installedLabel.ToolTip=null;installedLabel.Text="Lettura componenti non completata: "+ex.Message;}}
 static string Summary(DlssScan s){return s.Owner+(s.Blockers.Count>0?"\n"+String.Join("\n",s.Blockers):s.Managed?"\nInstallazione e configurazione gestite da HDLSS.":s.Autopilot||s.Proxy!=""?"\nPremi Installa OptiScaler per scaricare la build scelta e gestirla con HDLSS, con backup dei file precedenti. Non serve aprire altre app.":"\nPremi Installa OptiScaler: HDLSS scarica e installa direttamente la build selezionata.");}
 static int Percent(string ini,string key,int fallback){double v;return Double.TryParse(Core.Get(ini,"DlssNr",key),System.Globalization.NumberStyles.Float,System.Globalization.CultureInfo.InvariantCulture,out v)?Math.Max(0,Math.Min(100,(int)Math.Round(v*100))):fallback;}
 DlssBuild Selected(){return builds.SelectedItem as DlssBuild??DlssBuild.All[0];}
 DlssOptions Options(){return new DlssOptions{Build=Selected().Id,Enabled=enabled.IsChecked==true,Scale=(int)scale.Value,Style=styles.SelectedIndex-1,Placement=placement.SelectedIndex-1,Passes=passes.SelectedIndex+1,Strength=Core.Number(strength.Text,"Intensità",0,100),Runtime=runtime,Proxy=proxy.SelectedIndex==0?"auto":Convert.ToString(proxy.SelectedItem),Key=menuKey,FrameMode=new[]{"keep","opti","native","off"}[Math.Max(0,fgMode.SelectedIndex)],FrameMultiplier=fgCount.SelectedIndex+2,AdaMfg=adaMfg.IsChecked==true};}
 void ChooseRuntime(){var d=new Microsoft.Win32.OpenFileDialog{Filter="Runtime NR|nvngx_dlssnr.dll",Title="Scegli nvngx_dlssnr.dll"};if(d.ShowDialog(window)!=true)return;if(!DlssCore.Pe64(d.FileName))throw new Exception("Il runtime deve essere una DLL PE x64.");runtime=d.FileName;runtimeLabel.Text="Da installare (file selezionato): "+runtime+"\nSHA-256: "+DlssCore.Hash(runtime)+"\nCompatibilità GPU da verificare con la fonte dell’autore.";}
 void ChoosePackage(){using(var d=new System.Windows.Forms.FolderBrowserDialog()){d.Description="Cartella del pacchetto completo estratto, contenente OptiScaler.dll";if(d.ShowDialog()!=System.Windows.Forms.DialogResult.OK)return;if(!File.Exists(Path.Combine(d.SelectedPath,"OptiScaler.dll")))throw new Exception("Non trovo OptiScaler.dll nella cartella.");package=d.SelectedPath;packageBuild=Selected().Id;packageLabel.Text="Pacchetto locale per "+Selected().Name+":\n"+package;}}
 void UpdateRemove(){bool present=scan.Managed||scan.Autopilot||scan.Proxy!="";remove.IsEnabled=!busy&&present;remove.Content=present?"Disinstalla / ripristina":"OptiScaler non installato";HdrChoices.Help(remove,"Rimuove solo OptiScaler con un registro di ripristino riconosciuto. ReShade e MFG separato hanno una gestione distinta.");}
 void Busy(bool value){if(!value)RefreshInstalled();busy=value;controls.IsEnabled=!value;install.IsEnabled=save.IsEnabled=!value;UpdateRemove();}
 async Task<string> ResolveRuntime(DlssOptions options){
  scan=DlssCore.Inspect(game);int series=gpu.SelectedIndex==1?40:gpu.SelectedIndex==2?50:hardware.Series;
  string current=String.IsNullOrEmpty(runtime)?scan.Runtime:runtime,origin="";
  if(options.Enabled)hardware.Validate(series,current);
  options.Runtime=await Task.Run(()=>NrModels.EnsureRuntime(options.Enabled,current,series,message=>window.Dispatcher.Invoke(new Action(()=>status.Text=message)),out origin));
  return origin;
 }
 async void PrepareInstall(){try{Core.Closed(game);Busy(true);var options=Options();string origin=await ResolveRuntime(options);string folder=package,tag="pacchetto locale";var build=Selected();if(folder==""){DlssRelease release=null;folder=await Task.Run(()=>DlssCore.Fetch(build,message=>window.Dispatcher.Invoke(new Action(()=>status.Text=message)),out release));tag=release.Tag;}var plan=await Task.Run(()=>DlssCore.Prepare(game,options,folder,tag));if(origin!="")plan.Summary+="\n"+origin;Busy(false);Review(plan);}catch(Exception ex){Busy(false);Error(ex);}}
 async void SaveExisting(){try{Core.Closed(game);Busy(true);var options=Options();scan=DlssCore.Inspect(game);if(scan.Build!=""&&options.Build!=scan.Build)throw new Exception("Per cambiare build usa Installa OptiScaler. Applica impostazioni non sostituisce la build.");if(scan.Proxy=="")throw new Exception("Premi Installa OptiScaler: scaricherà automaticamente anche il modello necessario.");string origin=await ResolveRuntime(options);var plan=await Task.Run(()=>DlssCore.Prepare(game,options,null,"configurazione esistente"));if(origin!="")plan.Summary+="\n"+origin;Busy(false);Review(plan);}catch(Exception ex){Busy(false);Error(ex);}}

 void Review(DlssPlan plan){StackPanel body;var d=Dialogs.Create(window,"Controlla le modifiche",out body);d.Width=860;d.MaxHeight=SystemParameters.WorkArea.Height-40;var report=new TextBox{Text=plan.ToString(),IsReadOnly=true,TextWrapping=TextWrapping.Wrap,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,Height=Math.Min(420,SystemParameters.WorkArea.Height-250),Margin=new Thickness(0,10,0,14)};body.Children.Add(report);var b=new Button{Content=plan.Uninstall?"Conferma ripristino":"Applica con backup",Style=window.TryFindResource("Primary") as Style};body.Children.Add(b);b.Click+=async(s,e)=>{b.IsEnabled=false;try{Busy(true);string backup=await Task.Run(()=>DlssCore.Apply(game,plan));Busy(false);d.Close();scan=DlssCore.Inspect(game);status.Text=Summary(scan);Busy(false);Dialogs.Notice(window,plan.Uninstall?"Ripristino completato":"DLSS configurato",plan.Uninstall?"File previsti ripristinati o messi da parte. Per verificare gli originali del gioco usa il launcher del gioco.":"File aggiornati e verificati. Avvia il gioco dal suo launcher e usa il menu OptiScaler per verificare Neural Rendering. La presenza dei file non certifica l’effetto attivo.",null).ShowDialog();status.Text+="\nCopia di recupero: "+backup;}catch(Exception ex){Busy(false);b.IsEnabled=true;Error(ex);}};d.Closing+=(s,e)=>{if(busy)e.Cancel=true;};d.ShowDialog();}
 void Libraries(){Libraries(null);}
 void Libraries(string component){
  StackPanel body;var d=Dialogs.Create(window,"DLL DLSS · versioni e ripristino",out body);d.Width=980;
  body.Children.Add(Text("Super Resolution, Ray Reconstruction e Frame Generation. Aggiorna solo le DLL già presenti nel gioco; il runtime NR rimane separato.",12));
  var list=new ComboBox{ItemsSource=DlssLibraries.Scan(game).Where(x=>component==null||x.File.Equals(component,StringComparison.OrdinalIgnoreCase)).ToList(),Margin=new Thickness(0,10,0,12)};body.Children.Add(list);if(list.Items.Count>0)list.SelectedIndex=0;if(component!=null){var item=list.Items.Cast<DlssLibrary>().FirstOrDefault(x=>x.File==component);if(item!=null)list.SelectedItem=item;}
  var info=Text("Scegli il componente e carica le ultime 10 versioni dal catalogo DLSS Swapper. Download dal suo archivio; origine della DLL visibile accanto alla versione. Firma NVIDIA e versione interna vengono verificate prima di applicare.",12);body.Children.Add(info);var versions=new ComboBox{Margin=new Thickness(0,8,0,12),FontSize=15};body.Children.Add(versions);list.SelectionChanged+=(s,e)=>versions.ItemsSource=null;var row=new WrapPanel();body.Children.Add(row);bool fetching=false;
  Action<string> prepare=file=>{var target=list.SelectedItem as DlssLibrary;if(target==null)throw new Exception("Nessuna DLL selezionata.");var plan=DlssLibraries.Prepare(game,target,file);d.Close();Review(plan);};
  var loadVersions=Button(row,"Carica ultime 10",async()=>{if(fetching)return;var target=list.SelectedItem as DlssLibrary;if(target==null){info.Text="Componente non presente nel gioco. Copiare una DLL non aggiunge il supporto a questa funzione: aggiorniamo soltanto componenti già installati.";return;}fetching=true;row.IsEnabled=list.IsEnabled=false;try{var tags=await Task.Run(()=>DllCatalog.Fetch(target.File));versions.ItemsSource=tags;if(tags.Count>0)versions.SelectedIndex=0;info.Text=tags.Count+" versioni dal catalogo DLSS Swapper. Puoi scegliere anche una versione precedente.";}catch(Exception ex){info.Text="Catalogo non disponibile: "+ex.Message+" Puoi importare una DLL da TechPowerUp.";}finally{fetching=false;row.IsEnabled=list.IsEnabled=true;}});
  Button(row,"Installa versione scelta",async()=>{if(fetching)return;var target=list.SelectedItem as DlssLibrary;var tag=versions.SelectedItem as DllDownload;if(target==null||tag==null){info.Text="Carica il catalogo e scegli una versione.";return;}fetching=true;row.IsEnabled=list.IsEnabled=versions.IsEnabled=false;try{string file=await Task.Run(()=>DllCatalog.Download(tag,msg=>d.Dispatcher.Invoke(new Action(()=>info.Text=msg))));fetching=false;prepare(file);}catch(Exception ex){info.Text=ex.Message;}finally{fetching=false;row.IsEnabled=list.IsEnabled=versions.IsEnabled=true;}},true);
  Button(row,"Ultima da NVIDIA",async()=>{if(fetching)return;var target=list.SelectedItem as DlssLibrary;if(target==null)return;fetching=true;row.IsEnabled=list.IsEnabled=versions.IsEnabled=false;try{string file=await Task.Run(()=>DlssLibraries.Latest(target.File,msg=>d.Dispatcher.Invoke(new Action(()=>info.Text=msg))));fetching=false;prepare(file);}catch(Exception ex){info.Text=ex.Message;}finally{fetching=false;row.IsEnabled=list.IsEnabled=versions.IsEnabled=true;}});
  Button(row,"TechPowerUp",()=>{var target=list.SelectedItem as DlssLibrary;if(target!=null)Open(DlssLibraries.Tpu(target.File));});
  Button(row,"Importa DLL…",()=>{var target=list.SelectedItem as DlssLibrary;if(target==null)return;var file=new Microsoft.Win32.OpenFileDialog{Filter="DLL del componente|"+target.File};if(file.ShowDialog(d)==true)prepare(file.FileName);});
  Button(row,"Ripristina solo questa DLL",()=>{var target=list.SelectedItem as DlssLibrary;if(target==null)return;var plan=DlssLibraries.Restore(game,target);d.Close();Review(plan);});
  body.Children.Add(Text("Il download non modifica il gioco. Dopo la verifica della firma NVIDIA vedrai versione e percorso esatti prima di confermare. Per TechPowerUp, scarica ed estrai il file dal sito, poi scegli Importa DLL. Un aggiornamento non abilita MFG su hardware non supportato.",11));
  d.ContentRendered+=(s,e)=>loadVersions.RaiseEvent(new RoutedEventArgs(System.Windows.Controls.Button.ClickEvent));d.Closing+=(s,e)=>{if(fetching)e.Cancel=true;};d.ShowDialog();RefreshInstalled();
 }
 void ShowReport(string title,string report){StackPanel body;var d=Dialogs.Create(window,title,out body);d.Width=900;body.Children.Add(new TextBox{Text=report,IsReadOnly=true,TextWrapping=TextWrapping.Wrap,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,Height=480});d.ShowDialog();}
 static void Open(string path){System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(path){UseShellExecute=true});}
}
}
