using System;
using System.Linq;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
namespace HdrPilot {
public static partial class Guide {
 sealed class Topic {public string Name,Intro;public string[] Sections;public Topic(string name,string intro,params string[] sections){Name=name;Intro=intro;Sections=sections;}}
 static readonly Topic[] Topics={
 new Topic("Attività e avanzamento","In basso trovi la fase corrente e una barra sempre visibile.","Durante l’installazione","Download e controlli senza una misura disponibile usano una barra animata. Durante l’applicazione la barra conta i file completati: non è una stima del tempo residuo. Attendi Operazione completata prima di avviare il gioco.","Registro semplice","Attività recenti mostra i passaggi principali, senza elencare ogni DLL e percorso. Puoi chiuderlo o ridimensionarlo trascinando la barra. Dettagli tecnici apre il registro completo, utile per diagnosticare errori."),
 new Topic("DLSS 5 e GPU","Seleziona un gioco nella libreria e apri DLSS 5 sotto le copertine. L’iniezione viene eseguita tramite OptiScaler, con la build della community selezionata.","RTX 4000 e 5000","L’app prova a leggere GPU e driver tramite NVIDIA. Per RTX 4000 serve il runtime NR di compatibilità indicato dagli autori; RTX 5000 usa quello originale. Il minimo driver documentato dalla build NR è 616.56, ma il risultato va verificato per gioco e release. Il driver non viene installato o sostituito dall’app.","Aiuti per ogni scelta","Sotto i gruppi trovi la spiegazione della scelta selezionata. Passa il mouse su un altro pulsante per leggerne l’effetto prima di sceglierlo. Il punto ? spiega l’intero gruppo. Le opzioni disabilitate mantengono gli aiuti disponibili.","Prima o dopo l’upscaling","Con la build wilsjo2, Prima applica il modello prima dell’ingrandimento: se l’ingresso ha meno pixel, può ridurre il lavoro del modello. Dopo elabora il risultato ingrandito e può costare più tempo GPU. Confronta resa e prestazioni nella stessa scena. Conserva lascia la posizione esistente o il default della build.","Passaggi e MFG sono diversi","Un passaggio esegue il modello una volta; due o tre ripetono l’elaborazione e possono aumentare trasformazione, costo e artefatti. Non creano fotogrammi intermedi: quello è il compito della Frame Generation, descritta nell’argomento dedicato.","Build e regolazioni","Dagherbou, wilsjo2 e y4my4my4m sono varianti della community, non versioni ufficiali NVIDIA. Inizia con un passaggio; 75% riduce il costo del modello, 100% usa la piena risoluzione d’ingresso. Stile e intensità modificano il risultato artistico. I pulsanti ? spiegano ciascuna scelta.","Installazione","Installa OptiScaler scarica il pacchetto standard dal repository dell’autore e verifica il digest pubblicato quando disponibile. Puoi anche scegliere una cartella già estratta. Il runtime nvngx_dlssnr.dll viene conservato se presente o selezionato separatamente. Prima della scrittura appare l’elenco dei file. Non usare nei giochi protetti da anti-cheat."),
 new Topic("Frame Generation / MFG","Genera fotogrammi intermedi per aumentare la fluidità. Il moltiplicatore richiesto non misura gli FPS e non aumenta nella stessa proporzione la reattività dei comandi.","1. Scegli chi genera i fotogrammi","In DLSS 5 trovi Fluidità / Frame Generation. Conserva è la scelta iniziale: non cambia i parametri FG. OptiScaler usa l’upscaler del gioco e un insieme di componenti NVIDIA FG già installato. FG del gioco richiede di attivare DLSS Frame Generation nel menu del gioco; HDLSS ne richiede il moltiplicatore tramite OptiScaler. Non attivare due sistemi FG concorrenti.","2. Scegli il moltiplicatore","Parti da 2×: un fotogramma reale più uno generato. 3× genera due intermedi, 4× tre e così via fino a 6×. I pulsanti non adatti alla GPU vengono disabilitati. I valori superiori dipendono dal supporto del runtime e del gioco; selezionarli non dimostra che siano attivi.","RTX 4000","Il percorso NVIDIA standard è limitato a 2×. Per provare valori superiori scegli y4my4my4m, FG del gioco e MFG RTX 4000 · sperimentale. Lo sblocco Ada è non ufficiale NVIDIA: può avere una cadenza irregolare e smettere di funzionare dopo un aggiornamento driver. L’app controlla che l’installazione dichiari AdaMfgUnlock; in caso contrario aggiorna prima la build. Le altre build non ricevono questo parametro.","RTX 5000","Puoi richiedere i moltiplicatori superiori senza lo sblocco Ada. Il massimo effettivo dipende dai componenti caricati e dal supporto del gioco. I controlli espongono moltiplicatori fissi, non MFG dinamico.","3. Applica e verifica","Chiudi il gioco e premi Applica impostazioni, oppure Installa OptiScaler per una nuova installazione. Controlla l’anteprima e conferma il backup. Riavvia il gioco. Il controllo verifica GPU, file FG/Streamline x64 e, per il moltiplicatore nativo, Streamline almeno 2.7.1. Le dipendenze mancanti non vengono scaricate da questa funzione. Usa il menu e i log del componente per verificare il supporto e il valore applicato; il contatore FPS da solo non basta.","Se non funziona","Il percorso configurato è pensato per DirectX 12; DX11 e Vulkan richiedono verifiche separate. Disattiva OptiScaler rimuove la sua generazione e i suoi override, ma non spegne FG nativa nel gioco. Conserva mantiene lo stato attuale: non annulla una modifica già applicata. Le copie precedenti sono nei backup. L’integrazione è stata testata su configurazioni isolate e nell’interfaccia, non collaudata in gioco in questa sessione."),
 new Topic("DLL e versioni","Il riepilogo Componenti installati mostra subito le versioni SR, RR, FG e del modello NR lette dai file, oppure Non installato. Passando il mouse sul riepilogo trovi i percorsi; Controlla file e percorsi ripete il controllo e mostra i percorsi. Per file multipli confronta gli hash SHA-256 e distingue file identici, file diversi da controllare e confronto non disponibile. Più percorsi non provano un conflitto o più effetti attivi; hash identici non certificano compatibilità o caricamento. Nessuna DLL viene cancellata automaticamente. I backup sono esclusi. Si aggiorna dopo installazioni e ripristini. Non certifica il caricamento in gioco. Le DLL di SR, RR e FG sono componenti diversi dal runtime Neural Rendering. Per lo scambio viene verificata l’architettura x64 della DLL presente, anche quando Windows protegge la lettura dell’eseguibile Xbox. La DLL deve essere accessibile e quella nuova deve superare i controlli NVIDIA; le cartelle protette e gli altri blocchi restano esclusi.","Aggiornamento NVIDIA","I quattro pulsanti Super Resolution, Ray Reconstruction, Frame Generation e Neural Rendering sono raggruppati sotto Componenti installati, senza puntini nei nomi. Neural Rendering apre la scelta del modello DLSS 5. Gli altri tre aprono direttamente il componente scelto, rilevato anche nelle sottocartelle Unreal. All’apertura caricano le ultime 10 versioni dal catalogo, con la più recente selezionata. Se il componente manca, lo segnalano senza sostituire un’altra DLL. Carica ultime 10 usa il catalogo pubblico DLSS Swapper, che include DLL provenienti da SDK, driver e giochi. Installa versione scelta scarica dal suo archivio e verifica hash, firma NVIDIA e versione interna. Ultima da NVIDIA usa invece il repository ufficiale NVIDIA. I cataloghi possono aggiornarsi in momenti diversi. La firma NVIDIA e l’identità del componente devono risultare valide prima dello scambio.","TechPowerUp e importazione","TechPowerUp apre la pagina del componente. Scarica ed estrai la versione desiderata, poi usa Importa DLL. Vedi la versione presente e quella scelta prima di confermare. Se i file sono identici, nessuna modifica viene effettuata.","Ripristino","Ripristina DLL precedenti recupera lo stato prima del primo scambio di HDLSS. Una DLL più recente non aggiunge Ray Reconstruction o Frame Generation se il gioco non le implementa e non abilita MFG su una GPU non supportata."),

 };
 public static Window Create(Window owner){var topics=NewTopics().Concat(Core.Pref.Language=="it"?Topics:EnglishTopics).ToArray();StackPanel body;Window window=Dialogs.Create(owner,"Guida di HDLSS",out body);window.Width=960;window.MaxWidth=SystemParameters.WorkArea.Width-40;window.MaxHeight=SystemParameters.WorkArea.Height-40;var layout=new Grid{Height=Math.Max(380,Math.Min(570,SystemParameters.WorkArea.Height-170)),Margin=new Thickness(0,12,0,0)};layout.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(215)});layout.ColumnDefinitions.Add(new ColumnDefinition());var menu=new StackPanel{Margin=new Thickness(0,0,18,0)};var menuScroll=new ScrollViewer{Content=menu,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};layout.Children.Add(menuScroll);var content=new StackPanel{Margin=new Thickness(22,0,18,12)};var scroll=new ScrollViewer{Content=content,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};Grid.SetColumn(scroll,1);layout.Children.Add(scroll);body.Children.Add(layout);var buttons=new List<Button>();Action<int> select=index=>{content.Children.Clear();for(int i=0;i<buttons.Count;i++){buttons[i].Background=new SolidColorBrush((Color)ColorConverter.ConvertFromString(i==index?"#41331E":"#1B222C"));buttons[i].Foreground=new SolidColorBrush((Color)ColorConverter.ConvertFromString(i==index?"#E6AC50":"#BBC4D0"));}var topic=topics[index];var heading=Dialogs.Text(topic.Name,24);heading.Foreground=new SolidColorBrush(Color.FromRgb(230,172,80));content.Children.Add(heading);content.Children.Add(Dialogs.Text(topic.Intro,13));for(int n=0;n<topic.Sections.Length;n+=2){var h=Dialogs.Text(topic.Sections[n],15);h.Foreground=new SolidColorBrush(Color.FromRgb(230,172,80));h.Margin=new Thickness(0,14,0,8);content.Children.Add(h);content.Children.Add(Dialogs.Text(topic.Sections[n+1],13));}scroll.ScrollToTop();};for(int i=0;i<topics.Length;i++){int index=i;var button=new Button{Content=topics[i].Name,HorizontalContentAlignment=HorizontalAlignment.Left,Padding=new Thickness(10,12,10,12),Margin=new Thickness(0,0,0,7),FontSize=12};button.Click+=(s,e)=>select(index);buttons.Add(button);menu.Children.Add(button);}select(0);return window;}
 public static void Show(Window owner){Create(owner).ShowDialog();}
}
}
