using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Diagnostics;
using System.Windows;
using System.Windows.Controls;
namespace HdrPilot {
public sealed class InjectionProfile {public string Target="",Api="auto";}
public static class InjectionSetup {
 public static readonly string[] MenuKeys={"keep","0x2D","0x24","0x23","0x21","0x22","0x2E","0x70","0x71","0x72","0x73","0x74","0x75","0x76","0x77","0x78","0x7A"};
 public static string KeyName(string key){return key=="keep"?"Conserva":Shortcut.Label(0,Convert.ToUInt32(key.Substring(2),16));}
 public static bool ValidMenuKey(string value){uint vk;return value=="keep"||(value!=null&&value.StartsWith("0x")&&UInt32.TryParse(value.Substring(2),System.Globalization.NumberStyles.HexNumber,System.Globalization.CultureInfo.InvariantCulture,out vk)&&vk>=8&&vk<=254&&vk!=16&&vk!=17&&vk!=18&&vk!=91&&vk!=92&&!(vk>=160&&vk<=165));}
 public static string CapturedKeyLabel(string value){if(value=="keep")return "Conserva";if(!ValidMenuKey(value))return "Tasto non valido";int vk=Convert.ToInt32(value.Substring(2),16);if(MenuKeys.Contains(value))return KeyName(value);return System.Windows.Input.KeyInterop.KeyFromVirtualKey(vk).ToString();}
 public static void CaptureMenuKey(Window owner,Action<string> accept){StackPanel body;var dialog=Dialogs.Create(owner,"Tasto del menu OptiScaler",out body);dialog.Width=560;var hint=Dialogs.Text("Premi il tasto da assegnare, anche Home, Fine o Pag su. Usa un tasto singolo, senza Ctrl, Alt o Shift. Esc annulla.",14);body.Children.Add(hint);var cancel=new Button{Content="Annulla",Margin=new Thickness(0,12,0,0)};cancel.Click+=(s,e)=>dialog.Close();body.Children.Add(cancel);dialog.PreviewKeyDown+=(s,e)=>{e.Handled=true;if(e.IsRepeat)return;var key=e.Key==System.Windows.Input.Key.System?e.SystemKey:e.Key;if(key==System.Windows.Input.Key.Escape){dialog.Close();return;}string value="0x"+System.Windows.Input.KeyInterop.VirtualKeyFromKey(key).ToString("X2");if(System.Windows.Input.Keyboard.Modifiers!=System.Windows.Input.ModifierKeys.None||!ValidMenuKey(value)){hint.Text="Premi un singolo tasto senza modificatori. Esc annulla.";return;}dialog.Close();accept(value);};dialog.ShowDialog();}
 public static InjectionProfile Profile(Game g){if(Core.Pref.InjectionProfiles==null)Core.Pref.InjectionProfiles=new Dictionary<string,InjectionProfile>();InjectionProfile p;return Core.Pref.InjectionProfiles.TryGetValue(g.Id,out p)&&p!=null?p:new InjectionProfile();}
 public static string Target(Game g,string relative){if(g.ProtectedInstall)throw new Exception(g.Evidence);string file=DlssCore.Safe(g.Root,relative);if(!file.EndsWith(".exe",StringComparison.OrdinalIgnoreCase)||!XboxLibrary.IsGameX64(g,file)||Path.GetFileName(file).IndexOf("crash",StringComparison.OrdinalIgnoreCase)>=0||Path.GetFileName(file).IndexOf("unins",StringComparison.OrdinalIgnoreCase)>=0)throw new Exception("Scegli un eseguibile del gioco x64 valido, non un programma di servizio.");return file;}
 public static string Relative(Game g,string file){string root=Path.GetFullPath(g.Root).TrimEnd('\\')+"\\";file=Path.GetFullPath(file);if(!file.StartsWith(root,StringComparison.OrdinalIgnoreCase))throw new Exception("L’eseguibile deve appartenere alla cartella del gioco.");return file.Substring(root.Length);}
 public static void RestoreTarget(Game g){var p=Profile(g);if(!String.IsNullOrEmpty(p.Target))g.Exe=Target(g,p.Target);}
 static IEnumerable<string> Executables(string folder){foreach(string f in Directory.GetFiles(folder,"*.exe"))yield return f;foreach(string d in Directory.GetDirectories(folder)){if((File.GetAttributes(d)&FileAttributes.ReparsePoint)!=0)continue;foreach(string f in Executables(d))yield return f;}}
 public static string LaunchArguments(Game g){if(!System.Text.RegularExpressions.Regex.IsMatch(g.Id??"",@"^\d+$"))throw new Exception("ID Steam non valido.");string api=Profile(g).Api??"auto";if(!new[]{"auto","dx11","dx12","vulkan"}.Contains(api))throw new Exception("API non valida.");return "-applaunch "+g.Id+(api=="auto"||String.IsNullOrEmpty(g.EngineLabel)||!g.EngineLabel.StartsWith("UNREAL")?"":" -"+api);}
 public static void Launch(Game g){LegacyHdr.Disable(g);if(g.Store=="Manual"){if(!File.Exists(g.Exe))throw new Exception("Game executable not found.");Process.Start(new ProcessStartInfo(g.Exe){WorkingDirectory=Path.GetDirectoryName(g.Exe),UseShellExecute=true});return;}if(g.IsXbox){string arg=XboxLibrary.LaunchArgument(g);ActivityLog.Write("Avvio Xbox: "+g.Name);Process.Start(new ProcessStartInfo("explorer.exe",arg){UseShellExecute=true});return;}var args=LaunchArguments(g);string steam=Path.Combine(Core.SteamRoot(),"steam.exe");if(!File.Exists(steam))throw new Exception("Steam non trovato.");ActivityLog.Write("Avvio Steam: "+args);Process.Start(new ProcessStartInfo(steam,args){UseShellExecute=true});}
 public static void Show(Window owner,Game g,Action changed){if(g.ProtectedInstall){Dialogs.Notice(owner,"Installazione protetta",g.Evidence,null).ShowDialog();return;}StackPanel body;var w=Dialogs.Create(owner,"Eseguibile e API grafica",out body);w.Width=820;body.Children.Add(Dialogs.Text("Target.exe indica dove installare i componenti. Avvia gioco usa il launcher di provenienza: la scelta del target non cambia il launcher. Per Xbox / Game Pass si usa il pacchetto registrato, senza forzare parametri API. Cambiare target non sposta né disinstalla le mod già presenti.",13));var paths=new List<string>();foreach(string file in Executables(g.Root)){try{string relative=Relative(g,file);Target(g,relative);paths.Add(relative);}catch{}}var target=new ComboBox{ItemsSource=paths,SelectedItem=String.IsNullOrEmpty(g.Exe)?null:Relative(g,g.Exe),Margin=new Thickness(0,0,0,12)};body.Children.Add(target);var fullPath=new TextBox{IsReadOnly=true,TextWrapping=TextWrapping.Wrap,Text=g.Exe??"",FontSize=12,Margin=new Thickness(0,0,0,10)};body.Children.Add(fullPath);target.SelectionChanged+=(sender,args)=>{string relative=target.SelectedItem as string;fullPath.Text=relative==null?"":Path.Combine(g.Root,relative);};var browse=new Button{Content="Scegli target.exe…",Margin=new Thickness(0,0,0,12)};body.Children.Add(browse);browse.Click+=(s,e)=>{try{var pick=new Microsoft.Win32.OpenFileDialog{Filter="Eseguibile del gioco|*.exe",InitialDirectory=g.Root};if(pick.ShowDialog(w)==true){string relative=Relative(g,pick.FileName);Target(g,relative);if(!paths.Contains(relative)){paths.Add(relative);target.Items.Refresh();}target.SelectedItem=relative;}}catch(Exception ex){Dialogs.Notice(w,"Eseguibile non valido",ex.Message,null).ShowDialog();}};
 string api=Profile(g).Api??"auto";body.Children.Add(Dialogs.Text("API grafica del profilo",15));var row=new WrapPanel();body.Children.Add(row);string[] values={"auto","dx11","dx12","vulkan"},labels={"Automatica","DirectX 11","DirectX 12","Vulkan"};var buttons=new List<Button>();Action refresh=()=>{for(int i=0;i<buttons.Count;i++)buttons[i].Style=w.TryFindResource(values[i]==api?(object)"Primary":typeof(Button)) as Style;};for(int i=0;i<values.Length;i++){int n=i;var b=HdrChoices.Option(labels[i]);HdrChoices.Help(b,i==0?"Conserva l’avvio normale del gioco, senza richiedere un’API specifica.":"Memorizza "+labels[i]+" per questo gioco. Nei titoli Unreal di Steam passa il relativo parametro di avvio; su Xbox resta una preferenza, senza forzare il launcher; negli altri devi selezionarla anche nel gioco. Non aggiunge supporto a un’API mancante.");b.Click+=(s,e)=>{api=values[n];refresh();};row.Children.Add(b);buttons.Add(b);}refresh();body.Children.Add(Dialogs.Text("Nei giochi Unreal di Steam, la scelta passa -dx11, -dx12 o -vulkan a Steam per questo avvio. Negli altri motori memorizza l’API prevista: selezionala anche nelle impostazioni del gioco; l’avvio Steam rimane invariato. Non è una lettura dell’API attiva e non aggiunge API mancanti al gioco. Automatica conserva l’avvio normale. Per NR in DX11 occorre un backend con ponte DX12; Vulkan dipende dalla build e dal gioco.",13));var error=Dialogs.Text("",13);body.Children.Add(error);var save=new Button{Content="Salva per questo gioco",Style=w.TryFindResource("Primary") as Style};body.Children.Add(save);save.Click+=(s,e)=>{try{Core.Closed(g);string relative=target.SelectedItem as string;string exe=Target(g,relative);var old=Profile(g);Core.Pref.InjectionProfiles[g.Id]=new InjectionProfile{Target=relative,Api=api};try{Core.SavePrefs();}catch{Core.Pref.InjectionProfiles[g.Id]=old;throw;}g.Exe=exe;ActivityLog.Write("Target: "+exe+" · API richiesta: "+api);w.Close();changed();}catch(Exception ex){error.Text=ex.Message;}};w.ShowDialog();}
}
}
