using System;using System.IO;using System.Linq;using System.Threading.Tasks;using System.Collections.Generic;using System.Windows;using System.Windows.Controls;using System.Windows.Media;
namespace HdrPilot {
// Version choices exist independently of the selected game's installed files.
public sealed class LibraryPanel {
 readonly Window owner;readonly Game game;readonly Func<int> series;readonly Action changed;readonly StackPanel panel=new StackPanel{Name="ComponentLibrary",MaxWidth=1200,HorizontalAlignment=HorizontalAlignment.Left};
 readonly TextBlock status;readonly List<Action> scans=new List<Action>();readonly List<Func<Task>> refreshers=new List<Func<Task>>();bool working,loaded;
 static string L(string text){return Appearance.Localize(text);}
 public FrameworkElement View {get{return panel;}}
 public LibraryPanel(Window owner,Game game,Func<int> series,Action changed){this.owner=owner;this.game=game;this.series=series;this.changed=changed;
  panel.ToolTip=L("Choose a version, then install. Downloads, signature checks and backups run here. Updates require an existing game integration.");
  status=Dialogs.Text(L("Local catalog ready. Checking online…"),13);panel.Children.Add(status);
  for(int i=0;i<DlssLibraries.Names.Length;i++)Native(DlssLibraries.Names[i],new[]{"Super Resolution","Ray Reconstruction","Frame Generation"}[i]);
  StreamlineCard();NrCard();SavedCard();
  var refresh=Button(panel,"Refresh catalog",async()=>{if(working)return;working=true;refreshStatus();try{foreach(var run in refreshers)await run();foreach(var scan in scans)scan();status.Text=L("Catalog check completed. See each component for its status.");}finally{working=false;}});
  panel.Loaded+=async(s,e)=>{if(loaded)return;loaded=true;foreach(var run in refreshers)await run();status.Text=L("Catalog check completed. See each component for its status.");};
 }
 void SavedCard(){var body=new StackPanel();var box=new Border{Child=body,Padding=new Thickness(16),Margin=new Thickness(0,8,0,12),BorderThickness=new Thickness(1),BorderBrush=new SolidColorBrush(Color.FromRgb(65,85,103)),Background=new SolidColorBrush(Color.FromRgb(23,30,39)),CornerRadius=new CornerRadius(10)};panel.Children.Insert(1,box);var title=Dialogs.Text(L("Working DLL configuration"),18);title.Foreground=Brushes.White;body.Children.Add(title);body.Children.Add(Dialogs.Text(L("Save only after testing the game. Includes detected DLSS DLLs and Streamline folders, not mod settings. Restore is manual and backs up current files."),13));var state=Dialogs.Text("",14);body.Children.Add(state);var row=new WrapPanel();body.Children.Add(row);var save=Button(row,"Save working configuration",async()=>{working=true;ModCenter.Busy=true;panel.IsEnabled=false;try{await Task.Run(()=>SavedComponents.Save(game));foreach(var scan in scans)scan();status.Text=L("Working configuration saved.");}catch(Exception ex){status.Text=L(ex.Message);}finally{working=false;ModCenter.Busy=false;panel.IsEnabled=true;}});save.Style=owner.TryFindResource("Primary") as Style;var restore=Button(row,"Restore saved configuration",async()=>await Run(progress=>SavedComponents.Restore(game)));restore.Style=owner.TryFindResource("RestoreAction") as Style;Action refresh=()=>{state.Text=SavedComponents.State(game);bool matches=false,valid=false;try{if(SavedComponents.Exists(game)){matches=SavedComponents.Differences(game)==0;valid=true;}}catch{}state.Foreground=matches?new SolidColorBrush(Color.FromRgb(230,172,80)):Brushes.LightGray;restore.IsEnabled=valid&&!matches;};scans.Add(refresh);refresh();}
 void AddRefresh(StackPanel card,Func<Task> refresh){refreshers.Add(refresh);var state=Dialogs.Text("",13);card.Children.Add(state);Button(card,"Check again",async()=>{if(working)return;working=true;try{await refresh();foreach(var scan in scans)scan();state.Text=L("Catalog check completed. See each component for its status.");}catch(Exception ex){state.Text=L(ex.Message);}finally{working=false;}});}
 void refreshStatus(){status.Text=L("Checking updates…");}
 StackPanel Card(string name){var card=new StackPanel{Margin=new Thickness(0,0,0,2)};var label=Dialogs.Text(name,15);label.Foreground=new SolidColorBrush(Color.FromRgb(230,172,80));card.Children.Add(label);card.Children.Remove(label);panel.Children.Add(new Border{Child=NavigationSession.Track("library-"+name,new Expander{Header=label,Content=card,IsExpanded=false,Padding=new Thickness(6)}),Padding=new Thickness(10),CornerRadius=new CornerRadius(10),BorderThickness=new Thickness(1),BorderBrush=new SolidColorBrush(Color.FromRgb(52,62,74)),Margin=new Thickness(0,4,0,8)});return card;}
 static ComboBox Combo(Panel parent,string name){parent.Children.Add(Dialogs.Text(L(name),12));var c=new ComboBox{MinWidth=180,MaxDropDownHeight=300,Margin=new Thickness(0,2,0,6),HorizontalAlignment=HorizontalAlignment.Stretch};System.Windows.Automation.AutomationProperties.SetName(c,L(name));parent.Children.Add(c);return c;}
 Button Button(Panel parent,string name,Action action){var b=new Button{Content=L(name),Margin=new Thickness(0,4,8,4),Padding=new Thickness(12,8,12,8)};parent.Children.Add(b);b.Click+=(s,e)=>{if(working||InlineOperation.IsBusy||ModCenter.Busy||RenoDxUi.IsBusy)return;try{action();}catch(Exception ex){status.Text=L(ex.Message);}};return b;}
 async Task Run(Func<Action<string>,DlssPlan> make){if(working||InlineOperation.IsBusy)return;working=true;ModCenter.Busy=true;panel.IsEnabled=false;try{Core.Closed(game);status.Text=L("Downloading and verifying…");status.BringIntoView();Action<string> progress=msg=>panel.Dispatcher.Invoke(new Action(()=>status.Text=L(msg)));var plan=await Task.Run(()=>make(progress));await InlineOperation.Apply(game,plan,status,()=>{foreach(var scan in scans)scan();changed();});}catch(Exception ex){status.Text=L(ex.Message);ActivityLog.Write(ex.Message);}finally{ModCenter.Busy=false;working=false;panel.IsEnabled=true;}}
 void Native(string file,string title){var card=Card("DLSS · "+title);var state=Dialogs.Text("",13);card.Children.Add(state);var targets=Combo(card,"Game file");var versions=Combo(card,"Available version");versions.ItemsSource=DllCatalog.Local(file);versions.SelectedIndex=0;
  var info=Dialogs.Text(L("Local catalog · download required unless already cached."),12);card.Children.Add(info);var row=new WrapPanel();card.Children.Add(row);card.Children.RemoveAt(card.Children.IndexOf(versions)-1);card.Children.Remove(versions);versions.Width=290;versions.Margin=new Thickness(0,4,8,4);versions.MinHeight=34;row.Children.Add(versions);
  var install=Button(row,"Install selected version",async()=>{var target=targets.SelectedItem as DlssLibrary;var version=versions.SelectedItem as DllDownload;if(target==null||version==null)return;await Run(progress=>{DlssLibraries.ValidateTarget(game,target);return DlssLibraries.Prepare(game,target,DllCatalog.Download(version,progress));});});
  var import=Button(row,"Import DLL…",async()=>{var target=targets.SelectedItem as DlssLibrary;if(target==null)return;var pick=new Microsoft.Win32.OpenFileDialog{Filter="DLL|"+file};if(pick.ShowDialog(owner)==true){string source=pick.FileName;await Run(progress=>DlssLibraries.Prepare(game,target,source));}});
  Action scan=()=>{string old=(targets.SelectedItem as DlssLibrary)==null?null:((DlssLibrary)targets.SelectedItem).Path;var found=DlssLibraries.Scan(game).Where(f=>f.File.Equals(file,StringComparison.OrdinalIgnoreCase)).ToList();targets.ItemsSource=found;targets.SelectedItem=found.FirstOrDefault(f=>f.Path==old)??(found.Count==1?found[0]:null);install.IsEnabled=targets.SelectedItem!=null;targets.Visibility=found.Count>1?Visibility.Visible:Visibility.Collapsed;card.Children[card.Children.IndexOf(targets)-1].Visibility=targets.Visibility;state.Text=found.Count==0?L("Not detected. Select the correct game executable; installing a DLL alone does not add support."):L("Installed")+" · "+String.Join(" / ",found.Select(f=>f.Version).Distinct())+(found.Count==1?" · "+found[0].Relative:"");state.Foreground=found.Count>0?new SolidColorBrush(Color.FromRgb(230,172,80)):Brushes.LightGray;};scans.Add(scan);scan();targets.SelectionChanged+=(s,e)=>import.IsEnabled=install.IsEnabled=targets.SelectedItem!=null;import.IsEnabled=install.IsEnabled;
  AddRefresh(card,async()=>{try{var items=await Task.Run(()=>DllCatalog.Fetch(file));string old=(versions.SelectedItem as DllDownload)==null?null:((DllDownload)versions.SelectedItem).Version;versions.ItemsSource=items;versions.SelectedItem=items.FirstOrDefault(v=>v.Version==old)??items.FirstOrDefault();info.Text=L("Online catalog verified.");}catch(Exception ex){info.Text=L("Online check failed. Local versions remain available.")+" "+ex.Message;}});
 }
 void StreamlineCard(){var card=Card("Streamline");var folders=Combo(card,"Game folder");var versions=Combo(card,"Available version");versions.ItemsSource=Streamline.LocalVersions();versions.SelectedIndex=0;var info=Dialogs.Text(L("Local catalog · download required unless already cached."),12);card.Children.Add(info);var row=new WrapPanel();card.Children.Add(row);card.Children.RemoveAt(card.Children.IndexOf(versions)-1);card.Children.Remove(versions);versions.Width=290;versions.Margin=new Thickness(0,4,8,4);versions.MinHeight=34;row.Children.Add(versions);
  var install=Button(row,"Install selected version",async()=>{string folder=folders.SelectedItem as string,version=versions.SelectedItem as string;if(folder==null||version==null)return;await Run(progress=>{Streamline.CheckTarget(game,folder);return Streamline.Prepare(game,folder,Streamline.Download(version,progress));});});
  var import=Button(row,"Import Streamline SDK ZIP",async()=>{string folder=folders.SelectedItem as string;if(folder==null)return;var pick=new Microsoft.Win32.OpenFileDialog{Filter="Streamline SDK|*.zip"};if(pick.ShowDialog(owner)==true){string zip=pick.FileName;await Run(progress=>Streamline.Prepare(game,folder,Streamline.Extract(zip)));}});
  var state=Dialogs.Text("",13);card.Children.Insert(1,state);Action scan=()=>{var paths=Streamline.Scan(game).Select(f=>Path.GetDirectoryName(f.Path)).Distinct(StringComparer.OrdinalIgnoreCase).ToList();string old=folders.SelectedItem as string;folders.ItemsSource=paths;folders.SelectedItem=paths.FirstOrDefault(f=>f==old)??(paths.Count==1?paths[0]:null);folders.Visibility=paths.Count>1?Visibility.Visible:Visibility.Collapsed;card.Children[card.Children.IndexOf(folders)-1].Visibility=folders.Visibility;state.Text=Streamline.Summary(game)+(paths.Count==1?" · "+paths[0]:"");state.Foreground=paths.Count>0?new SolidColorBrush(Color.FromRgb(230,172,80)):Brushes.LightGray;install.IsEnabled=folders.SelectedItem!=null;};scans.Add(scan);scan();folders.SelectionChanged+=(s,e)=>import.IsEnabled=install.IsEnabled=folders.SelectedItem!=null;import.IsEnabled=install.IsEnabled;
  AddRefresh(card,async()=>{try{var items=await Task.Run(()=>Streamline.Versions());string old=versions.SelectedItem as string;versions.ItemsSource=items;versions.SelectedItem=items.Contains(old)?old:items.FirstOrDefault();info.Text=L("Online catalog verified.");}catch(Exception ex){info.Text=L("Online check failed. Local versions remain available.")+" "+ex.Message;}});
 }
 void NrCard(){var card=Card("Neural Rendering · DLSS 5");var state=Dialogs.Text("",13);card.Children.Add(state);var versions=Combo(card,"Available version");versions.ItemsSource=NrModels.Local();versions.SelectedIndex=0;bool chosen=false;versions.DropDownOpened+=(s,e)=>chosen=true;card.Loaded+=(s,e)=>{if(!chosen){var items=versions.Items.Cast<NrModel>();versions.SelectedItem=items.FirstOrDefault(m=>series()==40?m.Community:!m.Community);}};var info=Dialogs.Text(L("Community models: choose the variant for your GPU. This is separate from SR, RR and FG."),12);card.Children.Add(info);var row=new WrapPanel();card.Children.Add(row);card.Children.RemoveAt(card.Children.IndexOf(versions)-1);card.Children.Remove(versions);versions.Width=290;versions.Margin=new Thickness(0,4,8,4);versions.MinHeight=34;row.Children.Add(versions);Button(row,"Install selected version",async()=>{var model=versions.SelectedItem as NrModel;if(model==null){status.Text=L("Select a version first.");return;}int gpu=series();NrModels.Compatible(model,gpu);DlssHardware.Detect().Validate(gpu,"");await Run(progress=>NrModels.Prepare(game,NrModels.Download(model,progress),model));});
  Action scan=()=>{string path=Path.Combine(Path.GetDirectoryName(game.Exe),"nvngx_dlssnr.dll");bool exists=DlssCore.Pe64(path);state.Text=exists?L("Installed")+" · "+System.Diagnostics.FileVersionInfo.GetVersionInfo(path).FileVersion:L("Not installed");state.Foreground=exists?new SolidColorBrush(Color.FromRgb(230,172,80)):Brushes.LightGray;};scans.Add(scan);scan();
  AddRefresh(card,async()=>{try{var items=await Task.Run(()=>NrModels.Fetch());string old=(versions.SelectedItem as NrModel)==null?null:((NrModel)versions.SelectedItem).Tag;versions.ItemsSource=items;versions.SelectedItem=items.FirstOrDefault(v=>v.Tag==old);info.Text=L("Community models: choose the variant for your GPU. This is separate from SR, RR and FG.");}catch(Exception ex){info.Text=L("Online check failed. Local versions remain available.")+" "+ex.Message;}});
 }
}
}
