using System;using System.IO;using System.Linq;using System.Threading.Tasks;using System.Windows;using System.Windows.Controls;using System.Collections.Generic;
namespace HdrPilot {
public static class ModCenter {
 static bool ownBusy;public static bool Busy {get{return ownBusy||InlineOperation.IsBusy;}set{ownBusy=value;}}
 static string L(string s){return Appearance.Localize(s);}
 public static void Show(Window owner,IEnumerable<Game> games,Game selected,bool removal,Action changed){var all=games.Where(g=>g!=null&&File.Exists(g.Exe)).ToList();if(selected!=null&&!all.Any(g=>g.Exe==selected.Exe))all.Add(selected);StackPanel body;var d=Dialogs.Create(owner,L(removal?"Remove components":"Mod updates"),out body);d.Width=950;d.MaxHeight=SystemParameters.WorkArea.Height-40;var picker=new ComboBox{ItemsSource=all,DisplayMemberPath="Name",SelectedItem=selected??all.FirstOrDefault(),Margin=new Thickness(0,0,0,10)};body.Children.Add(picker);var info=Dialogs.Text(L(removal?"Remove one component at a time. Files are deleted with a recovery copy; other mods are preserved.":"Checks run at startup. Updates are applied only when you choose them, with backup."),13);body.Children.Add(info);var list=new StackPanel();body.Children.Add(new ScrollViewer{Content=list,VerticalScrollBarVisibility=ScrollBarVisibility.Auto,MaxHeight=420});var refresh=new Button{Content=L("Check again"),Margin=new Thickness(0,12,0,0)};body.Children.Add(refresh);Action render=null;
 Action<DlssPlan> review=plan=>{StackPanel b;var w=Dialogs.Create(d,L("Review changes"),out b);w.Width=830;b.Children.Add(new TextBox{Text=plan.ToString(),IsReadOnly=true,TextWrapping=TextWrapping.Wrap,Height=330,VerticalScrollBarVisibility=ScrollBarVisibility.Auto});var apply=new Button{Content=L("Apply with backup"),Margin=new Thickness(0,12,0,0)};b.Children.Add(apply);w.Closing+=(s,e)=>{if(Busy)e.Cancel=true;};apply.Click+=async(s,e)=>{Busy=true;apply.IsEnabled=false;try{string recovery=await Task.Run(()=>DlssCore.Apply((Game)picker.SelectedItem,plan));Busy=false;w.Close();info.Text=L("Files verified. Recovery copy:")+" "+recovery;changed();var checking=ModUpdates.Refresh(all);render();}catch(Exception ex){info.Text=ex.Message;}finally{Busy=false;apply.IsEnabled=true;}};w.ShowDialog();};
 render=()=>{list.Children.Clear();var game=picker.SelectedItem as Game;if(game==null)return;foreach(var item in ModInventory.Scan(game)){var row=new DockPanel{Margin=new Thickness(0,6,0,6)};var action=new Button{Content=L(removal?(item.Id=="native"||item.Id=="streamline"?"Restore original":"Uninstall"):"Update"),Margin=new Thickness(12,0,0,0),MinWidth=110};DockPanel.SetDock(action,Dock.Right);row.Children.Add(action);string marker=item.Id=="asi"?AsiLoader.Marker:item.Id=="mfg"?MfgAddon.Marker:item.Id=="renodx"?RenoDx.AddonMarker:item.Id=="reshade"?RenoDx.Marker:item.Id=="nr"?NrModels.Marker:item.Id=="effect"?item.Marker:null;if(removal&&marker!=null&&File.Exists(Path.Combine(Path.GetDirectoryName(game.Exe),marker))){var undo=new Button{Content=L("Restore previous"),Margin=new Thickness(8,0,0,0)};DockPanel.SetDock(undo,Dock.Right);row.Children.Add(undo);undo.Click+=(s,e)=>{try{review(item.Id=="asi"?AsiLoader.Restore(game):item.Id=="mfg"?MfgAddon.Restore(game):item.Id=="nr"?NrModels.Restore(game):item.Id=="effect"?EffectCatalog.Remove(game,item.Effect):RenoDx.Restore(game,marker));}catch(Exception ex){info.Text=ex.Message;}};}var label=new Button{Content=item.Name+" · "+(item.Version??""),Style=d.TryFindResource("Installed") as Style,HorizontalContentAlignment=HorizontalAlignment.Left};var col=new StackPanel();col.Children.Add(label);if(!String.IsNullOrEmpty(item.File)){string prefix=Path.GetFullPath(game.Root).TrimEnd('\\')+"\\";string location=item.File.StartsWith(prefix,StringComparison.OrdinalIgnoreCase)?item.File.Substring(prefix.Length):item.File;col.Children.Add(Dialogs.Text(location,11));}if(!removal){var check=ModUpdates.Items.FirstOrDefault(i=>i.Game.Exe==game.Exe&&i.Id==item.Id&&i.File==item.File&&i.Name==item.Name);action.IsEnabled=check==null||check.Status!="Up to date";col.Children.Add(Dialogs.Text(L(ModUpdates.Checking?"Checking updates…":check==null?"Not checked":check.Status)+(check!=null&&!String.IsNullOrEmpty(check.Latest)?" · "+check.Latest:""),12));}row.Children.Add(col);list.Children.Add(row);action.Click+=async(s,e)=>{if(Busy)return;Busy=true;picker.IsEnabled=refresh.IsEnabled=list.IsEnabled=false;try{if(removal){var plan=ModInventory.Remove(item);Busy=false;review(plan);}else if(item.Id=="opti"||item.Id=="nr"||item.Id=="ue4ss"){Busy=false;if(item.Id=="opti")DlssUi.Show(d,game);else if(item.Id=="nr")NrModels.Show(d,game,DlssHardware.Detect().Series,changed);else{Busy=true;var plan=await Task.Run(()=>Ue4ssInstaller.DownloadAndPrepare(game,false));Busy=false;review(plan);}}else{var plan=await Task.Run(()=>Update(item));Busy=false;review(plan);}render();}catch(Exception ex){info.Text=ex.Message;}finally{Busy=false;picker.IsEnabled=refresh.IsEnabled=list.IsEnabled=true;}};}
 if(removal){if(File.Exists(Path.Combine(Path.GetDirectoryName(game.Exe),RenoDx.KeyMarker))){var restoreKey=new Button{Content=L("Ripristina tasto ReShade"),Margin=new Thickness(0,10,0,0)};list.Children.Add(restoreKey);restoreKey.Click+=(s,e)=>{try{review(RenoDx.Restore(game,RenoDx.KeyMarker));}catch(Exception ex){info.Text=ex.Message;}};}var duplicate=new Button{Content=L("Clean duplicate loaders"),Margin=new Thickness(0,12,0,0)};list.Children.Add(duplicate);duplicate.Click+=(s,e)=>{try{review(DuplicateLoaders.Prepare(game));}catch(Exception ex){info.Text=ex.Message;}};}
 };
 picker.SelectionChanged+=(s,e)=>render();refresh.Click+=async(s,e)=>{refresh.IsEnabled=false;try{await ModUpdates.Refresh(all);render();}finally{refresh.IsEnabled=true;}};Action onChange=()=>d.Dispatcher.BeginInvoke(new Action(()=>{if(d.IsVisible)render();}));ModUpdates.Changed+=onChange;d.Closed+=(s,e)=>ModUpdates.Changed-=onChange;d.Closing+=(s,e)=>{if(Busy)e.Cancel=true;};render();d.ShowDialog();}

 public static DlssPlan RemoveGroup(Game game,string id){
  var items=ModInventory.Scan(game).Where(i=>i.Id==id).ToArray();if(items.Length==0)throw new Exception(L("No component files found."));
  var plan=ModInventory.Remove(items[0]);foreach(var item in items.Skip(1)){var next=ModInventory.Remove(item);if(next.Folder!=plan.Folder||next.Manifest!=null||plan.Manifest!=null)throw new Exception("Separate component locations require individual removal.");foreach(var c in next.Changes){var prior=plan.Changes.FirstOrDefault(x=>String.Equals(x.Name,c.Name,StringComparison.OrdinalIgnoreCase));if(prior==null)plan.Changes.Add(c);else if(prior.Delete!=c.Delete||prior.Expected!=c.Expected||prior.Source!=c.Source||!Enumerable.SequenceEqual(prior.Bytes??new byte[0],c.Bytes??new byte[0]))throw new Exception("Conflicting component changes: "+c.Name);}}
  return plan;
 }
 public static FrameworkElement Panel(Window owner,Game game,bool dlss,Action changed,Action<string> chooseVersion=null){
  var panel=new StackPanel{Name="InlineModActions",Margin=new Thickness(0,6,0,12)};
  var hdr=new StackPanel();panel.Children.Add(hdr);var removals=new WrapPanel{Name="InlineRemovalButtons"};var updates=new StackPanel{Name="InlineUpdates"};var info=Dialogs.Text("",12);
  var heading=Dialogs.Text(L("Removal"),15);panel.Children.Add(heading);panel.Children.Add(removals);
  var updateHeading=new DockPanel{Margin=new Thickness(0,10,0,6)};var check=new Button{Content=L("Check again"),MinWidth=120,Margin=new Thickness(8,0,0,0)};DockPanel.SetDock(check,Dock.Right);updateHeading.Children.Add(check);updateHeading.Children.Add(Dialogs.Text(L("Mod updates"),15));panel.Children.Add(updateHeading);panel.Children.Add(updates);panel.Children.Add(info);
  Action render=null;Action<DlssPlan> review=async plan=>{panel.IsEnabled=false;try{await InlineOperation.Apply(game,plan,info,()=>{changed();render();});}finally{panel.IsEnabled=true;}};

  Action<string,string,Action,bool> addRemove=(label,tag,action,enabled)=>{var button=new Button{Content=L(label),Tag=tag,MinWidth=120,Margin=new Thickness(0,0,8,6),IsEnabled=enabled,Style=owner.TryFindResource("RestoreAction") as Style};removals.Children.Add(button);button.Click+=(s,e)=>{if(Busy||RenoDxUi.IsBusy)return;try{action();render();}catch(Exception ex){info.Text=L(ex.Message);}};};
  render=()=>{
   var items=ModInventory.Scan(game).Where(i=>dlss?new[]{"opti","nr","native","streamline"}.Contains(i.Id):!new[]{"opti","nr","native","streamline"}.Contains(i.Id)).ToList();removals.Children.Clear();updates.Children.Clear();
   hdr.Children.Clear();if(!dlss&&RenoGameHdr.Supported(game)){bool configured=RenoGameHdr.Configured(game);var row=new WrapPanel();var configure=new Button{Content=L(configured?"HDR configured":"Configure HDR"),Margin=new Thickness(0,0,8,6),IsEnabled=!configured&&items.Any(i=>i.Id=="renodx"),Style=owner.TryFindResource(configured?"Installed":"Primary") as Style};row.Children.Add(configure);configure.Click+=(s,e)=>{if(Busy||RenoDxUi.IsBusy)return;try{review(RenoGameHdr.Prepare(game));}catch(Exception ex){info.Text=L(ex.Message);}};if(RenoGameHdr.Managed(game)){var restore=new Button{Content=L("Restore HDR configuration"),Margin=new Thickness(0,0,8,6)};row.Children.Add(restore);restore.Click+=(s,e)=>{if(Busy||RenoDxUi.IsBusy)return;try{var p=new DlssPlan{Folder=Path.GetDirectoryName(game.Exe),Uninstall=true,Summary=L("Restore HDR configuration")};RenoGameHdr.AttachRestore(game,p);review(p);}catch(Exception ex){info.Text=L(ex.Message);}};}hdr.Children.Add(row);hdr.Children.Add(Dialogs.Text(L(configured?"Restart the game and verify HDR in a loaded scene.":"RenoDX HDR requires game configuration."),12));}
   string[] ids=dlss?new[]{"opti","nr"}:new[]{"reshade","asi","renodx","mfg"};string[] labels=dlss?new[]{"Remove OptiScaler","Remove Neural Rendering"}:new[]{"Remove ReShade","Remove ASI Loader","Remove RenoDX","Remove MFG"};
   for(int n=0;n<ids.Length;n++){string id=ids[n];addRemove(labels[n],"remove-"+id,()=>review(RemoveGroup(game,id)),items.Any(i=>i.Id==id));}
   foreach(var item in items.Where(i=>!ids.Contains(i.Id))){var current=item;addRemove((item.Id=="native"||item.Id=="streamline"?L("Restore original"):L("Uninstall"))+" · "+item.Name,"remove-"+item.Id,()=>review(ModInventory.Remove(current)),true);}
   if(!dlss)addRemove("Clean duplicate loaders","remove-duplicates",()=>review(DuplicateLoaders.Prepare(game)),true);
   if(items.Count==0)updates.Children.Add(Dialogs.Text(L("No installed components detected."),12));
   foreach(var item in items){var current=item;var checkedItem=ModUpdates.Items.FirstOrDefault(i=>i.Game.Exe==game.Exe&&i.Id==item.Id&&i.File==item.File&&i.Name==item.Name);var row=new DockPanel{Margin=new Thickness(0,0,0,6)};var update=new Button{Content=L(item.Id=="opti"||item.Id=="nr"?"Choose version":item.Id=="addon"?(RenoDx.AddonPage(item.File)!=null?"Update via Nexus":"Import update…"):"Update"),MinWidth=120,Margin=new Thickness(8,0,0,0),Tag="update-"+item.Id,IsEnabled=!ModUpdates.Checking&&(checkedItem==null||checkedItem.Status!="Up to date")};DockPanel.SetDock(update,Dock.Right);row.Children.Add(update);var text=Dialogs.Text(item.Name+" · "+(item.Version??"")+"\n"+L(ModUpdates.Checking?"Checking updates…":checkedItem==null?"Not checked":checkedItem.Status)+(checkedItem!=null&&!String.IsNullOrEmpty(checkedItem.Latest)?" · "+checkedItem.Latest:""),12);text.Foreground=new System.Windows.Media.SolidColorBrush(System.Windows.Media.Color.FromRgb(230,172,80));row.Children.Add(text);updates.Children.Add(row);
    update.Click+=async(s,e)=>{if(Busy||RenoDxUi.IsBusy)return;Busy=true;panel.IsEnabled=false;try{if(current.Id=="addon"){Busy=false;string page=RenoDx.AddonPage(current.File);if(page!=null)NexusDownload.Show(owner,game,page,review,current.File,"Control",panel);else{var pick=new Microsoft.Win32.OpenFileDialog{Filter="ReShade add-on|*.addon64",Title=L("Choose the same add-on filename (x64).")};if(pick.ShowDialog(owner)==true)review(RenoDx.ReplaceManualAddon(game,current.File,pick.FileName));}changed();}else if(current.Id=="opti"||current.Id=="nr"){info.Text=L("Choose the version in the main component section, then install.");if(chooseVersion!=null)chooseVersion(current.Id);}else{var plan=await Task.Run(()=>current.Id=="ue4ss"?Ue4ssInstaller.DownloadAndPrepare(game,false):Update(current));Busy=false;review(plan);}render();}catch(Exception ex){info.Text=L(ex.Message);}finally{Busy=false;panel.IsEnabled=true;}};
   }
   check.IsEnabled=!ModUpdates.Checking;check.Content=L(ModUpdates.Checking?"Checking updates…":"Check again");
  };
  check.Click+=async(s,e)=>{if(Busy)return;try{await ModUpdates.Refresh(new[]{game});}catch(Exception ex){info.Text=L(ex.Message);}};
  bool subscribed=false;Action onChange=()=>panel.Dispatcher.BeginInvoke(new Action(()=>{if(panel.IsLoaded&&!Busy)render();}));panel.Loaded+=(s,e)=>{if(!subscribed){ModUpdates.Changed+=onChange;subscribed=true;}render();};panel.Unloaded+=(s,e)=>{if(subscribed){ModUpdates.Changed-=onChange;subscribed=false;}};render();return panel;
 }
 static DlssPlan Update(ModItem item){var g=item.Game;Core.Closed(g);string origin;
 switch(item.Id){case "reshade":return RenoDx.InstallReShade(g,RenoDx.Fetch(RenoDx.InstalledChannel(g)=="nightly",s=>{},out origin),origin);
 case "renodx":return RenoDx.InstallAddon(g,RenoDx.FetchForGame(g,out origin));
 case "mfg":MfgAddon.Release release;string file=MfgAddon.Fetch(out release);return MfgAddon.Prepare(g,file,release);
 case "asi":return AsiLoader.Prepare(g,AsiLoader.Fetch(),Path.GetFileName(item.File));
 case "effect":return EffectCatalog.Prepare(g,item.Effect,s=>{});
 case "streamline":return Streamline.Prepare(g,item.File,Streamline.Latest(s=>{}));
 case "native":var dll=DllCatalog.Fetch(item.Library.File).First();return DlssLibraries.Prepare(g,item.Library,DllCatalog.Download(dll,s=>{}));
 default:throw new Exception("No updater for this component.");}
 }
}
}

