using System;using System.IO;using System.Linq;using System.Text;using System.Collections.Generic;using System.Diagnostics;using System.Text.RegularExpressions;
namespace HdrPilot {
public sealed class ModItem {public Game Game;public string Id,Name,File,Version,Latest="",Status="",Repo="",Marker="";public bool UpdateAvailable;public EffectPackage Effect;public DlssLibrary Library;}
public static class ModInventory {
 public static string Version(string path){try{return (FileVersionInfo.GetVersionInfo(path).FileVersion??"").Replace(", ",".");}catch{return "";}}
 public static bool Recorded(Game g,string marker){try{string root=Path.GetDirectoryName(g.Exe);var m=DlssCore.ReadManifest(root,marker);return m.Files.Any(f=>!f.Name.EndsWith(".ini",StringComparison.OrdinalIgnoreCase)&&File.Exists(DlssCore.Safe(root,f.Name)));}catch{return false;}}
 public static List<ModItem> Scan(Game g){var items=new List<ModItem>();if(g==null||String.IsNullOrEmpty(g.Exe)||!File.Exists(g.Exe))return items;string root=Path.GetDirectoryName(g.Exe);Action<string,string,string,string> add=(id,name,file,repo)=>items.Add(new ModItem{Game=g,Id=id,Name=name,File=file,Version=Version(file),Repo=repo});
 foreach(string n in RenoDx.Loaders(root))add("reshade","ReShade",Path.Combine(root,n),"crosire/reshade");
 var hdr=RenoDx.HdrAddons(g);foreach(string file in RenoDx.AllAddons(g)){string name=Path.GetFileName(file);if(name.Equals(MfgAddon.Name,StringComparison.OrdinalIgnoreCase))add("mfg","MFG Unlock",file,MfgAddon.Repo);else if(hdr.Contains(file,StringComparer.OrdinalIgnoreCase))add("renodx","RenoDX HDR · "+name,file,"clshortfuse/renodx");else if(!name.Equals("AutoHDR.addon64",StringComparison.OrdinalIgnoreCase))add("addon",Appearance.Localize("Manual add-on")+" · "+name,file,"");}
 foreach(string n in AsiLoader.Installed(g))add("asi","ASI Loader · "+n,Path.Combine(root,n),AsiLoader.Repo);
 foreach(string n in new[]{"UE4SS.dll","ue4ss/UE4SS.dll"})if(DlssCore.Pe64(DlssCore.Safe(root,n)))add("ue4ss","UE4SS",DlssCore.Safe(root,n),"UE4SS-RE/RE-UE4SS");
 foreach(var effect in EffectCatalog.All){string marker="hdr-unlock-effects-"+effect.Id+".json";if(Recorded(g,marker)||effect.Addon&&DlssCore.Pe64(DlssCore.Safe(root,"AutoHDR.addon64"))){var item=new ModItem{Game=g,Id="effect",Name=effect.Name,Effect=effect,Repo=effect.Repo,Marker=marker};try{item.Version=DlssCore.ReadManifest(root,marker).Release??"";}catch{}items.Add(item);}}
 try{var scan=DlssCore.Inspect(g,false,false);if(scan.Proxy!=""){var build=DlssBuild.All.FirstOrDefault(b=>b.Id==scan.Build);add("opti","OptiScaler",Path.Combine(root,scan.Proxy),build==null?"":build.Repo);if(scan.Managed)items.Last().Version=DlssCore.ReadManifest(root).Release;}if(DlssCore.Pe64(scan.Runtime))add("nr","Neural Rendering",scan.Runtime,"RankFTW/rhi-repo");}catch{}
 foreach(var dll in DlssLibraries.Scan(g)){var item=new ModItem{Game=g,Id="native",Name=dll.File,File=dll.Path,Version=dll.Version,Library=dll};items.Add(item);}
 foreach(var group in Streamline.Scan(g).GroupBy(f=>Path.GetDirectoryName(f.Path),StringComparer.OrdinalIgnoreCase)){items.Add(new ModItem{Game=g,Id="streamline",Name="Streamline",File=group.Key,Version=group.First().Version,Repo=Streamline.Repo});}
 return items;
 }
 static void AddDelete(DlssPlan p,string name){string path=DlssCore.Safe(p.Folder,name);if(File.Exists(path)&&!p.Changes.Any(c=>c.Name.Equals(name,StringComparison.OrdinalIgnoreCase)))p.Changes.Add(new DlssChange{Name=name,Delete=true,Expected=DlssCore.Hash(path)});}
 public static DlssPlan Remove(ModItem item){var g=item.Game;Core.Closed(g);if(g.ProtectedInstall)throw new Exception(g.Evidence);string root=Path.GetDirectoryName(Path.GetFullPath(g.Exe));var p=new DlssPlan{Folder=root,Uninstall=true,Summary=g.Name+"\n"+Appearance.Localize("Remove only this component; dependent mods remain on disk and may need it reinstalled.")+"\n"+item.Name};
 if(item.Id=="native")return DlssLibraries.Restore(g,item.Library);
 if(item.Id=="streamline")return Streamline.Restore(g,item.File);
 if(item.Id=="effect"){if(item.Effect.Addon){if(DlssCore.Pe64(DlssCore.Safe(root,"AutoHDR.addon64")))AddDelete(p,"AutoHDR.addon64");AddDelete(p,item.Marker);return p;}var m=DlssCore.ReadManifest(root,item.Marker);string shaderPrefix="reshade-shaders/HDRUnlock-"+item.Effect.Id;foreach(var f in m.Files){if(f.Name.Replace('\\','/').StartsWith(shaderPrefix+"/",StringComparison.OrdinalIgnoreCase))AddDelete(p,f.Name);else if(f.Name.EndsWith(".ini",StringComparison.OrdinalIgnoreCase)){string path=DlssCore.Safe(root,f.Name);if(!File.Exists(path))continue;string ini=File.ReadAllText(path);foreach(string key in new[]{"EffectSearchPaths","TextureSearchPaths"}){string expected=".\\"+shaderPrefix.Replace('/','\\')+"\\"+(key=="EffectSearchPaths"?"Shaders":"Textures")+"\\**";ini=Core.Set(ini,"GENERAL",key,String.Join(",",(Core.Get(ini,"GENERAL",key)??"").Split(',').Where(x=>!String.Equals(x,expected,StringComparison.OrdinalIgnoreCase))));}p.Changes.Add(new DlssChange{Name=f.Name,Bytes=new UTF8Encoding(false).GetBytes(ini),Expected=DlssCore.Hash(path)});}}AddDelete(p,item.Marker);return p;}
 if(item.Id=="opti"){p=ComponentCleanup.Prepare(g,false,true);p.Changes.RemoveAll(c=>c.Name=="nvngx_dlssnr.dll"||c.Name==NrModels.Marker);string compatibility=DlssCore.Safe(root,"nvngx.dll_dlssnr.dll");if(DlssCore.Pe64(compatibility))AddDelete(p,"nvngx.dll_dlssnr.dll");if(File.Exists(DlssCore.Safe(root,DlssCore.Marker))){var owned=DlssCore.ReadManifest(root);foreach(var f in owned.Files.Where(f=>f.Name.Replace('\\','/').StartsWith("OptiScaler/",StringComparison.OrdinalIgnoreCase))){string path=DlssCore.Safe(root,f.Name);if(File.Exists(path)){if(DlssCore.Hash(path)!=f.After)throw new Exception("Modified OptiScaler file: "+f.Name);AddDelete(p,f.Name);}}}p.Summary=g.Name+"\n"+Appearance.Localize("Remove OptiScaler. Native DLSS, Neural Rendering models and other mods are preserved.");if(ModRemoval.Linked(g)){string from=DlssCore.Safe(root,"ReShade64.dll"),target=DlssCore.Safe(root,"dxgi.dll");if(File.Exists(target)&&!p.Changes.Any(c=>c.Name.Equals("dxgi.dll",StringComparison.OrdinalIgnoreCase)&&c.Delete))throw new Exception(Appearance.Localize("Cannot preserve ReShade: dxgi.dll belongs to another component."));p.Changes.RemoveAll(c=>c.Name.Equals("dxgi.dll",StringComparison.OrdinalIgnoreCase));p.Changes.Add(new DlssChange{Name="dxgi.dll",Source=from,SourceHash=DlssCore.Hash(from),Expected=File.Exists(target)?DlssCore.Hash(target):null});string oldConfig=DlssCore.Safe(root,"ReShade64.ini");if(!File.Exists(DlssCore.Safe(root,"ReShade.ini"))&&File.Exists(oldConfig)){string newConfig=DlssCore.Safe(root,"dxgi.ini");if(File.Exists(newConfig))throw new Exception("Existing dxgi.ini must be reviewed before moving ReShade.");p.Changes.Add(new DlssChange{Name="dxgi.ini",Source=oldConfig,SourceHash=DlssCore.Hash(oldConfig)});AddDelete(p,"ReShade64.ini");}AddDelete(p,"ReShade64.dll");AddDelete(p,RenoDx.Marker);AddDelete(p,RenoDx.KeyMarker);p.Summary+="\nReShade64.dll → dxgi.dll";}return p;}
 if(item.Id=="nr"){string iniPath=DlssCore.Safe(root,"OptiScaler.ini");if(File.Exists(iniPath)){string ini=Core.Set(File.ReadAllText(iniPath),"DlssNr","Enabled","false");p.Changes.Add(new DlssChange{Name="OptiScaler.ini",Bytes=new UTF8Encoding(false).GetBytes(ini),Expected=DlssCore.Hash(iniPath)});}AddDelete(p,NrModels.Marker);}
 if(item.Id=="reshade"){string iniPath=DlssCore.Safe(root,"OptiScaler.ini");if(File.Exists(iniPath)){string ini=Core.Set(File.ReadAllText(iniPath),"Plugins","LoadReshade","false");p.Changes.Add(new DlssChange{Name="OptiScaler.ini",Bytes=new UTF8Encoding(false).GetBytes(ini),Expected=DlssCore.Hash(iniPath)});}AddDelete(p,RenoDx.Marker);AddDelete(p,RenoDx.KeyMarker);}
 if(item.Id=="renodx")AddDelete(p,RenoDx.AddonMarker);
 if(item.Id=="mfg"){string name=MfgAddon.ConfigName(root),path=DlssCore.Safe(root,name);if(File.Exists(path)){string ini=MfgAddon.EarlyLoad(File.ReadAllText(path),false);p.Changes.Add(new DlssChange{Name=name,Bytes=new UTF8Encoding(false).GetBytes(ini),Expected=DlssCore.Hash(path)});}AddDelete(p,MfgAddon.Marker);}
 if(item.Id=="asi")AddDelete(p,AsiLoader.Marker);
 if(item.Id=="ue4ss"){if(File.Exists(DlssCore.Safe(root,Ue4ssInstaller.Marker))){var m=DlssCore.ReadManifest(root,Ue4ssInstaller.Marker);foreach(var f in m.Files.Where(f=>f.Name.EndsWith("dwmapi.dll",StringComparison.OrdinalIgnoreCase))){string path=DlssCore.Safe(root,f.Name);if(File.Exists(path)&&DlssCore.Hash(path)==f.After)AddDelete(p,f.Name);}AddDelete(p,Ue4ssInstaller.Marker);}}
 string full=Path.GetFullPath(item.File),prefix=root.TrimEnd('\\')+"\\";if(!full.StartsWith(prefix,StringComparison.OrdinalIgnoreCase))throw new Exception("Component outside game folder.");AddDelete(p,full.Substring(prefix.Length));if(p.Changes.Count==0)throw new Exception("No component files found.");return p;
 }
}
}
