using System;using System.IO;using System.Linq;using System.Net;using System.Collections.Generic;using System.Text.RegularExpressions;using System.Threading.Tasks;
namespace HdrPilot {
public static class ModUpdates {
 public static readonly List<ModItem> Items=new List<ModItem>();public static bool Checking;static Game[] pending;static bool cachedOnly;static readonly List<Action> reconciliations=new List<Action>();public static event Action Changed;
 static readonly Dictionary<string,string> binaryHashes=new Dictionary<string,string>();
 static readonly Dictionary<string,string> responses=new Dictionary<string,string>();static readonly Dictionary<string,string> failures=new Dictionary<string,string>();
 sealed class MetadataClient:WebClient {protected override WebRequest GetWebRequest(Uri address){var request=base.GetWebRequest(address);request.Timeout=8000;var http=request as HttpWebRequest;if(http!=null)http.ReadWriteTimeout=8000;return request;}}
 public static Func<string,string> FetchText;
 public static string Read(string url){string text;if(responses.TryGetValue(url,out text))return text;if(failures.TryGetValue(url,out text))throw new Exception(text);if(cachedOnly)throw new Exception("Not checked");if(FetchText!=null){text=FetchText(url);responses[url]=text;return text;}ServicePointManager.SecurityProtocol|=SecurityProtocolType.Tls12;using(var web=new MetadataClient()){web.Headers[HttpRequestHeader.UserAgent]="HDLSS";web.Headers[HttpRequestHeader.CacheControl]="no-cache";try{text=ApiMetadata.Handles(url)?ApiMetadata.Get(url):web.DownloadString(url);}catch(Exception ex){var we=ex as WebException;var response=we==null?null:we.Response as HttpWebResponse;string message=response!=null&&(int)response.StatusCode>=500?Appearance.Localize("Update server temporarily unavailable. Try Check again later.")+" (HTTP "+(int)response.StatusCode+")":ex.Message;failures[url]=message;throw new IOException(message,ex);}}responses[url]=text;return text;}
 static Dictionary<string,object> Object(string url){return Core.Json.Deserialize<Dictionary<string,object>>(Read(url));}
 static int[] Numbers(string value){var m=Regex.Match(value??"",@"\d+(?:\.\d+){1,3}");if(!m.Success)return null;var result=new int[4];var parts=m.Value.Split('.');for(int j=0;j<parts.Length;j++)if(!Int32.TryParse(parts[j],out result[j]))return null;return result;}
 public static bool Newer(string latest,string current){var x=Numbers(latest);var y=Numbers(current);if(x==null||y==null)return false;for(int j=0;j<4;j++)if(x[j]!=y[j])return x[j]>y[j];return false;}
 public static void Check(ModItem i){i.UpdateAvailable=false;i.Latest="";i.Status="Version check unavailable";string latest="";
 if(i.Id=="addon"){i.Status=RenoDx.AddonPage(i.File)!=null?"Nexus Mods: assisted update":"Manual update: source not linked";return;}
 else if(i.Id=="reshade"&&RenoDx.InstalledChannel(i.Game)=="nightly"){var runs=Object("https://api.github.com/repos/crosire/reshade/actions/workflows/build.yml/runs?branch=main&event=push&status=success&per_page=1");var run=((System.Collections.IEnumerable)runs["workflow_runs"]).Cast<Dictionary<string,object>>().First();i.Latest=Convert.ToString(run["head_sha"]);i.Status="Installed revision unknown";return;}
 else if(i.Id=="reshade")latest=RenoDx.StableVersion(Read("https://reshade.me/"));
 else if(i.Id=="native")latest=DllCatalog.Parse(Read(DllCatalog.ManifestUrl),i.Library.File).First().Version;
 else if(i.Id=="renodx"){var selected=RenoDx.ResolveGame(Read(RenoDx.CatalogUrl),i.Game.Name);var uri=new Uri(selected.Url);if(!String.Equals(Path.GetFileName(uri.AbsolutePath),Path.GetFileName(i.File),StringComparison.OrdinalIgnoreCase)){i.Status="Version check unavailable";return;}if(uri.Host!="github.com"){string hash=PublishedHash(uri);i.UpdateAvailable=!DlssCore.Hash(i.File).Equals(hash,StringComparison.OrdinalIgnoreCase);i.Status=i.UpdateAvailable?"Update available":"Up to date";return;}var split=uri.AbsolutePath.Split('/');string repo=split[1]+"/"+split[2];var a=RenoDx.PickAddon(Read("https://api.github.com/repos/"+repo+"/releases?per_page=20"),Path.GetFileName(i.File));if(a==null)throw new Exception("No matching release asset.");string digest=a.ContainsKey("digest")?Convert.ToString(a["digest"]):"";i.Latest=Convert.ToString(a["updated_at"]);if(!digest.StartsWith("sha256:"))throw new Exception("No comparable published checksum.");i.UpdateAvailable=!DlssCore.Hash(i.File).Equals(digest.Substring(7),StringComparison.OrdinalIgnoreCase);i.Status=i.UpdateAvailable?"Update available":"Up to date";return;}
 else if(i.Id=="effect"&&!i.Effect.Addon){latest=Convert.ToString(Object("https://api.github.com/repos/"+i.Repo+"/commits/"+i.Effect.Branch)["sha"]);i.Latest=latest.Substring(0,Math.Min(12,latest.Length));i.UpdateAvailable=!String.IsNullOrEmpty(i.Version)&&i.Version!=latest;i.Status=String.IsNullOrEmpty(i.Version)?"Installed revision unknown":i.UpdateAvailable?"Update available":"Up to date";return;}
 else if(i.Id=="opti"){var build=DlssBuild.All.FirstOrDefault(x=>x.Repo==i.Repo);if(build==null)throw new Exception("Unknown OptiScaler build.");latest=DlssCore.PickRelease(Read("https://api.github.com/repos/"+i.Repo+"/releases?per_page=10"),build).Tag;}
 else if(i.Id=="nr"){var models=NrModels.Parse(Read(NrModels.Api));var model=models.FirstOrDefault(m=>i.Version.IndexOf("SF",StringComparison.OrdinalIgnoreCase)>=0?m.Community:!m.Community);if(model==null)throw new Exception("No matching model family.");latest=model.Tag;}
 else {var r=Object("https://api.github.com/repos/"+i.Repo+"/releases/latest");if(Convert.ToBoolean(r["draft"])||Convert.ToBoolean(r["prerelease"]))throw new Exception("No stable release.");latest=Convert.ToString(r["tag_name"]);if(i.Id=="mfg"||i.Id=="effect"){string name=i.Id=="mfg"?MfgAddon.Name:"AutoHDR.addon64";var a=((System.Collections.IEnumerable)r["assets"]).Cast<Dictionary<string,object>>().Single(x=>Convert.ToString(x["name"])==name);string digest=a.ContainsKey("digest")?Convert.ToString(a["digest"]):"",path=i.Id=="mfg"?i.File:Path.Combine(Path.GetDirectoryName(i.Game.Exe),name);if(digest.StartsWith("sha256:")&&File.Exists(path)){i.Latest=latest;i.UpdateAvailable=!DlssCore.Hash(path).Equals(digest.Substring(7),StringComparison.OrdinalIgnoreCase);i.Status=i.UpdateAvailable?"Update available":"Up to date";return;}}}
 i.Latest=latest;i.UpdateAvailable=Newer(latest,i.Version);i.Status=Numbers(i.Version)==null?"Installed revision unknown":Numbers(latest)==null?"Version check unavailable":i.UpdateAvailable?"Update available":"Up to date";
 }
 public static string PublishedHash(Uri uri){
 if(uri.Scheme!="https"||!uri.IsDefaultPort||!String.IsNullOrEmpty(uri.UserInfo)||!Regex.IsMatch(uri.Host,@"^[a-zA-Z0-9-]+\.github\.io$")||!Regex.IsMatch(uri.AbsolutePath,@"^/renodx/renodx-[a-zA-Z0-9_-]+\.addon64$")||uri.Query.Length!=0)throw new IOException("Unsupported RenoDX source.");
 string hash;if(binaryHashes.TryGetValue(uri.AbsoluteUri,out hash))return hash;
 if(cachedOnly)throw new Exception("Not checked");string temp=Path.GetTempFileName();try{
 ServicePointManager.SecurityProtocol|=SecurityProtocolType.Tls12;
 var request=(HttpWebRequest)WebRequest.Create(uri);request.UserAgent="HDLSS/1.0.8";request.Timeout=10000;request.ReadWriteTimeout=10000;request.AllowAutoRedirect=false;
 var received=(HttpWebResponse)request.GetResponse();
 if((int)received.StatusCode==301||(int)received.StatusCode==302||(int)received.StatusCode==307||(int)received.StatusCode==308){string location=received.Headers["Location"];received.Dispose();Uri target;if(!Uri.TryCreate(location,UriKind.Absolute,out target)||target.Scheme!="https"||target.Host!="renodx.com"||!target.IsDefaultPort||target.UserInfo.Length!=0||target.Query.Length!=0||target.AbsolutePath!="/"+Path.GetFileName(uri.AbsolutePath))throw new IOException("Unexpected RenoDX redirect.");request=(HttpWebRequest)WebRequest.Create(target);request.UserAgent="HDLSS/1.0.8";request.Timeout=10000;request.ReadWriteTimeout=10000;request.AllowAutoRedirect=false;received=(HttpWebResponse)request.GetResponse();}
 using(var response=received){
 if(response.StatusCode!=HttpStatusCode.OK||response.ContentLength>67108864)throw new IOException("Invalid RenoDX download response.");
 using(var input=response.GetResponseStream())using(var output=File.Create(temp)){byte[] buffer=new byte[81920];int n;long total=0;var timer=System.Diagnostics.Stopwatch.StartNew();while((n=input.Read(buffer,0,buffer.Length))>0){total+=n;if(total>67108864||timer.Elapsed.TotalSeconds>30)throw new IOException("RenoDX download limit exceeded.");output.Write(buffer,0,n);}if(response.ContentLength>=0&&total!=response.ContentLength)throw new IOException("Incomplete RenoDX download.");}}
 if(!DlssCore.Pe64(temp))throw new IOException("Invalid RenoDX x64 download.");hash=DlssCore.Hash(temp);binaryHashes[uri.AbsoluteUri]=hash;return hash;
 }finally{File.Delete(temp);}
 }
 static bool Same(ModItem a,ModItem b){return a.Id==b.Id&&a.Name==b.Name&&String.Equals(a.File,b.File,StringComparison.OrdinalIgnoreCase);}
 public static void AfterApply(Game game,DlssPlan plan){if(Checking){reconciliations.Add(()=>AfterApply(game,plan));return;}var previous=Items.Where(x=>String.Equals(x.Game.Exe,game.Exe,StringComparison.OrdinalIgnoreCase)).ToList();var fresh=ModInventory.Scan(game);cachedOnly=true;try{foreach(var item in fresh){var old=previous.FirstOrDefault(x=>Same(x,item));bool affected=old==null||old.Version!=item.Version||plan.Changes.Any(c=>!String.IsNullOrEmpty(item.File)&&(String.Equals(DlssCore.Safe(plan.Folder,c.Name),item.File,StringComparison.OrdinalIgnoreCase)||item.Id=="streamline"&&String.Equals(Path.GetDirectoryName(DlssCore.Safe(plan.Folder,c.Name)),item.File,StringComparison.OrdinalIgnoreCase)))||item.Id=="effect"&&item.Marker==plan.MarkerName;if(!affected){item.Status=old.Status;item.Latest=old.Latest;item.UpdateAvailable=old.UpdateAvailable;}else{try{Check(item);}catch{item.Status="Not checked";item.Latest="";item.UpdateAvailable=false;}}}}finally{cachedOnly=false;}Items.RemoveAll(x=>String.Equals(x.Game.Exe,game.Exe,StringComparison.OrdinalIgnoreCase));Items.AddRange(fresh);if(Changed!=null)Changed();}
 public static async Task Refresh(IEnumerable<Game> games){if(Checking){pending=games.ToArray();return;}Checking=true;var copy=games.ToArray();if(Changed!=null)Changed();try{var found=await Task.Run(()=>{responses.Clear();failures.Clear();binaryHashes.Clear();var list=new List<ModItem>();var reported=new HashSet<string>();foreach(var g in copy){try{list.AddRange(ModInventory.Scan(g));}catch{}}foreach(var i in list){try{Check(i);}catch(Exception ex){i.Status="Version check unavailable";i.Latest="";if(reported.Add(ex.Message))ActivityLog.Write("Update check · "+i.Name+" · "+ex.Message);}}return list;});Items.RemoveAll(i=>copy.Any(g=>String.Equals(g.Exe,i.Game.Exe,StringComparison.OrdinalIgnoreCase)));Items.AddRange(found);}finally{Checking=false;if(Changed!=null)Changed();}var queued=reconciliations.ToArray();reconciliations.Clear();foreach(var action in queued)action();if(pending!=null){var again=pending;pending=null;await Refresh(again);}}
}
}
