using System;using System.IO;using System.Linq;using System.Net;using System.Collections.Generic;using System.Text.RegularExpressions;using System.Threading.Tasks;
namespace HdrPilot {
public static class ModUpdates {
 public static readonly List<ModItem> Items=new List<ModItem>();public static bool Checking;static Game[] pending;public static event Action Changed;
 static readonly Dictionary<string,string> responses=new Dictionary<string,string>();static readonly Dictionary<string,string> failures=new Dictionary<string,string>();
 sealed class MetadataClient:WebClient {protected override WebRequest GetWebRequest(Uri address){var request=base.GetWebRequest(address);request.Timeout=8000;var http=request as HttpWebRequest;if(http!=null)http.ReadWriteTimeout=8000;return request;}}
 public static Func<string,string> FetchText;
 public static string Read(string url){string text;if(responses.TryGetValue(url,out text))return text;if(failures.TryGetValue(url,out text))throw new Exception(text);if(FetchText!=null)return FetchText(url);ServicePointManager.SecurityProtocol|=SecurityProtocolType.Tls12;using(var web=new MetadataClient()){web.Headers[HttpRequestHeader.UserAgent]="HDLSS";web.Headers[HttpRequestHeader.CacheControl]="no-cache";try{text=ApiMetadata.Handles(url)?ApiMetadata.Get(url):web.DownloadString(url);}catch(Exception ex){failures[url]=ex.Message;throw;}}responses[url]=text;return text;}
 static Dictionary<string,object> Object(string url){return Core.Json.Deserialize<Dictionary<string,object>>(Read(url));}
 static int[] Numbers(string value){var m=Regex.Match(value??"",@"\d+(?:\.\d+){1,3}");if(!m.Success)return null;var result=new int[4];var parts=m.Value.Split('.');for(int j=0;j<parts.Length;j++)if(!Int32.TryParse(parts[j],out result[j]))return null;return result;}
 public static bool Newer(string latest,string current){var x=Numbers(latest);var y=Numbers(current);if(x==null||y==null)return false;for(int j=0;j<4;j++)if(x[j]!=y[j])return x[j]>y[j];return false;}
 public static void Check(ModItem i){i.UpdateAvailable=false;i.Latest="";i.Status="Version check unavailable";string latest="";
 if(i.Id=="addon"){i.Status=RenoDx.AddonPage(i.File)!=null?"Nexus Mods: assisted update":"Manual update: source not linked";return;}
 else if(i.Id=="reshade"&&RenoDx.InstalledChannel(i.Game)=="nightly"){var runs=Object("https://api.github.com/repos/crosire/reshade/actions/workflows/build.yml/runs?branch=main&event=push&status=success&per_page=1");var run=((System.Collections.IEnumerable)runs["workflow_runs"]).Cast<Dictionary<string,object>>().First();i.Latest=Convert.ToString(run["head_sha"]);i.Status="Installed revision unknown";return;}
 else if(i.Id=="reshade")latest=RenoDx.StableVersion(Read("https://reshade.me/"));
 else if(i.Id=="native")latest=DllCatalog.Parse(Read(DllCatalog.ManifestUrl),i.Library.File).First().Version;
 else if(i.Id=="renodx"){var selected=RenoDx.ResolveGame(Read(RenoDx.CatalogUrl),i.Game.Name);var uri=new Uri(selected.Url);if(uri.Host!="github.com")throw new Exception("The author does not publish comparable release metadata.");var split=uri.AbsolutePath.Split('/');string repo=split[1]+"/"+split[2];var a=RenoDx.PickAddon(Read("https://api.github.com/repos/"+repo+"/releases?per_page=20"),Path.GetFileName(i.File));if(a==null)throw new Exception("No matching release asset.");string digest=a.ContainsKey("digest")?Convert.ToString(a["digest"]):"";i.Latest=Convert.ToString(a["updated_at"]);if(!digest.StartsWith("sha256:"))throw new Exception("No comparable published checksum.");i.UpdateAvailable=!DlssCore.Hash(i.File).Equals(digest.Substring(7),StringComparison.OrdinalIgnoreCase);i.Status=i.UpdateAvailable?"Update available":"Up to date";return;}
 else if(i.Id=="effect"&&!i.Effect.Addon){latest=Convert.ToString(Object("https://api.github.com/repos/"+i.Repo+"/commits/"+i.Effect.Branch)["sha"]);i.Latest=latest.Substring(0,Math.Min(12,latest.Length));i.UpdateAvailable=!String.IsNullOrEmpty(i.Version)&&i.Version!=latest;i.Status=String.IsNullOrEmpty(i.Version)?"Installed revision unknown":i.UpdateAvailable?"Update available":"Up to date";return;}
 else if(i.Id=="opti"){var build=DlssBuild.All.FirstOrDefault(x=>x.Repo==i.Repo);if(build==null)throw new Exception("Unknown OptiScaler build.");latest=DlssCore.PickRelease(Read("https://api.github.com/repos/"+i.Repo+"/releases?per_page=10"),build).Tag;}
 else if(i.Id=="nr"){var models=NrModels.Parse(Read(NrModels.Api));var model=models.FirstOrDefault(m=>i.Version.IndexOf("SF",StringComparison.OrdinalIgnoreCase)>=0?m.Community:!m.Community);if(model==null)throw new Exception("No matching model family.");latest=model.Tag;}
 else {var r=Object("https://api.github.com/repos/"+i.Repo+"/releases/latest");if(Convert.ToBoolean(r["draft"])||Convert.ToBoolean(r["prerelease"]))throw new Exception("No stable release.");latest=Convert.ToString(r["tag_name"]);if(i.Id=="mfg"||i.Id=="effect"){string name=i.Id=="mfg"?MfgAddon.Name:"AutoHDR.addon64";var a=((System.Collections.IEnumerable)r["assets"]).Cast<Dictionary<string,object>>().Single(x=>Convert.ToString(x["name"])==name);string digest=a.ContainsKey("digest")?Convert.ToString(a["digest"]):"",path=i.Id=="mfg"?i.File:Path.Combine(Path.GetDirectoryName(i.Game.Exe),name);if(digest.StartsWith("sha256:")&&File.Exists(path)){i.Latest=latest;i.UpdateAvailable=!DlssCore.Hash(path).Equals(digest.Substring(7),StringComparison.OrdinalIgnoreCase);i.Status=i.UpdateAvailable?"Update available":"Up to date";return;}}}
 i.Latest=latest;i.UpdateAvailable=Newer(latest,i.Version);i.Status=Numbers(i.Version)==null?"Installed revision unknown":Numbers(latest)==null?"Version check unavailable":i.UpdateAvailable?"Update available":"Up to date";
 }
 public static async Task Refresh(IEnumerable<Game> games){if(Checking){pending=games.ToArray();return;}Checking=true;var copy=games.ToArray();if(Changed!=null)Changed();try{var found=await Task.Run(()=>{responses.Clear();failures.Clear();var list=new List<ModItem>();var reported=new HashSet<string>();foreach(var g in copy){try{list.AddRange(ModInventory.Scan(g));}catch{}}foreach(var i in list){try{Check(i);}catch(Exception ex){i.Status="Version check unavailable";i.Latest="";if(reported.Add(ex.Message))ActivityLog.Write("Update check · "+i.Name+" · "+ex.Message);}}return list;});Items.Clear();Items.AddRange(found);}finally{Checking=false;if(Changed!=null)Changed();}if(pending!=null){var again=pending;pending=null;await Refresh(again);}}
}
}
