using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Windows;
using System.Windows.Controls;
using System.Threading.Tasks;
namespace HdrPilot {
public sealed class NrModel {public string Tag,Url,Digest;public bool Community;public override string ToString(){return Tag.Replace("dlssnr-","")+" · "+(Community?"community / compatibilità":"originale RTX 5000");}}
public static class NrModels {
 public const string Marker="hdr-unlock-nr-model.json",Api="https://api.github.com/repos/RankFTW/rhi-repo/releases?per_page=100";
 public static List<NrModel> Parse(string json){var rows=Core.Json.Deserialize<List<Dictionary<string,object>>>(json);var result=new List<NrModel>();foreach(var row in rows.OrderByDescending(r=>r.ContainsKey("published_at")?Convert.ToString(r["published_at"]):"",StringComparer.Ordinal)){string tag=Convert.ToString(row["tag_name"]);if(!Regex.IsMatch(tag,@"^dlssnr-[0-9][a-zA-Z0-9.\-]*$")||Convert.ToBoolean(row["draft"]))continue;foreach(var asset in ((System.Collections.IEnumerable)row["assets"]).Cast<Dictionary<string,object>>()){string url=Convert.ToString(asset["browser_download_url"]),name=Convert.ToString(asset["name"]),digest=asset.ContainsKey("digest")?Convert.ToString(asset["digest"]):"";if(!name.EndsWith(".zip")||!url.StartsWith("https://github.com/RankFTW/rhi-repo/releases/download/"+tag+"/",StringComparison.Ordinal)||!Regex.IsMatch(digest,@"^sha256:[a-fA-F0-9]{64}$"))continue;result.Add(new NrModel{Tag=tag,Url=url,Digest=digest.Substring(7),Community=tag.IndexOf("SF",StringComparison.OrdinalIgnoreCase)>=0||tag.IndexOf("RTX40",StringComparison.OrdinalIgnoreCase)>=0});break;}if(result.Count==10)break;}return result;}
 public static List<NrModel> Fetch(){ServicePointManager.SecurityProtocol|=SecurityProtocolType.Tls12;using(var web=new DlssCore.DownloadClient()){web.Headers[HttpRequestHeader.UserAgent]="HDR-Unlock/0.1";return Parse(web.DownloadString(Api));}}
 public static NrModel SelectAutomatic(List<NrModel> models,int series){
  if(series!=40&&series!=50)throw new Exception("GPU RTX 4000/5000 non rilevata: impossibile scegliere automaticamente il modello.");
  var chosen=models.FirstOrDefault(m=>series==40?m.Community:!m.Community);
  if(chosen==null)throw new Exception("Nessun modello NR adatto alla GPU disponibile nel repository.");Compatible(chosen,series);return chosen;
 }
 public static string EnsureRuntime(bool enabled,string existing,int series,Action<string> progress,out string origin){
  origin="";if(!enabled)return existing;
  if(DlssCore.Pe64(existing)){progress("Modello NR presente: riutilizzo il file esistente.");return existing;}
  progress("Cerco automaticamente il modello NR per RTX "+series+"00…");
  var model=SelectAutomatic(Fetch(),series);ActivityLog.Write("Modello NR automatico: "+model.Tag+" · "+model.Url);
  string file=Download(model,progress);origin="Modello NR selezionato automaticamente: "+model.Tag+"\nRepository community RankFTW/rhi-repo\n"+model.Url+"\nSHA256 archivio: "+model.Digest;
  ActivityLog.Write("Modello NR scaricato e verificato. Verrà applicato insieme alla build con backup.");return file;
 }
 public static void Compatible(NrModel m,int series){if(series!=40&&series!=50)throw new Exception("GPU non rilevata: scegli la serie nel pannello DLSS 5.");if(series==40&&!m.Community)throw new Exception("Il modello originale richiede RTX 5000. Scegli una variante di compatibilità per RTX 4000.");if(series==50&&m.Tag.IndexOf("RTX40",StringComparison.OrdinalIgnoreCase)>=0)throw new Exception("Questa variante è indicata per RTX 4000. Per RTX 5000 scegli l’originale o una variante SF documentata.");}
 public static string Extract(NrModel m,string archive,string dir){if(!DlssCore.Hash(archive).Equals(m.Digest,StringComparison.OrdinalIgnoreCase))throw new Exception("Hash del pacchetto NR non corrispondente alla release.");Directory.CreateDirectory(dir);string dest=Path.Combine(dir,"nvngx_dlssnr.dll");using(var file=File.OpenRead(archive))using(var zip=new ZipArchive(file,ZipArchiveMode.Read)){var entries=zip.Entries.Where(e=>Path.GetFileName(e.FullName).Equals("nvngx_dlssnr.dll",StringComparison.OrdinalIgnoreCase)).ToList();if(entries.Count!=1||entries[0].Length>300000000)throw new Exception("Il pacchetto non contiene un singolo modello NR valido.");using(var input=entries[0].Open())using(var output=File.Create(dest))input.CopyTo(output);}if(!DlssCore.Pe64(dest))throw new Exception("Modello NR non x64.");return dest;}
 public static string Download(NrModel model,Action<string> progress){if(!model.Url.StartsWith("https://github.com/RankFTW/rhi-repo/releases/download/"+model.Tag+"/",StringComparison.Ordinal))throw new Exception("Origine del modello non valida.");ServicePointManager.SecurityProtocol|=SecurityProtocolType.Tls12;string dir=Path.Combine(Core.Data,"nr-models",Guid.NewGuid().ToString("N"));Directory.CreateDirectory(dir);string archive=Path.Combine(dir,"model.zip");progress("Scarico modello "+model.Tag+"…");using(var web=new DlssCore.DownloadClient()){web.Headers[HttpRequestHeader.UserAgent]="HDR-Unlock/0.1";web.DownloadFile(model.Url,archive);}string file=Extract(model,archive,dir);File.WriteAllText(Path.Combine(dir,"origine.txt"),model.Url+"\nSHA256 archivio "+model.Digest+"\nSHA256 modello "+DlssCore.Hash(file));return file;}
 public static DlssPlan Prepare(Game g,string file,NrModel model){if(!DlssCore.Pe64(file))throw new Exception("Modello NR non x64 o non leggibile.");var scan=DlssCore.Inspect(g);if(scan.Blockers.Count>0)throw new Exception(String.Join("\n",scan.Blockers));string marker=DlssCore.Safe(scan.Folder,Marker);var p=new DlssPlan{Folder=scan.Folder,MarkerName=Marker,MarkerExpected=File.Exists(marker)?DlssCore.Hash(marker):null,Summary=g.Name+"\nSolo modello Neural Rendering: "+model.Tag+"\nRepository community: RankFTW/rhi-repo\n"+model.Url+"\nSHA256 DLL: "+DlssCore.Hash(file)+"\nCompatibilità dichiarata dalla variante, da verificare nel gioco. Non vengono installati add-on o un secondo iniettore NR.",Manifest=File.Exists(marker)?DlssCore.ReadManifest(scan.Folder,Marker):new DlssManifest{Game=g.Id,Folder=scan.Folder,PreviousOwner="Modello NR precedente",BackupRoot="nr-backups/"+Guid.NewGuid().ToString("N")}};p.Changes.Add(new DlssChange{Name="nvngx_dlssnr.dll",Source=file,SourceHash=DlssCore.Hash(file),Expected=File.Exists(scan.Runtime)?DlssCore.Hash(scan.Runtime):null});return p;}
 public static DlssPlan Restore(Game g){string root=Path.GetDirectoryName(g.Exe);var m=DlssCore.ReadManifest(root,Marker);if(m.Files.Any(f=>f.Before==null)&&DlssCore.Inspect(g).Proxy!=""&&Core.Get(DlssCore.ReadIni(root),"DlssNr","Enabled")!="false")throw new Exception("Disattiva Neural Rendering in OptiScaler e salva prima di rimuovere il modello. Un modello precedente può invece essere ripristinato.");return RenoDx.Restore(g,Marker);}
 public static void Show(Window owner,Game game,int series,Action updated){StackPanel body;var d=Dialogs.Create(owner,"Neural Rendering · modello DLSS 5",out body);d.Width=940;d.FontSize=14;body.Children.Add(Dialogs.Text("Il file nvngx_dlssnr.dll contiene il modello. OptiScaler o un add-on NR per ReShade possono usarlo: installa un solo iniettore NR alla volta. ReShade per il solo HDR può restare attivo.",14));
  var list=new ComboBox{Margin=new Thickness(0,0,0,12)};body.Children.Add(list);var info=Dialogs.Text("Catalogo: repository community RankFTW/rhi-repo. Mostra fino a 10 varianti NR pubblicate; non sono le versioni SR/RR/FG. Le modifiche della community possono invalidare la firma originale NVIDIA: verifichiamo l’hash dell’archivio pubblicato, senza disattivare la protezione di Windows.",14);body.Children.Add(info);var row=new WrapPanel();body.Children.Add(row);bool busy=false;
  Action<DlssPlan> review=plan=>{StackPanel b;var w=Dialogs.Create(d,"Modello NR · verifica modifiche",out b);w.Width=840;b.Children.Add(new TextBox{Text=plan.ToString(),Height=310,IsReadOnly=true,TextWrapping=TextWrapping.Wrap,VerticalScrollBarVisibility=ScrollBarVisibility.Auto});var apply=new Button{Content="Applica con backup",Margin=new Thickness(0,12,0,0)};b.Children.Add(apply);w.Closing+=(sender,args)=>{if(!apply.IsEnabled)args.Cancel=true;};apply.Click+=async(s,e)=>{apply.IsEnabled=false;try{await Task.Run(()=>DlssCore.Apply(game,plan));apply.IsEnabled=true;w.Close();info.Text="Modello aggiornato. Backup conservato; verifica Neural Rendering nel menu del gioco.";updated();}catch(Exception ex){apply.IsEnabled=true;info.Text=ex.Message;w.Close();}};w.ShowDialog();};
  Action<string,Action> button=(title,action)=>{var b=new Button{Content=title,Margin=new Thickness(0,0,8,8)};b.Style=d.TryFindResource(title.StartsWith("Installa")?"Primary":title.StartsWith("Ripristina")?"RestoreAction":"InfoAction") as Style;b.Click+=(s,e)=>{try{action();}catch(Exception ex){info.Text=ex.Message;}};row.Children.Add(b);};
  button("Carica varianti dal repository",async()=>{busy=true;row.IsEnabled=false;try{var items=await Task.Run(()=>Fetch());list.ItemsSource=items;list.SelectedItem=items.FirstOrDefault(m=>series==40?m.Community:!m.Community);info.Text=items.Count+" varianti NR disponibili. RTX "+(series==40?"4000: variante di compatibilità.":"5000: originale consigliato.")+" Il modello presente resta invariato finché non installi.";}catch(Exception ex){info.Text=ex.Message;}finally{busy=false;row.IsEnabled=true;}});
  button("Installa modello scelto",async()=>{busy=true;row.IsEnabled=list.IsEnabled=false;try{var model=list.SelectedItem as NrModel;if(model==null)throw new Exception("Carica e scegli una variante.");Compatible(model,series);DlssHardware.Detect().Validate(series,"");Core.Closed(game);string file=await Task.Run(()=>Download(model,msg=>d.Dispatcher.Invoke(new Action(()=>info.Text=msg))));review(Prepare(game,file,model));}catch(Exception ex){info.Text=ex.Message;}finally{busy=false;row.IsEnabled=list.IsEnabled=true;}});
  button("Ripristina / rimuovi solo modello",()=>review(Restore(game)));
  body.Children.Add(Dialogs.Text("Ripristino: torna al modello presente prima del primo cambio. Se non esisteva, rimuove solo quello aggiunto. Le DLL dei loader e le versioni di SR/RR/FG restano separate.",14));d.Closing+=(s,e)=>{if(busy)e.Cancel=true;};d.ShowDialog();
 }
}
}
