using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Interop;
using System.Windows.Media;
using System.Windows.Shapes;
using System.Windows.Threading;

namespace HdrPilot {
public class Snapshot {
 public Dictionary<string,double> Values=new Dictionary<string,double>();public long Time;public long Sequence;
 public static Snapshot Parse(string text){var s=new Snapshot();var lines=text.Split('\n').Select(x=>x.Trim()).ToArray();if(!lines.Contains("HDRPILOT=1")||!lines.Contains("complete=1"))return null;foreach(string line in lines){int i=line.IndexOf('=');if(i<0)continue;string key=line.Substring(0,i),val=line.Substring(i+1);long l;double d;if(key=="time"&&Int64.TryParse(val,out l))s.Time=l;else if(key=="sequence"&&Int64.TryParse(val,out l))s.Sequence=l;else if(Double.TryParse(val,NumberStyles.Float,CultureInfo.InvariantCulture,out d)&&!Double.IsNaN(d)&&!Double.IsInfinity(d))s.Values[key]=d;}return s.Time>0?s:null;}
 public bool Fresh(){double now=(DateTime.UtcNow-new DateTime(1970,1,1)).TotalSeconds;return now-Time>=-2&&now-Time<=4;}
}
public sealed class ReaderState {
 public bool Ue4ss,Reader,Enabled,Listed,Fresh;public string Folder,Error="",Last="";
 public string Description {get{return Error!=""?Error:(Ue4ss?"UE4SS presente":"UE4SS non rilevato")+"\n"+(Reader?"Lettore HDLSS già installato (HDRPilotTelemetry)":"Lettore HDLSS non installato")+"\n"+(Listed?"Voce presente in mods.txt: controlla anche questa abilitazione.":Enabled?"Abilitazione configurata con enabled.txt":"Nessun file enabled.txt presente")+"\n"+(Fresh?"Dati recenti ricevuti dal lettore":"Nessun dato recente ricevuto")+(Last==""?"":"\nUltimo file di lettura: "+Last)+"\n"+(Folder??"");}}
}
public static class Telemetry {
 public static string ModFolder(Game g){return System.IO.Path.Combine(Ue4ssInstaller.RuntimeFolder(g),@"Mods\HDRPilotTelemetry");}
 public static ReaderState Inspect(Game g){var state=new ReaderState();if(g==null||String.IsNullOrEmpty(g.Exe)){state.Error="Seleziona un gioco e un target.exe valido.";return state;}try{state.Folder=ModFolder(g);string ue=System.IO.Path.GetDirectoryName(System.IO.Path.GetDirectoryName(state.Folder));state.Ue4ss=File.Exists(System.IO.Path.Combine(ue,"UE4SS.dll"));state.Reader=File.Exists(System.IO.Path.Combine(state.Folder,@"Scripts\main.lua"));state.Enabled=File.Exists(System.IO.Path.Combine(state.Folder,"enabled.txt"));string list=System.IO.Path.Combine(ue,@"Mods\mods.txt");state.Listed=File.Exists(list)&&System.Text.RegularExpressions.Regex.IsMatch(File.ReadAllText(list),@"(?im)^\s*HDRPilotTelemetry\s*:");string path=System.IO.Path.Combine(state.Folder,"telemetry.txt");if(File.Exists(path)){state.Last=File.GetLastWriteTime(path).ToString("g");using(var f=File.Open(path,FileMode.Open,FileAccess.Read,FileShare.ReadWrite|FileShare.Delete))using(var r=new StreamReader(f)){var snap=Snapshot.Parse(r.ReadToEnd());state.Fresh=snap!=null&&snap.Fresh();}}}catch(Exception ex){state.Error="Stato lettore non verificabile: "+ex.Message;}return state;}
 public static string Payload(){using(var s=Assembly.GetExecutingAssembly().GetManifestResourceStream("telemetry.lua"))using(var r=new StreamReader(s))return r.ReadToEnd();}
 public static void Install(Game g){Core.Closed(g);string ue=Ue4ssInstaller.RuntimeFolder(g);if(!File.Exists(System.IO.Path.Combine(ue,"UE4SS.dll")))throw new Exception("Installa prima una versione di UE4SS compatibile con questo gioco. HDLSS aggiunge solo il lettore di parametri; non sostituisce UE4SS o altre mod.");string folder=ModFolder(g),script=System.IO.Path.Combine(folder,@"Scripts\main.lua");if(Directory.Exists(folder))throw new Exception("Il modulo HDRPilotTelemetry è già presente. Nessun file sovrascritto.");Directory.CreateDirectory(System.IO.Path.GetDirectoryName(script));File.WriteAllText(script,Payload(),new UTF8Encoding(false));File.WriteAllText(System.IO.Path.Combine(folder,"enabled.txt"),"");}
 public static void Disable(Game g){Core.Closed(g);string f=System.IO.Path.Combine(ModFolder(g),"enabled.txt"),target=System.IO.Path.Combine(ModFolder(g),"disabled-by-hdr-pilot.txt");if(!File.Exists(f))return;if(File.Exists(target))throw new Exception("Il lettore risulta già disattivato.");File.Move(f,target);}
 public static void Enable(Game g){Core.Closed(g);string folder=ModFolder(g),f=System.IO.Path.Combine(folder,"enabled.txt"),disabled=System.IO.Path.Combine(folder,"disabled-by-hdr-pilot.txt");if(File.Exists(f))return;if(File.Exists(disabled)){File.Move(disabled,f);return;}Install(g);}
}
public class LiveOverlay:Window {
 Game game;string section;DispatcherTimer timer;TextBlock live,title,device;Dictionary<string,TextBlock> configured=new Dictionary<string,TextBlock>(),actual=new Dictionary<string,TextBlock>();Polyline graph;Canvas plot;Queue<double> history=new Queue<double>();long last=-1;int tick;
 Brush muted=new SolidColorBrush(Color.FromRgb(147,162,179)),lime=new SolidColorBrush(Color.FromRgb(230,172,80));
 [DllImport("user32.dll")]static extern int GetWindowLong(IntPtr h,int n);[DllImport("user32.dll")]static extern int SetWindowLong(IntPtr h,int n,int value);
 IntPtr handle;
 TextBlock Text(string text,double size,Brush color){return new TextBlock{Text=text,FontSize=size,Foreground=color,Margin=new Thickness(0,4,0,4)};}
 public LiveOverlay(Game g,string sec){game=g;section=sec;Title="HDLSS · overlay";FontFamily=new FontFamily("Cascadia Mono, Consolas");Width=430;Height=390;WindowStyle=WindowStyle.None;ResizeMode=ResizeMode.NoResize;AllowsTransparency=true;Background=Brushes.Transparent;Topmost=true;ShowInTaskbar=false;ShowActivated=false;Left=Math.Max(10,SystemParameters.WorkArea.Right-Width-24);Top=SystemParameters.WorkArea.Top+24;
  var outer=new Border{Background=new SolidColorBrush(Color.FromArgb(239,13,18,25)),BorderBrush=new SolidColorBrush(Color.FromRgb(110,96,45)),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(12),Padding=new Thickness(18)};var stack=new StackPanel();outer.Child=stack;Content=outer;
  stack.Children.Add(Text("HDLSS  /  PARAMETRI MOTORE",11,lime));title=Text(g.Name,13,Brushes.White);title.TextTrimming=TextTrimming.CharacterEllipsis;stack.Children.Add(title);live=Text("IN ATTESA DEL GIOCO / UE4SS",11,muted);stack.Children.Add(live);
  var grid=new Grid{Margin=new Thickness(0,8,0,6)};grid.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(1,GridUnitType.Star)});grid.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(100)});grid.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(105)});
  string[] keys={"header","max","mid","ui","black"};string[] names={"","Picco (nit)","Grigio 18% (nit)","Interfaccia (%)","Nero (nit)"};
  for(int i=0;i<keys.Length;i++){grid.RowDefinitions.Add(new RowDefinition{Height=new GridLength(29)});var name=Text(names[i],12,muted);Grid.SetRow(name,i);grid.Children.Add(name);var saved=Text(i==0?"SALVATO":"—",12,muted);saved.TextAlignment=TextAlignment.Right;Grid.SetColumn(saved,1);Grid.SetRow(saved,i);grid.Children.Add(saved);var read=Text(i==0?"IN GIOCO":"—",12,lime);read.TextAlignment=TextAlignment.Right;Grid.SetColumn(read,2);Grid.SetRow(read,i);grid.Children.Add(read);if(i>0){configured[keys[i]]=saved;actual[keys[i]]=read;}}
  stack.Children.Add(grid);device=Text("Formato uscita: non disponibile",11,muted);stack.Children.Add(device);stack.Children.Add(Text("PICCO CONFIGURATO NEL TEMPO · NON MISURA DEI PIXEL",9,muted));plot=new Canvas{Height=35,ClipToBounds=true,Background=new SolidColorBrush(Color.FromRgb(22,32,41))};graph=new Polyline{Stroke=lime,StrokeThickness=2};plot.Children.Add(graph);stack.Children.Add(plot);stack.Children.Add(Text(Shortcut.Label(Core.Pref.HotkeyMods,Core.Pref.HotkeyKey)+": mostra/nascondi · senza bordi",10,muted));
  SourceInitialized+=(s,e)=>{handle=new WindowInteropHelper(this).Handle;SetWindowLong(handle,-20,GetWindowLong(handle,-20)|0x20|0x08000000);};
  timer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(500)};timer.Tick+=(s,e)=>Update();Closed+=(s,e)=>{timer.Stop();};timer.Start();Update();
 }
 void Update(){try{if(tick++%4==0)Saved();string path=System.IO.Path.Combine(Telemetry.ModFolder(game),"telemetry.txt");Snapshot snap=null;if(File.Exists(path)){using(var f=File.Open(path,FileMode.Open,FileAccess.Read,FileShare.ReadWrite|FileShare.Delete))using(var r=new StreamReader(f))snap=Snapshot.Parse(r.ReadToEnd());}if(snap==null||!snap.Fresh()){live.Text="NESSUN DATO RECENTE · avvia il gioco con UE4SS";live.Foreground=muted;foreach(var t in actual.Values)t.Text="—";device.Text="Formato uscita: non disponibile";history.Clear();graph.Points.Clear();last=-1;return;}
  live.Text="LIVE · lettura ogni secondo · "+DateTime.Now.ToString("HH:mm:ss");live.Foreground=lime;foreach(string key in actual.Keys){double n;if(snap.Values.TryGetValue(key,out n)){if(key=="ui")n*=100;if(key=="black")n=Math.Pow(10,n);actual[key].Text=n.ToString(key=="black"?"0.######":"0.##",CultureInfo.CurrentCulture);}else actual[key].Text="n/d";}
  double dev,en;string mode="n/d";if(snap.Values.TryGetValue("device",out dev)){string[] modes={"sRGB","Rec709","Gamma","HDR10 / PQ 1000","HDR10 / PQ 2000","scRGB 1000","scRGB 2000"};mode=dev>=0&&dev<modes.Length?modes[(int)dev]:dev.ToString();}device.Text="Uscita: "+mode+" · HDR "+(snap.Values.TryGetValue("enabled",out en)?(en!=0?"ON":"OFF"):"n/d");double peak;if(snap.Sequence!=last&&snap.Values.TryGetValue("max",out peak)){last=snap.Sequence;history.Enqueue(peak);while(history.Count>60)history.Dequeue();double[] values=history.ToArray();double ceiling=Math.Max(1100,values.Max()*1.1);double width=Math.Max(10,plot.ActualWidth);graph.Points=new PointCollection(values.Select((v,i)=>new Point(i*width/59,34-Math.Min(1,Math.Max(0,v/ceiling))*32)));}
 }catch{live.Text="LETTURA TEMPORANEAMENTE NON DISPONIBILE";foreach(var t in actual.Values)t.Text="—";graph.Points.Clear();}}
 void Saved(){foreach(var t in configured.Values)t.Text="—";if(String.IsNullOrEmpty(game.Config))return;try{string p=System.IO.Path.Combine(game.Config,"Engine.ini");if(!File.Exists(p))return;string e=File.ReadAllText(p);var map=new Dictionary<string,string>{{"max","r.HDR.Display.MaxLuminance"},{"mid","r.HDR.Display.MidLuminance"},{"ui","r.HDR.UI.Level"},{"black","r.HDR.Display.MinLuminanceLog10"}};foreach(var kv in map){double n;if(Double.TryParse(Core.Get(e,"SystemSettings",kv.Value),NumberStyles.Float,CultureInfo.InvariantCulture,out n)){if(kv.Key=="ui")n*=100;if(kv.Key=="black")n=Math.Pow(10,n);configured[kv.Key].Text=n.ToString(kv.Key=="black"?"0.######":"0.##",CultureInfo.CurrentCulture);}}}catch{}}
 public static void Smoke(string imagePath){string dir=System.IO.Path.Combine(System.IO.Path.GetDirectoryName(imagePath),"overlay-test-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(dir);var g=new Game{Id="test",Name="TEST · dati sintetici",Config=dir,Exe=System.IO.Path.Combine(dir,"test.exe")};File.WriteAllText(System.IO.Path.Combine(dir,"Engine.ini"),"[SystemSettings]\nr.HDR.Display.MaxLuminance=1060\nr.HDR.Display.MidLuminance=15\nr.HDR.UI.Level=1\nr.HDR.Display.MinLuminanceLog10=-4\n");Directory.CreateDirectory(Telemetry.ModFolder(g));string path=System.IO.Path.Combine(Telemetry.ModFolder(g),"telemetry.txt");long now=(long)(DateTime.UtcNow-new DateTime(1970,1,1)).TotalSeconds;File.WriteAllText(path,"HDRPILOT=1\ntime="+now+"\nsequence=1\nmax=1060\nmid=15\nui=1\nblack=-4\nenabled=1\ndevice=5\ncomplete=1\n");var overlay=new LiveOverlay(g,"");overlay.Show();overlay.UpdateLayout();overlay.Update();if(overlay.actual["max"].Text!="1060"||overlay.actual["ui"].Text!="100")throw new Exception("Overlay live values failed");var b=new System.Windows.Media.Imaging.RenderTargetBitmap(430,390,96,96,PixelFormats.Pbgra32);b.Render(overlay);var png=new System.Windows.Media.Imaging.PngBitmapEncoder();png.Frames.Add(System.Windows.Media.Imaging.BitmapFrame.Create(b));using(var f=File.Create(imagePath))png.Save(f);File.WriteAllText(path,"HDRPILOT=1\ntime="+(now-10)+"\nmax=1060\ncomplete=1\n");overlay.Update();if(overlay.actual["max"].Text!="—")throw new Exception("Stale overlay values not cleared");overlay.Close();File.WriteAllText(imagePath+".txt","PASS: live fields and percent conversion, stale data removal, overlay render. Synthetic fixture only.");}
}
}

