using System;
using System.IO;
namespace HdrPilot {
public static class PreferencesTests {
 public static void Run(string mode,string root){Directory.CreateDirectory(root);if(mode=="language"){string langRoot=Path.Combine(root,"language");Directory.CreateDirectory(langRoot);string prefFile=Path.Combine(langRoot,"preferences.json");if(File.Exists(prefFile))throw new Exception("Use a fresh language test directory.");if(PreferenceStore.Load(langRoot).Language!="en")throw new Exception("First launch must use English.");foreach(string json in new[]{"{}","{\"Language\":null}","{\"Language\":\"invalid\"}"}){File.WriteAllText(prefFile,json);if(PreferenceStore.Load(langRoot).Language!="en")throw new Exception("Invalid language fallback failed.");}foreach(string lang in new[]{"en","it","es","fr","de","pt"}){File.WriteAllText(prefFile,"{\"Language\":\""+lang+"\"}");if(PreferenceStore.Load(langRoot).Language!=lang)throw new Exception("Saved language changed.");}File.WriteAllText(Path.Combine(root,"language-pass.txt"),"PASS: clean start and invalid language use English; all six saved languages survive loading.");return;}Core.Data=Path.Combine(root,"data");if(mode=="write"){Core.Init();Core.Pref.Language="en";Core.Pref.Theme="light";Core.Pref.HotkeyMods=2;Core.Pref.HotkeyKey=119;Core.Pref.DlssChoices["fixture"]=new DlssOptions{Build="wilsjo2",Scale=63,Style=2,Passes=2,Key="0x23"};Core.SavePrefs();File.WriteAllText(Path.Combine(root,"write.txt"),"Saved in process "+System.Diagnostics.Process.GetCurrentProcess().Id);return;}Core.Init();if(Core.Pref.Language!="en"||Core.Pref.Theme!="light"||Core.Pref.HotkeyMods!=2||Core.Pref.HotkeyKey!=119||Core.Pref.DlssChoices["fixture"].Scale!=63||Core.Pref.DlssChoices["fixture"].Key!="0x23")throw new Exception("Preference persistence failed across process restart.");
  string portable=Path.Combine(root,"HDR-Unlock-Portable-test");Directory.CreateDirectory(Path.Combine(portable,"data"));File.Copy(Path.Combine(Core.Data,"preferences.json"),Path.Combine(portable,"data","preferences.json"),true);string nested=Path.Combine(portable,"HDR-Unlock-Portable-test");Directory.CreateDirectory(nested);if(PreferenceStore.Resolve(nested)!=Path.Combine(portable,"data"))throw new Exception("Nested portable store not reused.");
  File.WriteAllText(Path.Combine(Core.Data,"preferences.json"),"broken json");Core.Init();if(Core.Pref.HotkeyKey!=119)throw new Exception("Backup recovery failed.");Core.SavePrefs();if(!File.ReadAllText(ActivityLog.FilePath).Contains("Preferenze recuperate"))throw new Exception("Recovery not logged.");File.WriteAllText(Path.Combine(root,"read.txt"),"PASS: preferences and DLSS 5 choices survived separate process restart; nested portable reused existing data; corrupt preference restored from backup and logged. Reader PID "+System.Diagnostics.Process.GetCurrentProcess().Id);
 }
}
}
