using System;using System.IO;using System.Linq;using System.Text;using System.Text.RegularExpressions;using System.Collections.Generic;
namespace HdrPilot {
// Deliberately allowlisted: generic UE5 detection is not evidence of HDR compatibility.
public static class RenoGameHdr {
 public const string Marker="hdlss-renodx-engine.json";
 public const string Help="Configure HDR prepares the documented RenoDX Engine.ini settings for Dawnwalker only. Close the game first. Existing settings are backed up. HDR configured describes files, not verified output. Remove RenoDX restores only unchanged managed values; later edits are preserved. Restart the game and verify RenoDX in a loaded scene.";
 public static bool Supported(Game g){return String.Equals(Path.GetFileName(g.Exe),"Dawnwalker.exe",StringComparison.OrdinalIgnoreCase)&&String.Equals(g.Project,"Dawnwalker",StringComparison.OrdinalIgnoreCase);}
 public static string Config(Game g){if(!Supported(g))throw new Exception("No verified RenoDX HDR profile for this game.");string p=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"Dawnwalker","Saved","Config","Windows");if(!String.IsNullOrEmpty(g.Config)&&!String.Equals(Path.GetFullPath(g.Config).TrimEnd('\\'),p,StringComparison.OrdinalIgnoreCase))throw new Exception("Game configuration path does not match the verified profile.");return Path.Combine(p,"Engine.ini");}
 public static readonly string[][] Keys={new[]{"SystemSettings","r.AllowHDR","1"},new[]{"SystemSettings","r.HDR.EnableHDROutput","1"},new[]{"SystemSettings","r.HDR.Display.OutputDevice","3"},new[]{"SystemSettings","r.HDR.Display.ColorGamut","2"},new[]{"SystemSettings","r.HDR.UI.CompositeMode","1"},new[]{"/Script/Engine.RendererSettings","r.LUT.UpdateEveryFrame","1"}};
 public sealed class Record {public string Path,Original,Applied,ReShadePathBefore;public int Attributes;public bool Existed;}
 public static string Hash(string p){return File.Exists(p)?DlssCore.Hash(p):null;}
 static string Root(Game g){return Path.GetDirectoryName(g.Exe);}
 public static bool Managed(Game g){return File.Exists(Path.Combine(Root(g),Marker));}
 public static bool Configured(Game g){try{string p=Config(g);return File.Exists(p)&&Keys.All(k=>Core.Get(File.ReadAllText(p),k[0],k[1])==k[2])&&Core.Get(File.ReadAllText(Path.Combine(Root(g),"ReShade.ini")),"renodx","Set_Path")=="0";}catch{return false;}}
 public static string Merge(string text,string original,string applied){foreach(var k in Keys)if(Core.Get(text,k[0],k[1])==Core.Get(applied,k[0],k[1])){string old=Core.Get(original,k[0],k[1]);text=old==null?RemoveKey(text,k[0],k[1]):Core.Set(text,k[0],k[1],old);}return text;}
 static string RemoveKey(string text,string section,string key){bool inside=false;return String.Join(text.Contains("\r\n")?"\r\n":"\n",Regex.Split(text,"\r?\n").Where(l=>{var m=Regex.Match(l,@"^\s*\[([^\]]+)\]\s*$");if(m.Success)inside=String.Equals(m.Groups[1].Value,section,StringComparison.OrdinalIgnoreCase);return !(inside&&Regex.IsMatch(l,@"^\s*"+Regex.Escape(key)+@"\s*=",RegexOptions.IgnoreCase));}));}
 public static DlssPlan Prepare(Game g){Core.Closed(g);string path=Config(g),root=Root(g),marker=Path.Combine(root,Marker);if(!File.Exists(Path.Combine(Path.GetDirectoryName(path),"GameUserSettings.ini")))throw new Exception("Start the game once before configuring HDR.");if(!File.Exists(Path.Combine(root,"renodx-ue-extended.addon64")))throw new Exception("Install RenoDX Unreal Engine Extended first.");if(File.Exists(Path.Combine(root,"AutoHDR.addon64")))throw new Exception("Remove AutoHDR before configuring RenoDX HDR.");string text=File.Exists(path)?File.ReadAllText(path):"";var r=Managed(g)?Core.Json.Deserialize<Record>(File.ReadAllText(marker)):new Record{Path=path,Original=text,Existed=File.Exists(path),Attributes=File.Exists(path)?(int)File.GetAttributes(path):(int)FileAttributes.Normal};if(r.Path!=path)throw new Exception("HDR backup belongs to another configuration.");if(Managed(g)&&!Keys.All(k=>Core.Get(text,k[0],k[1])==Core.Get(r.Applied,k[0],k[1])))throw new Exception("HDR settings changed: restore the managed profile before configuring again.");string after=text;foreach(var k in Keys)after=Core.Set(after,k[0],k[1],k[2]);r.Applied=after;if(!Managed(g)){string ini=Path.Combine(root,"ReShade.ini");r.ReShadePathBefore=File.Exists(ini)?Core.Get(File.ReadAllText(ini),"renodx","Set_Path"):null;}var p=new DlssPlan{Folder=root,Summary=Appearance.Localize("Configure HDR"),EnginePatch=new RenoEnginePatch{Path=path,Expected=Hash(path),Text=after,Attributes=r.Attributes|(int)FileAttributes.ReadOnly}};p.Changes.Add(new DlssChange{Name=Marker,Expected=Hash(marker),Bytes=Encoding.UTF8.GetBytes(Core.Json.Serialize(r))});string rp=Path.Combine(root,"ReShade.ini");string ri=File.Exists(rp)?File.ReadAllText(rp):"";p.Changes.Add(new DlssChange{Name="ReShade.ini",Expected=Hash(rp),Bytes=Encoding.UTF8.GetBytes(Core.Set(ri,"renodx","Set_Path","0"))});return p;}
 public static void AttachRestore(Game g,DlssPlan plan){if(!Managed(g))return;string path=Config(g),marker=Path.Combine(Root(g),Marker);var r=Core.Json.Deserialize<Record>(File.ReadAllText(marker));if(r.Path!=path)throw new Exception("HDR backup belongs to another configuration.");if(File.Exists(path)){string current=File.ReadAllText(path),after=Merge(current,r.Original,r.Applied);bool exact=current==r.Applied;plan.EnginePatch=new RenoEnginePatch{Path=path,Expected=Hash(path),Text=exact?r.Original:after,Delete=exact&&!r.Existed,Attributes=r.Attributes};}string rp=Path.Combine(Root(g),"ReShade.ini");if(File.Exists(rp)){string ri=File.ReadAllText(rp);if(Core.Get(ri,"renodx","Set_Path")=="0"){string restored=r.ReShadePathBefore==null?RemoveKey(ri,"renodx","Set_Path"):Core.Set(ri,"renodx","Set_Path",r.ReShadePathBefore);plan.Changes.Add(new DlssChange{Name="ReShade.ini",Expected=Hash(rp),Bytes=Encoding.UTF8.GetBytes(restored)});}}plan.Changes.Add(new DlssChange{Name=Marker,Expected=Hash(marker),Delete=true});}
}
public sealed class RenoEnginePatch {
 public string Path,Expected,Text;public int Attributes;public bool Delete;
 public void Validate(Game g){Core.Closed(g);if(Path!=RenoGameHdr.Config(g)||RenoGameHdr.Hash(Path)!=Expected)throw new Exception("HDR configuration changed; try again.");for(var d=new DirectoryInfo(System.IO.Path.GetDirectoryName(Path));d!=null;d=d.Parent)if((d.Attributes&FileAttributes.ReparsePoint)!=0)throw new Exception("Linked configuration folders are not supported.");if(File.Exists(Path)&&(File.GetAttributes(Path)&FileAttributes.ReparsePoint)!=0)throw new Exception("Linked configuration files are not supported.");}
 public void Commit(Game g,string recovery){Validate(g);byte[] before=File.Exists(Path)?File.ReadAllBytes(Path):null;var attrs=File.Exists(Path)?File.GetAttributes(Path):FileAttributes.Normal;string backup=System.IO.Path.Combine(recovery,"Engine.ini.before");if(before!=null)File.WriteAllBytes(backup,before);File.WriteAllText(System.IO.Path.Combine(recovery,"engine-config.json"),Core.Json.Serialize(new{Path=Path,Existed=before!=null,Attributes=(int)attrs}));try{if(File.Exists(Path))File.SetAttributes(Path,FileAttributes.Normal);if(Delete)File.Delete(Path);else{File.WriteAllText(Path,Text,new UTF8Encoding(false));File.SetAttributes(Path,(FileAttributes)Attributes);if(File.ReadAllText(Path)!=Text)throw new IOException("HDR configuration verification failed.");}}catch{if(File.Exists(Path))File.SetAttributes(Path,FileAttributes.Normal);if(before==null){if(File.Exists(Path))File.Delete(Path);}else{File.WriteAllBytes(Path,before);File.SetAttributes(Path,attrs);}throw;}}
}
}

