using System;using System.IO;using System.Linq;using System.Text;using System.Collections.Generic;using System.Security.Cryptography;
namespace HdrPilot {
public static class SavedComponents {
 static string L(string s){return Appearance.Localize(s);}
 static string Home(Game g){using(var h=SHA256.Create()){string key=BitConverter.ToString(h.ComputeHash(Encoding.UTF8.GetBytes(Path.GetFullPath(g.Exe).ToUpperInvariant()))).Replace("-","");return Path.Combine(Core.Data,"saved-components",key);}}
 static string Pointer(Game g){return Path.Combine(Home(g),"current.json");}
 static string[] Allowed= DlssLibraries.Names.Concat(Streamline.Names).Concat(new[]{"nvngx_dlssnr.dll"}).ToArray();
 static List<string> Files(Game g){return DlssLibraries.ScanNames(g,Allowed).Select(x=>x.Path).Distinct(StringComparer.OrdinalIgnoreCase).ToList();}
 public static bool Exists(Game g){return File.Exists(Pointer(g));}
 static DlssManifest Read(Game g){var m=Core.Json.Deserialize<DlssManifest>(File.ReadAllText(Pointer(g)));if(m==null||m.Game!=g.Id||!String.Equals(m.Folder,Path.GetFullPath(g.Root),StringComparison.OrdinalIgnoreCase)||m.Files==null||m.Files.Count==0)throw new Exception(L("Invalid saved configuration."));var paths=new HashSet<string>(StringComparer.OrdinalIgnoreCase);foreach(var f in m.Files){DlssCore.Safe(g.Root,f.Name);if(!Allowed.Contains(Path.GetFileName(f.Name),StringComparer.OrdinalIgnoreCase)||!paths.Add(f.Name))throw new Exception(L("Invalid saved configuration."));string file=DlssCore.Safe(Core.Data,f.Backup);string home=Path.GetFullPath(Home(g))+Path.DirectorySeparatorChar;if(!file.StartsWith(home,StringComparison.OrdinalIgnoreCase)||!File.Exists(file)||DlssCore.Hash(file)!=f.After)throw new Exception(L("Saved configuration files are missing or changed."));}return m;}
 public static void Save(Game g){Core.Closed(g);if(g.ProtectedInstall)throw new Exception(g.Evidence);var files=Files(g);if(files.Count==0)throw new Exception(L("No DLL components found."));string root=Path.GetFullPath(g.Root).TrimEnd('\\'),home=Home(g),dir=Path.Combine(home,Guid.NewGuid().ToString("N"));Directory.CreateDirectory(dir);var m=new DlssManifest{Game=g.Id,Folder=Path.GetFullPath(g.Root),Release=DateTime.Now.ToString("yyyy-MM-dd HH:mm"),PreviousOwner="User-confirmed working configuration"};foreach(var file in files){if(!file.StartsWith(root+"\\",StringComparison.OrdinalIgnoreCase))throw new Exception(L("Invalid saved configuration."));string name=file.Substring(root.Length+1),dest=DlssCore.Safe(dir,name),hash=DlssCore.Hash(file);Directory.CreateDirectory(Path.GetDirectoryName(dest));File.Copy(file,dest);if(DlssCore.Hash(dest)!=hash||DlssCore.Hash(file)!=hash)throw new Exception(L("Files changed while saving. Close the game and retry."));m.Files.Add(new DlssFile{Name=name,After=hash,Backup=dest.Substring(Path.GetFullPath(Core.Data).TrimEnd('\\').Length+1)});}string tmp=Path.Combine(home,"current-"+Guid.NewGuid().ToString("N")+".json");File.WriteAllText(tmp,Core.Json.Serialize(m),new UTF8Encoding(false));if(File.Exists(Pointer(g)))File.Replace(tmp,Pointer(g),Path.Combine(home,"previous-"+Guid.NewGuid().ToString("N")+".json"));else File.Move(tmp,Pointer(g));}
 public static int Differences(Game g){var m=Read(g);return m.Files.Count(f=>!File.Exists(DlssCore.Safe(g.Root,f.Name))||DlssCore.Hash(DlssCore.Safe(g.Root,f.Name))!=f.After);}
 public static string State(Game g){if(!Exists(g))return L("No working configuration saved.");try{var m=Read(g);int count=Differences(g);return (count==0?L("Saved configuration matches installed files."):L("Changed files detected")+": "+count)+" · "+m.Release;}catch(Exception ex){return ex.Message;}}
 public static DlssPlan Restore(Game g){Core.Closed(g);if(g.ProtectedInstall)throw new Exception(g.Evidence);var m=Read(g);var names=new HashSet<string>(m.Files.Select(x=>x.Name),StringComparer.OrdinalIgnoreCase);foreach(var group in m.Files.Where(x=>Streamline.Names.Contains(Path.GetFileName(x.Name),StringComparer.OrdinalIgnoreCase)).GroupBy(x=>Path.GetDirectoryName(DlssCore.Safe(g.Root,x.Name))))if(Directory.Exists(group.Key))foreach(var f in Directory.GetFiles(group.Key,"sl.*.dll")){string rel=f.Substring(Path.GetFullPath(g.Root).TrimEnd('\\').Length+1);if(!names.Contains(rel))throw new Exception(L("Streamline folder has additional components. Restore stopped to avoid mixing packages.")+" "+rel);}
 var plan=new DlssPlan{Folder=Path.GetFullPath(g.Root),NativeSwap=true,Summary=L("Restore saved DLL configuration. Current files are backed up first; other mods are preserved.")};foreach(var f in m.Files){string dest=DlssCore.Safe(g.Root,f.Name),hash=File.Exists(dest)?DlssCore.Hash(dest):null;if(hash!=f.After)plan.Changes.Add(new DlssChange{Name=f.Name,Source=DlssCore.Safe(Core.Data,f.Backup),SourceHash=f.After,Expected=hash});}if(plan.Changes.Count==0)throw new Exception(L("Saved configuration matches installed files."));return plan;}
}
}
