using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Interop;
using System.Windows.Media;
using System.Windows.Shapes;
using System.Windows.Threading;
namespace HdrPilot {
public sealed class SceneOverlay:Window {
 [DllImport("user32.dll")]static extern bool GetWindowRect(IntPtr h,out HdrCapture.Rect rect);
 IntPtr overlayHandle;
 [DllImport("user32.dll")]static extern int GetWindowLong(IntPtr h,int n);
 [DllImport("user32.dll")]static extern int SetWindowLong(IntPtr h,int n,int value);
 readonly Game game;readonly string monitor;readonly CancellationTokenSource stop=new CancellationTokenSource();readonly object gate=new object();SceneStats? latest;bool unchanged;string message="Attendi il gioco in primo piano";volatile bool suspended=true;string lastLogged;Task worker;DispatcherTimer timer;TextBlock status,peak,mean,min,reference,scale,details,engine;Canvas canvas;Polyline line;Queue<SceneStats> history=new Queue<SceneStats>();DateTime last;int ticks;double target;
 static Brush Gold=new SolidColorBrush(Color.FromRgb(230,172,80));static Brush Muted=new SolidColorBrush(Color.FromRgb(150,163,178));
 static TextBlock Text(string text,int size,Brush brush){return new TextBlock{Text=text,FontSize=size,Foreground=brush,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,4,0,6)};}
 public SceneOverlay(Game g,string device,bool test=false){game=g;monitor=device;Title="HDLSS · luminanza scena";Width=470;Height=470;WindowStyle=WindowStyle.None;ResizeMode=ResizeMode.NoResize;Background=new SolidColorBrush(Color.FromRgb(13,18,25));Foreground=Brushes.White;FontFamily=new FontFamily("Cascadia Mono, Consolas");Topmost=true;ShowInTaskbar=false;ShowActivated=false;var border=new Border{BorderBrush=Gold,BorderThickness=new Thickness(1),Padding=new Thickness(18)};var stack=new StackPanel();border.Child=stack;Content=border;stack.Children.Add(Text("HDLSS "+System.Reflection.Assembly.GetExecutingAssembly().GetName().Version.ToString(3)+" / LUMINANZA DELLA SCENA",11,Gold));stack.Children.Add(Text(game.Name,13,Brushes.White));status=Text(message,11,Muted);stack.Children.Add(status);
 var grid=new Grid();for(int i=0;i<3;i++)grid.ColumnDefinitions.Add(new ColumnDefinition());string[] names={"PICCO · nit","MEDIA · nit","MINIMO · nit"};for(int i=0;i<3;i++){var col=new StackPanel();Grid.SetColumn(col,i);col.Children.Add(Text(names[i],10,Muted));var v=Text("—",26,i==0?Gold:Brushes.White);col.Children.Add(v);if(i==0)peak=v;if(i==1)mean=v;if(i==2)min=v;grid.Children.Add(col);}stack.Children.Add(grid);reference=Text("Picco richiesto nel file: n/d",11,Muted);stack.Children.Add(reference);engine=Text("",10,Muted);stack.Children.Add(engine);scale=Text("PICCO DELLA SCENA · ultimi 24 secondi",10,Muted);stack.Children.Add(scale);canvas=new Canvas{Height=65,ClipToBounds=true,Background=new SolidColorBrush(Color.FromRgb(22,30,40))};line=new Polyline{Stroke=Gold,StrokeThickness=2};canvas.Children.Add(line);stack.Children.Add(canvas);details=Text("ScRGB · area di gioco escluso il riquadro overlay\nObiettivo: 5 letture/s · nessuna immagine salvata",10,Muted);stack.Children.Add(details);stack.Children.Add(Text("Segnale Windows, HUD incluso; riquadro overlay escluso.\nValori arrotondati; non misura fisica del pannello.",10,Muted));stack.Children.Add(Text(Shortcut.Label(Core.Pref.HotkeyMods,Core.Pref.HotkeyKey)+" · mostra/nascondi",10,Gold));
 SourceInitialized+=(s,e)=>{IntPtr h=new WindowInteropHelper(this).Handle;SetWindowLong(h,-20,GetWindowLong(h,-20)|0x20|0x08000000);overlayHandle=h;OverlayDiagnostics.Log("Cattura con esclusione geometrica del riquadro overlay; nessuna protezione display applicata.");};
 IsVisibleChanged+=(s,e)=>{suspended=!IsVisible;if(suspended){State("Overlay nascosto · cattura sospesa",null);Paint();}else{OverlayDiagnostics.Log("Overlay mostrato; monitor "+monitor+"; gioco "+game.Name);}};
 Loaded+=(s,e)=>{if(!test&&worker==null)worker=Task.Factory.StartNew(Loop,stop.Token,TaskCreationOptions.LongRunning,TaskScheduler.Default);};timer=new DispatcherTimer{Interval=TimeSpan.FromMilliseconds(200)};timer.Tick+=(s,e)=>Paint();Closed+=(s,e)=>{stop.Cancel();timer.Stop();};timer.Start();ReadTarget();}
 void State(string text,SceneStats? value,bool reuse=false){lock(gate){message=text;latest=value;unchanged=reuse;if(text!=lastLogged){lastLogged=text;OverlayDiagnostics.Log(text);}}}
 void Loop(){HdrCapture capture=null;var dpi=new CaptureDpi();try{while(!stop.IsCancellationRequested){try{HdrCapture.Rect area;string reason;if(suspended){State("Overlay nascosto · cattura sospesa",null);if(capture!=null){capture.Dispose();capture=null;}}else if(!HdrCapture.GameArea(game,out area,out reason)){State(reason,null);if(capture!=null){capture.Dispose();capture=null;}}else{if(capture==null)capture=new HdrCapture(monitor);HdrCapture.Rect omit;if(!GetWindowRect(overlayHandle,out omit))throw new Exception("Posizione overlay non disponibile: misura sospesa.");omit.Left-=8;omit.Top-=8;omit.Right+=8;omit.Bottom+=8;var sample=capture.Capture(area,omit);HdrCapture.Rect after;if(!HdrCapture.GameArea(game,out after)||area.Left!=after.Left||area.Top!=after.Top||area.Right!=after.Right||area.Bottom!=after.Bottom)State("In pausa · finestra del gioco cambiata",null);else if(sample.HasValue)State("LIVE · scRGB · riquadro overlay escluso",sample);else{SceneStats? cached;lock(gate)cached=latest;if(cached.HasValue)State("ULTIMO CAMPIONE · nessun nuovo fotogramma",cached,true);else State("In attesa del primo fotogramma HDR",null);}}}catch(MaskedFrameException e){State(e.Message,null);if(stop.Token.WaitHandle.WaitOne(1000))break;}catch(Exception e){State(e.Message,null);if(capture!=null){capture.Dispose();capture=null;}if(stop.Token.WaitHandle.WaitOne(1800))break;}if(stop.Token.WaitHandle.WaitOne(200))break;}}finally{if(capture!=null)capture.Dispose();dpi.Dispose();}}
 static string Field(Snapshot s,string key,string format="0.##"){double v;return s.Values.TryGetValue(key,out v)?v.ToString(format,CultureInfo.CurrentCulture):"n/d";}
 void ReadEngine(){try{string path=System.IO.Path.Combine(Telemetry.ModFolder(game),"telemetry.txt");Snapshot s=null;if(File.Exists(path))using(var f=File.Open(path,FileMode.Open,FileAccess.Read,FileShare.ReadWrite|FileShare.Delete))using(var r=new StreamReader(f))s=Snapshot.Parse(r.ReadToEnd());
  if(s==null||!s.Fresh()){engine.Text="MOTORE · dati live non disponibili (UE4SS facoltativo)\nLa misura dei pixel funziona senza UE4SS.";return;}
  engine.Text="MOTORE LIVE · HDR="+Field(s,"enabled")+" · output="+Field(s,"device")+"\nPicco CVar="+Field(s,"max")+" · medio="+Field(s,"mid")+" · UI="+Field(s,"ui")+" (valori motore)";
 }catch{engine.Text="MOTORE · telemetria non disponibile\nLa misura dei pixel resta indipendente.";}}
 void ReadTarget(){target=0;try{if(!String.IsNullOrEmpty(game.Config)){string p=System.IO.Path.Combine(game.Config,"Engine.ini");double.TryParse(Core.Get(File.ReadAllText(p),"SystemSettings","r.HDR.Display.MaxLuminance"),NumberStyles.Float,CultureInfo.InvariantCulture,out target);}}catch{}reference.Text="Picco richiesto nel file: "+(target>0?target.ToString("0")+" nit":"n/d");}
 void Paint(){if(ticks%5==0)ReadEngine();if(ticks++%10==0){ReadTarget();if(!suspended)OverlayWindow.BringAbove(this);}SceneStats? value;string text;bool reuse;lock(gate){value=latest;text=message;reuse=unchanged;}status.Text=text;if(!value.HasValue||(!reuse&&(DateTime.UtcNow-value.Value.Time).TotalSeconds>1.5)){peak.Text=mean.Text=min.Text="—";history.Clear();line.Points.Clear();if(value.HasValue)status.Text="Nessun fotogramma HDR recente";return;}var s=value.Value;bool over=target>0&&s.Peak>target+1;peak.Foreground=over?Brushes.OrangeRed:Gold;if(over)status.Text="SUPERAMENTO DEL PICCO · "+(s.Peak-target).ToString("0")+" nit oltre il richiesto";peak.Text=s.Peak.ToString("0");mean.Text=s.Mean.ToString("0");min.Text=s.Min.ToString("0");if(s.Time!=last){history.Enqueue(s);last=s.Time;}while(history.Count>0&&(s.Time-history.Peek().Time).TotalSeconds>24)history.Dequeue();double ceiling=Math.Max(100,Math.Max(target,history.Max(v=>v.Peak))*1.1);scale.Text="PICCO SCENA · 24 s · scala 0–"+ceiling.ToString("0")+" nit";line.Points=new PointCollection(history.Select(v=>new Point(Math.Max(0,24-(s.Time-v.Time).TotalSeconds)/24*Math.Max(1,canvas.ActualWidth),63-Math.Min(1,v.Peak/ceiling)*60)));details.Text="ScRGB · "+s.Pixels.ToString("N0")+" pixel · analisi "+s.AnalysisMs.ToString("0")+" ms\nCampione: "+s.Time.ToLocalTime().ToString("HH:mm:ss.fff")+" · età "+Math.Max(0,(DateTime.UtcNow-s.Time).TotalSeconds).ToString("0.0")+" s";}
 public static void Smoke(string path){var g=new Game{Name="TEST · scena sintetica",Exe="test.exe"};var w=new SceneOverlay(g,FormsScreen(),true);w.Show();w.UpdateLayout();w.target=1060;var now=DateTime.UtcNow;for(int i=0;i<100;i++)w.history.Enqueue(new SceneStats{Peak=80+800*Math.Abs(Math.Sin(i/9.0)),Time=now.AddSeconds((i-100)*0.2)});w.State("TEST GRAFICO · dati sintetici",new SceneStats{Peak=834,Mean=74,Min=0,Pixels=4953600,AnalysisMs=33,Time=now});w.Paint();w.UpdateLayout();if(w.peak.Text!="834"||w.mean.Text!="74")throw new Exception("Scene overlay fields");var image=new System.Windows.Media.Imaging.RenderTargetBitmap((int)w.ActualWidth,(int)w.ActualHeight,96,96,PixelFormats.Pbgra32);image.Render(w);var encoder=new System.Windows.Media.Imaging.PngBitmapEncoder();encoder.Frames.Add(System.Windows.Media.Imaging.BitmapFrame.Create(image));using(var file=File.Create(path))encoder.Save(file);w.State("Scena invariata",new SceneStats{Peak=321,Mean=40,Min=0,Pixels=4,Time=DateTime.UtcNow.AddSeconds(-10)},true);w.Paint();if(w.peak.Text!="321")throw new Exception("Unchanged valid frame lost");w.State("Fotogramma obsoleto",new SceneStats{Peak=321,Mean=40,Min=0,Pixels=4,Time=DateTime.UtcNow.AddSeconds(-10)});w.Paint();if(w.peak.Text!="—")throw new Exception("Stale non-reused frame retained");OverlayWindow.Toggle(w);if(OverlayWindow.IsWindowVisible(new WindowInteropHelper(w).Handle)||!w.suspended)throw new Exception("Hidden overlay still visible or capturing");OverlayWindow.Toggle(w);if(!OverlayWindow.IsWindowVisible(new WindowInteropHelper(w).Handle)||w.suspended)throw new Exception("Overlay did not return");OverlayWindow.Toggle(w);OverlayWindow.Toggle(w);w.State("In pausa",null);w.Paint();if(w.peak.Text!="—"||w.line.Points.Count!=0)throw new Exception("Stale scene values");File.WriteAllText(path+".txt","PASS: native HWND hide/show cycles and capture suspension, unchanged-frame retention and stale-frame rejection, scene values, history graph, clearing on pause; geometric overlay exclusion enabled. Render uses synthetic data, not captured gameplay.");w.Close();}
 static string FormsScreen(){return System.Windows.Forms.Screen.PrimaryScreen.DeviceName;}
 public static void NumericTest(string path){IntPtr data=Marshal.AllocHGlobal(48);try{short[] pixels=new short[24];for(int i=0;i<4;i++){short half=new short[]{0,15360,17152,19008}[i];for(int c=0;c<3;c++)pixels[(i/2)*12+(i%2)*4+c]=half;}Marshal.Copy(pixels,0,data,pixels.Length);var s=HdrCapture.Analyze(data,24,0,0,2,2);if(s.Min!=0||Math.Abs(s.Peak-1000)>0.01||Math.Abs(s.Mean-340)>0.01||s.Pixels!=4)throw new Exception("FP16 luminance / padded pitch failure: "+s.Peak+" "+s.Mean);s=HdrCapture.Analyze(data,24,1,1,1,1);if(Math.Abs(s.Peak-1000)>0.01)throw new Exception("Crop failure");var omitted=HdrCapture.Analyze(data,24,0,0,2,2,new HdrCapture.Rect{Left=1,Top=1,Right=2,Bottom=2});if(omitted.Pixels!=3||Math.Abs(omitted.Peak-280)>0.01||Math.Abs(omitted.Mean-120)>0.01)throw new Exception("Overlay exclusion failure");bool rejected=false;try{HdrCapture.Analyze(data,24,0,0,2,2,new HdrCapture.Rect{Left=0,Top=0,Right=2,Bottom=2});}catch(Exception){rejected=true;}if(!rejected)throw new Exception("Fully obscured area accepted");File.WriteAllText(path,"PASS: overlay excluded from peak/mean/count; fully obscured area rejected; FP16 black, 80 / 280 / 1000 nit whites; full-frame min/max/mean; padded row pitch; cropped area.\n");}finally{Marshal.FreeHGlobal(data);}}
 public static void CaptureTest(string path){var displays=Displays.Scan();if(displays.Count==0)throw new Exception("No monitor");using(var dpi=new CaptureDpi())using(var c=new HdrCapture(displays[0].Device)){SceneStats? value=null;for(int i=0;i<6&&!value.HasValue;i++)value=c.Capture(c.Bounds);if(!value.HasValue)throw new Exception("No fresh FP16 frame");var s=value.Value;File.WriteAllText(path,"LIVE CAPTURE: "+c.DeviceName+"; output colorspace "+c.ColorSpace+"; "+s.Pixels+" pixels; min "+s.Min.ToString("F3")+"; mean "+s.Mean.ToString("F3")+"; peak "+s.Peak.ToString("F3")+" nit; analyze "+s.AnalysisMs.ToString("F1")+" ms. Desktop test, not game validation. No image stored.");}}
}
}
