$ErrorActionPreference='Stop'
$p='work\hdr-pilot\Core.cs';$s=Get-Content $p -Raw;$s=$s.Replace('public class Preferences {','public class Preferences {public uint HotkeyMods=6; public uint HotkeyKey=72; public string MonitorId; public Dictionary<string,int> MonitorModes=new Dictionary<string,int>(); ');Set-Content $p $s -Encoding utf8
$p='work\hdr-pilot\Displays.cs';$s=Get-Content $p -Raw;$s=$s.Replace('String.Equals(Name.Trim(),"AW3423DW",','String.Equals(Name.Trim(),"Dell AW3423DW",StringComparison.OrdinalIgnoreCase)||String.Equals(Name.Trim(),"AW3423DW",');Set-Content $p $s -Encoding utf8
$p='work\hdr-pilot\build.ps1';$s=Get-Content $p -Raw;$s=$s.Replace('"$PSScriptRoot\Overlay.cs"','"$PSScriptRoot\Overlay.cs" "$PSScriptRoot\Ui.cs" "$PSScriptRoot\Displays.cs"');Set-Content $p $s -Encoding utf8
$p='work\hdr-pilot\Overlay.cs';$s=Get-Content $p -Raw;$s=$s.Replace('stack.Children.Add(Text("Ctrl + Shift + H: mostra/nascondi · finestra senza bordi",10,muted));','stack.Children.Add(Text(Shortcut.Label(Core.Pref.HotkeyMods,Core.Pref.HotkeyKey)+": mostra/nascondi · senza bordi",10,muted));');$s=$s.Replace('HwndSource.FromHwnd(handle).AddHook(Hook);if(!RegisterHotKey(handle,7021,0x0002|0x0004,0x48))live.Text="Scorciatoia occupata: usa il pulsante nell''app.";','');$s=$s.Replace('if(handle!=IntPtr.Zero)UnregisterHotKey(handle,7021);','');Set-Content $p $s -Encoding utf8
$p='work\hdr-pilot\Main.xaml';$s=Get-Content $p -Raw;$s=$s.Replace('PORTABLE / 1.0','PORTABLE / 1.1');$s=$s.Replace('<Button x:Name="Help"','<Button x:Name="Hotkey" Content="Tasto overlay…" Margin="0,0,0,10"/><TextBlock x:Name="HotkeyState" Text="Ctrl + Shift + H" TextWrapping="Wrap" Foreground="#B8ED71" FontSize="10" Margin="0,0,0,14"/><Button x:Name="Help"');$s=$s.Replace('<TextBlock Text="AW3423DW"','<TextBlock x:Name="MonitorLabel" Text="Monitor" TextWrapping="Wrap"');$s=$s.Replace('Text="Profilo iniziale · 1060 nit"','Text="Profilo del display selezionato" TextWrapping="Wrap"');$s=$s.Replace('<Grid Margin="0,0,0,7">','<Border Background="#1C2631" CornerRadius="8" Padding="12" Margin="0,0,0,16"><StackPanel><TextBlock Text="MONITOR E CONSIGLI" Foreground="#B8ED71" FontSize="10"/><ComboBox x:Name="Monitors" Margin="0,8,0,8"/><ComboBox x:Name="MonitorMode" Margin="0,0,0,8"/><TextBlock x:Name="MonitorAdvice" TextWrapping="Wrap" Foreground="#ADBACA" FontSize="11"/><Button x:Name="RefreshMonitors" Content="Rileva di nuovo" Padding="8,5" Margin="0,10,0,0"/></StackPanel></Border><Grid Margin="0,0,0,7">');$s=$s.Replace('Text="Base AW3423DW: 1060 nit"','x:Name="PeakAdvice" Text="Consiglio: scegli un monitor"');
$helps=@{
 Peak='Il limite richiesto alla curva HDR del gioco, in nit. Non aumenta le capacità fisiche del display e non misura i pixel della scena. Usa il valore calibrato per la modalità HDR attiva sul monitor. Valori troppo alti possono perdere dettaglio nelle luci; troppo bassi possono comprimerle. Intervallo: 200–10000. Per AW3423DW: 1000 nominali in Peak 1000; 1060 è la personalizzazione scelta da te, non una misura del tuo pannello.';
 Mid='Controlla la luminanza del grigio al 18% nella curva HDR, non quella del bianco. Base Unreal: 15 nit. Aumentarlo può schiarire i toni intermedi; ridurlo può scurirli. Parti da 15 e cambia poco alla volta, verificando visi e ombre nella stessa scena. Intervallo: 5–100 nit. Non deriva dal picco del monitor e alcuni giochi ignorano questo parametro.';
 Ui='Regola il moltiplicatore della luminosità dell''interfaccia quando il gioco usa la composizione UI HDR di Unreal. 100% significa moltiplicatore 1, non 100 nit. Riduci se menu e HUD abbagliano; aumenta se sono poco leggibili. Intervallo: 25–300%. Può non agire su elementi disegnati direttamente nella scena o gestiti diversamente dal gioco.';
 Black='Il nero fisico di un OLED può essere zero. Questo controllo agisce invece sul minimo logaritmico della curva Unreal: Base = 0,0001 nit (−4); Quasi zero = 0,000001 nit (−6). Scrivere 0 nella variabile logaritmica significherebbe 1 nit. Parti dalla base: quasi zero non corregge necessariamente neri sollevati dal gioco. Conserva valore attuale mantiene un''impostazione personalizzata già presente.'
}
foreach($name in @('Peak','Mid','Ui')){ $pat='(<TextBox x:Name="'+$name+'"[^>]*/></Grid>)';$help=[System.Security.SecurityElement]::Escape($helps[$name]);$s=[regex]::Replace($s,$pat,'$1<Expander Header="Come regolarlo" Foreground="#ADBACA" Margin="0,0,0,6"><TextBlock Text="'+$help+'" TextWrapping="Wrap" FontSize="11" Margin="0,8,0,8"/></Expander>') }
$help=[System.Security.SecurityElement]::Escape($helps.Black);$s=$s.Replace('<TextBlock x:Name="ReadState"','<Expander Header="Capire il punto di nero" Foreground="#ADBACA" Margin="0,8,0,0"><TextBlock Text="'+$help+'" TextWrapping="Wrap" FontSize="11" Margin="0,8,0,8"/></Expander><TextBlock x:Name="ReadState"');Set-Content $p $s -Encoding utf8

